//  ValidationRuleParityTests
//  The transcribed rule table, diffed against the reference's own.
//
//  `ValidationRules.table` is a transcription of `validators/*.ts`, and a transcription rots
//  silently: a rule added, reordered or retyped upstream is invisible here until a client is
//  refused something it should be allowed. That failure is the expensive direction — a request
//  that used to work and now 400s — so the table is checked mechanically rather than read.
//
//  The fixture is generated by `Tools/validation-rules/extract.py` from the reference sources.
//  Regenerate it when the Node validators change; this suite fails loudly when the two drift,
//  which is the point.
//
//  FIELD ORDER IS ASSERTED, not just membership. Only the first failure is reported, in
//  declaration order (`validators/index.ts:getFirstError`), so reordering two fields changes
//  the sentence a client is shown. That is why the fixture is a list of pairs.
//
//  A deliberate divergence is listed in `knowinglyDivergent` with a reason, in the shape
//  `RequestParameterParityTests.knowinglyInert` established. There is one today. A divergence
//  that is not on that list fails.

import BBHTTPAPI
import Foundation
import Testing

@Suite("Validation rule parity")
struct ValidationRuleParityTests {

  // MARK: - The fixture

  private struct Fixture: Decodable {
    let reactions: [String]
    let ruleSets: [String: [RuleSetField]]
    let routes: [ValidatedRoute]
  }

  /// `["limit", ["numeric", "min:1", "max:1000"]]` — a pair, so order survives the round trip.
  private struct RuleSetField: Decodable {
    let field: String
    let rules: [String]

    init(from decoder: any Decoder) throws {
      var container = try decoder.unkeyedContainer()
      field = try container.decode(String.self)
      rules = try container.decode([String].self)
    }
  }

  private struct ValidatedRoute: Decodable {
    let method: String
    let path: String
    let validator: String
    // swift-format-ignore: AlwaysUseLowerCamelCase
    let method_name: String
  }

  private static func fixture() throws -> Fixture {
    let url = URL(fileURLWithPath: #filePath)
      .deletingLastPathComponent()
      .appendingPathComponent("Fixtures/node-validation-rules.json")
    return try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
  }

  /// Which reference rule set each handler transcribes.
  ///
  /// Written out rather than derived: the reference attaches validators by route in
  /// `httpRoutes.ts`, and the mapping from its route paths to our `HandlerID`s is the one
  /// step a scanner cannot take. Every entry is checked against the fixture below, so a
  /// wrong name here fails rather than silently skipping a rule set.
  private static let transcribed: [HandlerID: String] = [
    .serverMarkAlertRead: "alertsValidator.readRules",
    .attachmentFind: "attachmentValidator.findParamRules",
    .attachmentDownload: "attachmentValidator.downloadRules",
    .attachmentForceDownload: "attachmentValidator.downloadRules",
    .attachmentBlurhash: "attachmentValidator.downloadRules",
    .chatMessages: "chatValidator.getMessagesRules",
    .chatQuery: "chatValidator.queryRules",
    .chatUpdate: "chatValidator.updateRules",
    .chatCreate: "chatValidator.createRules",
    .chatAddParticipant: "chatValidator.toggleParticipantRules",
    .chatRemoveParticipant: "chatValidator.toggleParticipantRules",
    .fcmRegisterDevice: "fcmValidator.registerRules",
    .handleFind: "handleValidator.findRules",
    .handleFocusStatus: "handleValidator.findRules",
    .handleQuery: "handleValidator.queryBodyRules",
    .handleIMessageAvailability: "handleValidator.availabilityParamRules",
    .handleFaceTimeAvailability: "handleValidator.availabilityParamRules",
    .messageCount: "messageValidator.countParamRules",
    .messageCountUpdated: "messageValidator.updatedCountParamRules",
    .messageFind: "messageValidator.findParamRules",
    .messageQuery: "messageValidator.queryBodyRules",
    .messageSendText: "messageValidator.sendTextRules",
    .messageSendAttachment: "messageValidator.sendAttachmentRules",
    .messageReact: "messageValidator.sendReactionRules",
    .messageEdit: "messageValidator.editParamRules",
    .messageUnsend: "messageValidator.unsendParamRules",
    .messageEmbeddedMedia: "messageValidator.getEmbeddedMediaRules",
    .messageSendMultipart: "messageValidator.multipartRules",
    .messageSendAttachmentChunk: "messageValidator.attachmentChunkRules",
    .scheduleCreate: "scheduledMessageValidator.defaultRules",
    .scheduleUpdate: "scheduledMessageValidator.defaultRules",
    .backupCreateSettings: "settingsValidator.rules",
    .backupDeleteSettings: "settingsValidator.deleteRules",
    .backupCreateTheme: "themeValidator.rules",
    .backupDeleteTheme: "themeValidator.deleteRules",
    .webhookList: "webhookValidator.getWebhookRules",
    .webhookCreate: "webhookValidator.createRules",
  ]

  /// Fields we knowingly do not reproduce, and why.
  ///
  /// Keyed `<rule set>.<field>`. Each is a case where transcribing would refuse a request the
  /// reference ACCEPTS, or would reproduce a crash. Adding to this list is a decision; leaving
  /// a divergence off it is a failure.
  private static let knowinglyDivergent: [String: String] = [
    "webhookValidator.getWebhookRules.id":
      """
    `id: "number"` names a rule validatorjs does not have. An unregistered rule THROWS \
    (rules.js:missedRuleValidator), so the reference answers 500 Server Error for any \
    request that actually sends `id`, and passes it through untouched when it does not \
    (an absent value is never validatable). No working client sends it. Reproducing the \
    500 would be transcribing a crash.
    """
  ]

  // MARK: - Tests

  @Test("Every reference rule set a route uses is transcribed")
  func everyValidatedRouteIsCovered() throws {
    let fixture = try Self.fixture()

    // The rule sets actually reachable from a route, which is a smaller set than "every rule
    // set declared": a validator method with no route is dead upstream too.
    var reachable: Set<String> = []
    for route in fixture.routes {
      let stem = route.validator.prefix(1).lowercased() + route.validator.dropFirst()
      // `validateQuery` → `queryBodyRules` is not derivable, so reachability is established
      // by the validator FILE and checked against what we transcribed from it.
      reachable.formUnion(
        fixture.ruleSets.keys.filter { $0.hasPrefix("\(stem).") }
      )
    }

    let transcribedSets = Set(Self.transcribed.values)
    let missing = reachable.subtracting(transcribedSets).sorted()

    // Rule sets belonging to bespoke validator methods that take no rule object. Named, so
    // that a genuinely missed one still fails.
    let bespoke: Set<String> = []

    #expect(
      Set(missing).subtracting(bespoke).isEmpty,
      """
      These reference rule sets are reachable from a route and are transcribed nowhere. A \
      route with no rules accepts what the reference refuses:

      \(missing.joined(separator: "\n"))
      """
    )
  }

  @Test("Each transcribed rule set matches the reference field for field, in order")
  func fieldsAndOrderMatch() throws {
    let fixture = try Self.fixture()
    var problems: [String] = []

    for (handler, setName) in Self.transcribed.sorted(by: { $0.value < $1.value }) {
      guard let expected = fixture.ruleSets[setName] else {
        problems.append("\(setName): named by \(handler.rawValue) but not in the fixture")
        continue
      }
      guard let actual = ValidationRules.ruleSet(for: handler) else {
        problems.append("\(handler.rawValue): no rule set, expected \(setName)")
        continue
      }

      let expectedFields =
        expected
        .map(\.field)
        .filter { Self.knowinglyDivergent["\(setName).\($0)"] == nil }
      let actualFields = actual.fields.map(\.field)

      if expectedFields != actualFields {
        problems.append(
          """
          \(handler.rawValue) (\(setName)) fields differ:
             reference: \(expectedFields)
             ours:      \(actualFields)
          """)
      }
    }

    #expect(problems.isEmpty, "\(problems.joined(separator: "\n\n"))")
  }

  @Test("Each field's rules match the reference, in order")
  func rulesMatch() throws {
    let fixture = try Self.fixture()
    var problems: [String] = []

    for (handler, setName) in Self.transcribed.sorted(by: { $0.value < $1.value }) {
      guard let expected = fixture.ruleSets[setName],
        let actual = ValidationRules.ruleSet(for: handler)
      else { continue }

      for field in expected
      where Self.knowinglyDivergent["\(setName).\(field.field)"] == nil {
        guard let ours = actual.fields.first(where: { $0.field == field.field }) else { continue }
        let rendered = ours.rules.map(Self.render)
        if rendered != field.rules {
          problems.append(
            """
            \(handler.rawValue) (\(setName)) field `\(field.field)` rules differ:
               reference: \(field.rules)
               ours:      \(rendered)
            """)
        }
      }
    }

    #expect(problems.isEmpty, "\(problems.joined(separator: "\n\n"))")
  }

  @Test("The reaction list is the reference's, not a hand-copied one")
  func reactionsMatch() throws {
    // Twelve strings that are easy to get subtly wrong, and a wrong one refuses a tapback a
    // client is entitled to send.
    #expect(ValidationRules.reactions == (try Self.fixture()).reactions)
  }

  @Test("No handler carries rules the reference does not give it")
  func noInventedRules() throws {
    let fixture = try Self.fixture()
    var invented: [String] = []

    for handler in ValidationRules.table.keys {
      guard let setName = Self.transcribed[handler] else {
        invented.append("\(handler.rawValue): has rules but transcribes no reference rule set")
        continue
      }
      if fixture.ruleSets[setName] == nil {
        invented.append("\(handler.rawValue): names \(setName), which the reference does not have")
      }
    }

    #expect(
      invented.isEmpty,
      """
      Validation this server invented. Being stricter than the reference is the one way this \
      layer breaks a client:

      \(invented.joined(separator: "\n"))
      """
    )
  }

  @Test("Every divergence from the reference is declared with a reason")
  func divergencesAreDeclared() throws {
    let fixture = try Self.fixture()

    for (handler, setName) in Self.transcribed {
      guard let expected = fixture.ruleSets[setName],
        let actual = ValidationRules.ruleSet(for: handler)
      else { continue }

      let ours = Set(actual.fields.map(\.field))
      for field in expected.map(\.field) where !ours.contains(field) {
        let reason = Self.knowinglyDivergent["\(setName).\(field)"]
        #expect(
          reason != nil,
          """
          `\(setName).\(field)` is in the reference and not in our table, and is not on the \
          knowinglyDivergent list. Either transcribe it, or add it there with the reason it \
          cannot be transcribed.
          """
        )
        #expect(reason.map { $0.count > 40 } ?? false, "\(setName).\(field): reason too thin")
      }
    }
  }

  // MARK: - Rendering

  /// Our typed rule back into the reference's rule-string spelling, for comparison only.
  private static func render(_ rule: ValidationRule) -> String {
    switch rule {
    case .required: "required"
    case .present: "present"
    case .string: "string"
    case .numeric: "numeric"
    case .boolean: "boolean"
    case .array: "array"
    case .jsonObject: "json-object"
    case .inList(let values): "in:\(values.joined(separator: ","))"
    case .min(let bound): "min:\(bound == bound.rounded() ? String(Int64(bound)) : String(bound))"
    case .max(let bound): "max:\(bound == bound.rounded() ? String(Int64(bound)) : String(bound))"
    }
  }
}
