// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/Stickers.framework/Versions/A/Stickers
@interface _STKTextInputObjCStoreFacade : NSObject

- (bool)touchStickerWithIdentifier:(id)arg0 error:(id *)arg1;
- (id)init;
- (id)representationsForStickersWithIdentifiers:(id)arg0 roles:(id)arg1 error:(id *)arg2;
- (id)stickersWithIdentifiers:(id)arg0 roles:(id)arg1 error:(id *)arg2;

@end
