// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/Stickers.framework/Versions/A/Stickers
@interface _STKStickerEffect : NSObject

@property (nonatomic, readonly) NSString *description;

- (id)description;
- (id)init;

@end
