// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/ChatKit.framework/Versions/A/ChatKit
@interface CKAssociatedStickerChatItem : CKAssociatedMessageChatItem

@property (copy, nonatomic) IMSticker *sticker;
@property (nonatomic) long long stickerReactionIndex;
@property (readonly, copy, nonatomic) NSString *transferGUID;
@property (readonly, nonatomic) NSDictionary *attributionInfo;
@property (readonly, nonatomic) NSDictionary *stickerUserInfo;
@property (readonly, nonatomic) NSNumber *adamID;
@property (readonly, nonatomic) NSString *stickerPackGUID;
@property (readonly, nonatomic) NSString *stickerPackName;
@property (readonly, nonatomic) bool canShowInAppStore;
@property (readonly, nonatomic) bool isCustomSticker;
@property (readonly, nonatomic) bool isDeletable;
@property (readonly, nonatomic) bool isDraggable;
@property (readonly, nonatomic) bool isReaction;
@property (retain, nonatomic) CKMediaObject *mediaObject;

+ (bool)isDroppedSticker:(id)arg0;
+ (bool)userHasDraggedSticker;
+ (double)computeHorizontalStickerFrameOffset:(CGRect)arg0 parentSize:(CGSize)arg1 forPositioningWithinContentAlignmentRect:(CGRect)arg2 geometryDescriptor:(IMAssociatedMessageGeometryDescriptor)arg3 forTranscriptOrientation:(char)arg4;
+ (id)_droppedStickers;
+ (id)_showingStickers;
+ (void)addDroppedSticker:(id)arg0;
+ (void)clearTranscriptDisplayCaches;
+ (void)removeDroppedSticker:(id)arg0;
+ (void)setUserHasDraggedSticker:(bool)arg0;

- (CGSize)loadSizeThatFits:(CGSize)arg0 textAlignmentInsets:(UIEdgeInsets *)arg1;
- (Class)cellClass;
- (bool)canShowInAppStore;
- (bool)chatItemIsStickerReposition;
- (bool)currentStickerRepositionIsLocalReposition;
- (bool)isCustomSticker;
- (bool)isDeletable;
- (bool)isDraggable;
- (bool)isReaction;
- (bool)isSticker;
- (bool)supportsCommunicationSafety;
- (char)transcriptOrientation;
- (id)IMAssociatedStickerChatItem;
- (id)adamID;
- (id)attributionImage;
- (id)attributionImageTintColor;
- (id)attributionInfo;
- (id)commSafetyTransferGUID;
- (id)initWithIMChatItem:(id)arg0 maxWidth:(double)arg1;
- (id)insertionHandler;
- (id)mediaObject;
- (id)messageSummaryInfoValueForKey:(id)arg0;
- (id)sticker;
- (id)stickerPackGUID;
- (id)stickerPackName;
- (id)stickerUserInfo;
- (id)transferGUID;
- (long long)stickerReactionIndex;
- (void)clearStickerRepositionLocalState;
- (void)refreshMediaObjectForStickerRepositioning;
- (void)setMediaObject:(id)arg0;
- (void)setSticker:(id)arg0;
- (void)setStickerReactionIndex:(long long)arg0;

@end
