// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/FindMyLocateObjCWrapper.framework/Versions/A/FindMyLocateObjCWrapper
@interface FindMyLocateSession : NSObject

@property (copy) id /* block */ friendshipUpdateCallback;
@property (copy) id /* block */ locationUpdateCallback;
@property (copy) id /* block */ meDeviceUpdateCallback;
@property (retain, nonatomic) _TtC23FindMyLocateObjCWrapper13ObjCBootstrap *trampoline;

+ (bool)FMFRestricted;

- (id /* block */)friendshipUpdateCallback;
- (id /* block */)locationUpdateCallback;
- (id /* block */)meDeviceUpdateCallback;
- (id)cachedFriendsFollowingMyLocation;
- (id)cachedFriendsSharingLocationsWithMe;
- (id)cachedLocationForHandle:(id)arg0 includeAddress:(bool)arg1;
- (id)cachedLocationForHandle:(id)arg0;
- (id)cachedOfferExpirationForHandle:(id)arg0 groupId:(id)arg1;
- (id)init;
- (id)trampoline;
- (long long)cachedCanShareLocationWithHandle:(id)arg0 isFromGroup:(bool)arg1;
- (void)canShareLocationWithHandle:(id)arg0 isFromGroup:(bool)arg1 completion:(id /* block */)arg2;
- (void)friendshipStateWithHandle:(id)arg0 isFromGroup:(bool)arg1 completion:(id /* block */)arg2;
- (void)getActiveLocationSharingDeviceWithCompletion:(id /* block */)arg0;
- (void)getFriendsFollowingMyLocationWithCompletion:(id /* block */)arg0;
- (void)getFriendsSharingLocationsWithMeWithCompletion:(id /* block */)arg0;
- (void)getOfferExpirationForHandle:(id)arg0 groupId:(id)arg1 completion:(id /* block */)arg2;
- (void)sendFriendshipInviteToHandle:(id)arg0 from:(id)arg1 isFromGroup:(bool)arg2 completion:(id /* block */)arg3;
- (void)sendFriendshipInviteToHandle:(id)arg0 isFromGroup:(bool)arg1 completion:(id /* block */)arg2;
- (void)sendFriendshipOfferToHandles:(id)arg0 expiration:(long long)arg1 isFromGroup:(bool)arg2 completion:(id /* block */)arg3;
- (void)sendFriendshipOfferToHandles:(id)arg0 from:(id)arg1 expiration:(long long)arg2 isFromGroup:(bool)arg3 completion:(id /* block */)arg4;
- (void)setActiveLocationSharingDevice:(id)arg0 completion:(id /* block */)arg1;
- (void)setFriendshipUpdateCallback:(id /* block */)arg0;
- (void)setLocationUpdateCallback:(id /* block */)arg0;
- (void)setMeDeviceUpdateCallback:(id /* block */)arg0;
- (void)setTrampoline:(id)arg0;
- (void)startMonitoringActiveLocationSharingDeviceChangeWithCompletion:(id /* block */)arg0;
- (void)startRefreshingLocationForHandles:(id)arg0 priority:(long long)arg1 isFromGroup:(bool)arg2 completion:(id /* block */)arg3;
- (void)startRefreshingLocationForHandles:(id)arg0 priority:(long long)arg1 isFromGroup:(bool)arg2 reverseGeocode:(bool)arg3 completion:(id /* block */)arg4;
- (void)startUpdatingFriendsWithInitialUpdates:(bool)arg0 completion:(id /* block */)arg1;
- (void)stopRefreshingLocationForHandles:(id)arg0 priority:(long long)arg1 isFromGroup:(bool)arg2 completion:(id /* block */)arg3;
- (void)stopRefreshingLocationWithCompletion:(id /* block */)arg0;
- (void)stopSharingLocationWith:(id)arg0 from:(id)arg1 isFromGroup:(bool)arg2 completion:(id /* block */)arg3;
- (void)stopSharingLocationWith:(id)arg0 isFromGroup:(bool)arg1 completion:(id /* block */)arg2;
- (void)stopUpdatingFriendsWithCompletion:(id /* block */)arg0;

@end
