// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/FMF.framework/Versions/A/FMF
@interface FMFDevice : NSObject <NSCopying, NSSecureCoding>

@property (assign) bool isActiveDevice;
@property (assign) bool isAutoMeCapable;
@property (assign) bool isCompanionDevice;
@property (assign) bool isThisDevice;
@property (copy) NSString *deviceId;
@property (copy) NSString *deviceName;
@property (copy) NSString *idsDeviceId;

+ (bool)supportsSecureCoding;
+ (id)deviceWithId:(id)arg0 name:(id)arg1 idsDeviceId:(id)arg2 isActive:(bool)arg3 isThisDevice:(bool)arg4 isCompanionDevice:(bool)arg5 isAutoMeCapable:(bool)arg6;

- (bool)isActiveDevice;
- (bool)isAutoMeCapable;
- (bool)isCompanionDevice;
- (bool)isEqual:(id)arg0;
- (bool)isThisDevice;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)debugDescription;
- (id)description;
- (id)deviceId;
- (id)deviceName;
- (id)idsDeviceId;
- (id)initWithCoder:(id)arg0;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg0;
- (void)setDeviceId:(id)arg0;
- (void)setDeviceName:(id)arg0;
- (void)setIdsDeviceId:(id)arg0;
- (void)setIsActiveDevice:(bool)arg0;
- (void)setIsAutoMeCapable:(bool)arg0;
- (void)setIsCompanionDevice:(bool)arg0;
- (void)setIsThisDevice:(bool)arg0;
- (void)updateIsActive:(bool)arg0 isThisDevice:(bool)arg1;

@end
