// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/FMF.framework/Versions/A/FMF
@interface FMFPlacemark : NSObject <NSCopying, NSSecureCoding>

@property (retain, nonatomic) NSArray *formattedAddressLines;
@property (retain, nonatomic) NSString *administrativeArea;
@property (retain, nonatomic) NSString *country;
@property (retain, nonatomic) NSString *locality;
@property (retain, nonatomic) NSString *state;
@property (retain, nonatomic) NSString *streetAddress;
@property (retain, nonatomic) NSString *streetName;

+ (bool)supportsSecureCoding;

- (bool)isEqual:(id)arg0;
- (id)administrativeArea;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)country;
- (id)dictionaryValue;
- (id)formattedAddress;
- (id)formattedAddressLines;
- (id)initWithCoder:(id)arg0;
- (id)initWithDictionary:(id)arg0;
- (id)initWithLocality:(id)arg0 administrativeArea:(id)arg1 country:(id)arg2 state:(id)arg3 streetAddress:(id)arg4 streetName:(id)arg5;
- (id)locality;
- (id)state;
- (id)streetAddress;
- (id)streetName;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg0;
- (void)setAdministrativeArea:(id)arg0;
- (void)setCountry:(id)arg0;
- (void)setFormattedAddressLines:(id)arg0;
- (void)setLocality:(id)arg0;
- (void)setState:(id)arg0;
- (void)setStreetAddress:(id)arg0;
- (void)setStreetName:(id)arg0;

@end
