// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/FMF.framework/Versions/A/FMF
@interface FMFSessionDataManager : NSObject

@property (retain, nonatomic) NSMutableDictionary *locationsCache;
@property (retain, nonatomic) NSSet *fences;
@property (retain, nonatomic) NSSet *followers;
@property (retain, nonatomic) NSSet *following;
@property (retain, nonatomic) NSSet *locations;

+ (id)sharedInstance;

- (id)favoritesOrdered;
- (id)fences;
- (id)followerForHandle:(id)arg0;
- (id)followers;
- (id)following;
- (id)followingForHandle:(id)arg0;
- (id)locationForHandle:(id)arg0;
- (id)locations;
- (id)locationsCache;
- (id)offerExpirationForHandle:(id)arg0 groupId:(id)arg1;
- (void)abDidChange;
- (void)abPreferencesDidChange;
- (void)setFences:(id)arg0;
- (void)setFollowers:(id)arg0;
- (void)setFollowing:(id)arg0;
- (void)setLocations:(id)arg0;
- (void)setLocationsCache:(id)arg0;

@end
