// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/FindMyLocateObjCWrapper.framework/Versions/A/FindMyLocateObjCWrapper
@interface FMLLocation : NSObject

@property (assign) double altitude;
@property (assign) double horizontalAccuracy;
@property (assign) double latitude;
@property (assign) double longitude;
@property (assign) double speed;
@property (assign) double timestamp;
@property (assign) double verticalAccuracy;
@property (assign) int floorLevel;
@property (assign) long long locationType;
@property (copy) NSArray *labels;
@property (copy) NSString *coarseAddressLabel;
@property (readonly) long long type;
@property (retain) FMLPlaceMark *address;

- (double)altitude;
- (double)horizontalAccuracy;
- (double)latitude;
- (double)longitude;
- (double)speed;
- (double)timestamp;
- (double)verticalAccuracy;
- (id)address;
- (id)coarseAddressLabel;
- (id)debugDescription;
- (id)description;
- (id)initWithAddress:(id)arg0 altitude:(double)arg1 longitude:(double)arg2 speed:(double)arg3 floorLevel:(int)arg4 horizontalAccuracy:(double)arg5 labels:(id)arg6 latitude:(double)arg7 timestamp:(double)arg8 verticalAccuracy:(double)arg9 locationType:(long long)arg10 coarseAddressLabel:(id)arg11;
- (id)labels;
- (id)locationTypeDescription;
- (int)floorLevel;
- (long long)locationType;
- (long long)type;
- (void)setAddress:(id)arg0;
- (void)setAltitude:(double)arg0;
- (void)setCoarseAddressLabel:(id)arg0;
- (void)setFloorLevel:(int)arg0;
- (void)setHorizontalAccuracy:(double)arg0;
- (void)setLabels:(id)arg0;
- (void)setLatitude:(double)arg0;
- (void)setLocationType:(long long)arg0;
- (void)setLongitude:(double)arg0;
- (void)setSpeed:(double)arg0;
- (void)setTimestamp:(double)arg0;
- (void)setVerticalAccuracy:(double)arg0;

@end
