// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/FindMyLocateObjCWrapper.framework/Versions/A/FindMyLocateObjCWrapper
@interface FMLPlaceMark : NSObject

@property (copy) NSArray *formattedAddressLines;
@property (copy) NSString *administrativeArea;
@property (copy) NSString *country;
@property (copy) NSString *locality;
@property (copy) NSString *stateCode;
@property (copy) NSString *streetAddress;
@property (copy) NSString *streetName;

- (bool)isEqual:(id)arg0;
- (id)administrativeArea;
- (id)comparisonIdentifier;
- (id)country;
- (id)debugDescription;
- (id)description;
- (id)formattedAddressLines;
- (id)initWithLocality:(id)arg0 administrativeArea:(id)arg1 country:(id)arg2 stateCode:(id)arg3 streetAddress:(id)arg4 streetName:(id)arg5 formattedAddressLines:(id)arg6;
- (id)locality;
- (id)stateCode;
- (id)streetAddress;
- (id)streetName;
- (unsigned long long)hash;
- (void)setAdministrativeArea:(id)arg0;
- (void)setCountry:(id)arg0;
- (void)setFormattedAddressLines:(id)arg0;
- (void)setLocality:(id)arg0;
- (void)setStateCode:(id)arg0;
- (void)setStreetAddress:(id)arg0;
- (void)setStreetName:(id)arg0;

@end
