// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMAccountController : NSObject

@property (copy) NSArray *accounts;
@property (nonatomic) bool networkDataAvailable;
@property (readonly, nonatomic) IMAccount *activeIMessageAccount;
@property (readonly, nonatomic) IMAccount *activeSMSAccount;
@property (readonly, nonatomic) NSArray *activeAccounts;
@property (readonly, nonatomic) NSArray *connectedAccounts;
@property (readonly, nonatomic) NSArray *operationalAccounts;
@property (readonly, nonatomic) id bestAccountForStatus;
@property (readonly, nonatomic) int numberOfAccounts;
@property (retain) NSMutableDictionary *accountMap;

+ (id)bestAccountFromAccounts:(id)arg0;
+ (id)sharedInstance;

- (bool)_deactivateAccount:(id)arg0;
- (bool)_deactivateAccounts:(id)arg0;
- (bool)_shouldPerformDeferredSetup;
- (bool)accountActive:(id)arg0;
- (bool)accountConnected:(id)arg0;
- (bool)accountConnecting:(id)arg0;
- (bool)accountLogoutable:(id)arg0;
- (bool)activateAccount:(id)arg0 force:(bool)arg1 locally:(bool)arg2;
- (bool)activateAccount:(id)arg0 force:(bool)arg1;
- (bool)activateAccount:(id)arg0 locally:(bool)arg1;
- (bool)activateAccount:(id)arg0;
- (bool)activateAccounts:(id)arg0 force:(bool)arg1 locally:(bool)arg2;
- (bool)activateAccounts:(id)arg0;
- (bool)activateAndHandleReconnectAccount:(id)arg0;
- (bool)activateAndHandleReconnectAccounts:(id)arg0;
- (bool)addAccount:(id)arg0 atIndex:(int)arg1 locally:(bool)arg2;
- (bool)addAccount:(id)arg0 atIndex:(int)arg1;
- (bool)addAccount:(id)arg0 locally:(bool)arg1;
- (bool)addAccount:(id)arg0;
- (bool)canActivateAccount:(id)arg0;
- (bool)canActivateAccounts:(id)arg0;
- (bool)canDeleteAccount:(id)arg0;
- (bool)deactivateAccount:(id)arg0 withDisable:(bool)arg1;
- (bool)deactivateAccount:(id)arg0;
- (bool)deactivateAccounts:(id)arg0 withDisable:(bool)arg1;
- (bool)deactivateAccounts:(id)arg0;
- (bool)deleteAccount:(id)arg0 locally:(bool)arg1;
- (bool)deleteAccount:(id)arg0;
- (bool)isAccountKeyCDPSyncingOrWaitingForUser:(id)arg0;
- (bool)metionedHandleMatchesMeCard:(id)arg0;
- (bool)networkDataAvailable;
- (bool)readOnly;
- (bool)receiverIsMyMention:(id)arg0;
- (id)__iCloudSystemAccountForService:(id)arg0;
- (id)_bestAccountForAddresses:(id)arg0;
- (id)_bestOperationalAccountForSendingForService:(id)arg0;
- (id)accountAtIndex:(int)arg0;
- (id)accountForUniqueID:(id)arg0;
- (id)accountMap;
- (id)accounts;
- (id)accountsForService:(id)arg0;
- (id)accountsWithCapability:(unsigned long long)arg0;
- (id)activeAccounts;
- (id)activeAccountsForService:(id)arg0;
- (id)activeIMessageAccount;
- (id)activeSMSAccount;
- (id)aimAccount;
- (id)bestAccountForService:(id)arg0 login:(id)arg1 guid:(id)arg2;
- (id)bestAccountForService:(id)arg0 withLogin:(id)arg1;
- (id)bestAccountForService:(id)arg0;
- (id)bestAccountForStatus;
- (id)bestAccountWithCapability:(unsigned long long)arg0;
- (id)bestActiveAccountForService:(id)arg0 withLogin:(id)arg1;
- (id)bestActiveAccountForService:(id)arg0;
- (id)bestConnectedAccountForService:(id)arg0 withLogin:(id)arg1;
- (id)bestConnectedAccountForService:(id)arg0;
- (id)bestOperationalAccountForService:(id)arg0 withLogin:(id)arg1;
- (id)bestOperationalAccountForService:(id)arg0;
- (id)connectedAccounts;
- (id)connectedAccountsForService:(id)arg0;
- (id)connectedAccountsWithCapability:(unsigned long long)arg0;
- (id)iMessageAccountForLastAddressedHandle:(id)arg0 simID:(id)arg1;
- (id)init;
- (id)jabberAccount;
- (id)mostLoggedInAccount;
- (id)operationalAccounts;
- (id)operationalAccountsForService:(id)arg0;
- (id)operationalAccountsWithCapability:(unsigned long long)arg0;
- (id)senderIdentifiers;
- (int)numberOfAccounts;
- (long long)activeAccountsAreEligibleForAppleSMSFilter;
- (long long)activeAccountsAreEligibleForAppleSMSFilterSubClassification;
- (long long)activeAccountsAreEligibleForDefaultAppleSMSFilter;
- (long long)activeAccountsAreEligibleForHawking;
- (long long)activeAccountsAreEligibleForInternationalFiltering;
- (long long)activeAccountsAreEligibleForUnknownSendersFiltering;
- (long long)activeAccountsAreEligibleForiMessageJunk;
- (void)_accountRegistrationStatusChanged:(id)arg0;
- (void)_activeAccountChanged:(id)arg0;
- (void)_disableCache;
- (void)_enableCache;
- (void)_rebuildOperationalAccountsCache:(bool)arg0;
- (void)_requestNetworkDataAvailability;
- (void)accountLoginComplete:(id)arg0;
- (void)autoLogin;
- (void)dealloc;
- (void)deferredSetup;
- (void)setAccountMap:(id)arg0;
- (void)setAccounts:(id)arg0;
- (void)setNetworkDataAvailable:(bool)arg0;
- (void)setReadOnly:(bool)arg0;

@end
