// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMAggregateAttachmentMessagePartChatItem : IMAttachmentMessagePartChatItem

@property (copy, nonatomic) NSArray *aggregateAttachmentParts;
@property (readonly, copy, nonatomic) NSArray *transferGUIDs;

- (Class)__ck_chatItemClass;
- (bool)isAttachmentContiguousWithChatItem:(id)arg0;
- (id)_initWithItem:(id)arg0 text:(id)arg1 index:(long long)arg2 messagePartRange:(_NSRange)arg3 transferGUIDs:(id)arg4 chatContext:(id)arg5 visibleAssociatedMessageChatItems:(id)arg6;
- (id)_initWithItem:(id)arg0 text:(id)arg1 index:(long long)arg2 messagePartRange:(_NSRange)arg3 transferGUIDs:(id)arg4 chatContext:(id)arg5;
- (id)aggregateAttachmentParts;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)description;
- (id)replyContextPreviewChatItemForReply:(id)arg0 chatContext:(id)arg1;
- (id)transferGUIDs;
- (void)setAggregateAttachmentParts:(id)arg0;

@end
