// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

@protocol IMDaemonProtocol

// required
- (void)setListenerCapabilities:(id)arg0;
- (void)setVCCapabilities:(id)arg0;

@end
