// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMSharedUtilities.framework/Versions/A/IMSharedUtilities
@interface IMEmojiSticker : IMSticker

@property (readonly, copy, nonatomic) NSString *emojiString;

+ (id)defaultEmojiStickerPackID;
+ (id)stickerPackID;
+ (id)tempFileURLForStickerID:(id)arg0;

- (bool)isEmojiSticker;
- (bool)isEqual:(id)arg0;
- (bool)prepareToSend;
- (bool)writeGeneratedImageToFileURL:(id)arg0 error:(id *)arg1;
- (bool)writeGeneratedImageToFileURL:(id)arg0 fontSize:(double)arg1 imageGenerationScale:(double)arg2 error:(id *)arg3;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)description;
- (id)emojiString;
- (id)generateImage;
- (id)generateImageForFontSize:(double)arg0 imageGenerationScale:(double)arg1;
- (id)image;
- (id)initWithEmojiString:(id)arg0 stickerID:(id)arg1 stickerPackID:(id)arg2 fileURL:(id)arg3 accessibilityLabel:(id)arg4 moodCategory:(id)arg5 stickerName:(id)arg6 textToSpeechName:(id)arg7;
- (id)initWithEmojiString:(id)arg0 stickerPackID:(id)arg1 fileURL:(id)arg2 moodCategory:(id)arg3;
- (id)initWithEmojiString:(id)arg0 stickerPackID:(id)arg1 fileURL:(id)arg2;
- (id)initWithEmojiString:(id)arg0 stickerPackID:(id)arg1;
- (id)stickerView;

@end
