// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMFindMyLocation : NSObject

@property (readonly, nonatomic) FMFLocation *fmfLocation;
@property (readonly, nonatomic) FMLLocation *fmlLocation;
@property (readonly, nonatomic) NSString *shortAddress;

+ (id)locationWithFMFLocation:(id)arg0 fmlLocation:(id)arg1;
+ (id)locationWithFMFLocation:(id)arg0;
+ (id)locationWithFMLLocation:(id)arg0;

- (bool)isEqual:(id)arg0;
- (id)fmfLocation;
- (id)fmlLocation;
- (id)initWithFMFLocation:(id)arg0 fmlLocation:(id)arg1;
- (id)shortAddress;
- (unsigned long long)hash;

@end
