// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMFMFSession : NSObject <FMFSessionDelegate>

@property (nonatomic) unsigned long long fmfProvisionedState;
@property (readonly) Class superclass;
@property (readonly) unsigned long long hash;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic) bool disableLocationSharing;
@property (readonly, nonatomic) bool restrictLocationSharing;
@property (retain, nonatomic) FMFSession *session;
@property (retain, nonatomic) IMFindMyDevice *activeDevice;
@property (retain, nonatomic) NSString *establishingAccountID;
@property (retain, nonatomic) id fmlSession;

+ (id)sharedInstance;

- (Class)__FMFSessionClass;
- (Class)__FMLSessionClass;
- (bool)_canShareLocationWithFMLHandle:(id)arg0 isFromGroup:(bool)arg1;
- (bool)allChatParticipantsFollowingMyLocation:(id)arg0;
- (bool)allChatParticipantsSharingLocationWithMe:(id)arg0;
- (bool)chatHasParticipantsFollowingMyLocation:(id)arg0;
- (bool)chatHasParticipantsSharingLocationWithMe:(id)arg0;
- (bool)chatHasSiblingParticipantsSharingLocationWithMe:(id)arg0;
- (bool)disableLocationSharing;
- (bool)findMyHandleIsFollowingMyLocation:(id)arg0;
- (bool)findMyHandleIsSharingLocationWithMe:(id)arg0;
- (bool)handleIsFollowingMyLocation:(id)arg0;
- (bool)handleIsSharingLocationWithMe:(id)arg0;
- (bool)imIsProvisionedForLocationSharing;
- (bool)restrictLocationSharing;
- (id)_accountStore;
- (id)_bestAccountForAddresses:(id)arg0;
- (id)_callerIDForChat:(id)arg0;
- (id)_dateFromShareDuration:(long long)arg0;
- (id)activeDevice;
- (id)allSiblingFindMyHandlesForChat:(id)arg0;
- (id)establishingAccountID;
- (id)findMyHandlesForChat:(id)arg0;
- (id)findMyHandlesSharingLocationWithMe;
- (id)findMyLocationForFindMyHandle:(id)arg0;
- (id)findMyLocationForHandle:(id)arg0;
- (id)findMyLocationForHandleOrSibling:(id)arg0;
- (id)findMyURLForChat:(id)arg0;
- (id)fmfGroupIdGroup;
- (id)fmfGroupIdOneToOne;
- (id)fmlSession;
- (id)init;
- (id)session;
- (id)timedOfferExpirationForChat:(id)arg0;
- (unsigned long long)fmfProvisionedState;
- (void)_accountStoreDidChangeNotification:(id)arg0;
- (void)_configureFindMyLocateSession;
- (void)_initializeFindMySessionIfInAllowedProcess;
- (void)_postNotification:(id)arg0 object:(id)arg1 userInfo:(id)arg2;
- (void)_postRelationshipStatusDidChangeNotificationWithIMFindMyHandle:(id)arg0;
- (void)_setUpFindMyLocateSessionCallbacks;
- (void)_startFMLSessionMonitoring;
- (void)_startRefreshingLocationForFMLHandles:(id)arg0 priority:(long long)arg1 isFromGroup:(bool)arg2;
- (void)_startSharingWithFMFHandles:(id)arg0 inChat:(id)arg1 untilDate:(id)arg2;
- (void)_startSharingWithFMLHandles:(id)arg0 inChat:(id)arg1 withDuration:(long long)arg2;
- (void)_stopSharingWithFMFHandles:(id)arg0 inChat:(id)arg1;
- (void)_stopSharingWithFMLHandles:(id)arg0 inChat:(id)arg1;
- (void)_stopTrackingLocationForFMLHandles:(id)arg0 priority:(long long)arg1 isFromGroup:(bool)arg2;
- (void)_updateActiveDevice;
- (void)dealloc;
- (void)didChangeActiveLocationSharingDevice:(id)arg0;
- (void)didReceiveLocation:(id)arg0;
- (void)didReceiveLocationForHandle:(id)arg0;
- (void)didStartAbilityToGetLocationForHandle:(id)arg0;
- (void)didStartSharingMyLocationWithHandle:(id)arg0;
- (void)didStopAbilityToGetLocationForHandle:(id)arg0;
- (void)didStopSharingMyLocationWithHandle:(id)arg0;
- (void)didUpdateHidingStatus:(bool)arg0;
- (void)friendshipRequestReceived:(id)arg0;
- (void)friendshipWasRemoved:(id)arg0;
- (void)makeThisDeviceActiveDevice;
- (void)refreshLocationForChat:(id)arg0;
- (void)refreshLocationForHandle:(id)arg0 inChat:(id)arg1;
- (void)sendMappingPacket:(id)arg0 toHandle:(id)arg1;
- (void)setActiveDevice:(id)arg0;
- (void)setEstablishingAccountID:(id)arg0;
- (void)setFmfProvisionedState:(unsigned long long)arg0;
- (void)setFmlSession:(id)arg0;
- (void)setSession:(id)arg0;
- (void)startSharingWithChat:(id)arg0 withDuration:(long long)arg1;
- (void)startSharingWithHandle:(id)arg0 inChat:(id)arg1 withDuration:(long long)arg2;
- (void)startTrackingLocationForChat:(id)arg0;
- (void)startTrackingLocationForHandle:(id)arg0;
- (void)stopSharingWithChat:(id)arg0;
- (void)stopSharingWithHandle:(id)arg0 inChat:(id)arg1;
- (void)stopTrackingLocationForChat:(id)arg0;
- (void)stopTrackingLocationForHandle:(id)arg0;

@end
