// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMMessagePartChatItem : IMMessageChatItem <IMVisibleAssociatedMessageHost>

@property (nonatomic) _NSRange messagePartRange;
@property (nonatomic) bool allowlistedRichLinkSender;
@property (nonatomic) bool chatInScrutinyMode;
@property (nonatomic) bool isBusiness;
@property (nonatomic) long long index;
@property (nonatomic) unsigned long long replyCount;
@property (readonly) Class superclass;
@property (readonly) unsigned long long hash;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, copy, nonatomic) IMMessagePartHighlightChatItem *messageHighlightChatItem;
@property (readonly, copy, nonatomic) NSAttributedString *fallbackCorruptText;
@property (readonly, copy, nonatomic) NSAttributedString *text;
@property (readonly, copy, nonatomic) NSString *threadIdentifier;
@property (readonly, copy, nonatomic) NSString *threadIdentifierForTapback;
@property (readonly, nonatomic) IMMessageItem *threadOriginator;
@property (readonly, nonatomic) _NSRange originalMessagePartRange;
@property (readonly, nonatomic) bool hasSubject;
@property (readonly, nonatomic) bool isCorrupt;
@property (readonly, nonatomic) bool isEditedMessagePart;
@property (readonly, nonatomic) bool isFailedEditMessagePart;
@property (readonly, nonatomic) bool isFailedRetractMessagePart;
@property (readonly, nonatomic) bool isRetractedMessagePart;
@property (readonly, nonatomic) bool requiresFaceTimeAttribution;
@property (readonly, nonatomic) bool requiresSiriAttribution;
@property (readonly, nonatomic) long long syndicationBehavior;
@property (readonly, nonatomic) long long syndicationStatus;
@property (readonly, nonatomic) long long syndicationType;
@property (retain, nonatomic) NSArray *visibleAssociatedMessageChatItems;

+ (bool)_isAllowlistedRichLinkSender:(id)arg0 isBusiness:(bool)arg1;
+ (bool)_isAllowlistedURL:(id)arg0;
+ (bool)_isPathExceptionToAllowlistedURL:(id)arg0;
+ (bool)_shouldAggregateForTransferType:(id)arg0;
+ (bool)_supportsRichLinkURL:(id)arg0 forSender:(id)arg1 isAllowlistedRichLinkSender:(bool)arg2;
+ (bool)isSiriEnabled;
+ (id)_additionalSupportedRichLinkSchemesForAllowlistedSender:(id)arg0;
+ (id)_defaultRichLinkAllowListExceptions;
+ (id)_defaultRichLinkAllowlist;
+ (id)_guidForMessage:(id)arg0 url:(id)arg1;
+ (id)_messageItemWithPartsDeleted:(id)arg0 fromMessageItem:(id)arg1 indexesOfItemsDeleted:(id *)arg2 indexToRangeMapping:(id *)arg3;
+ (id)_newAudioMessagePartsForMessageItem:(id)arg0 text:(id)arg1 chatContext:(id)arg2 retractedPartIndexes:(id)arg3 singlePart:(id)arg4;
+ (id)_newDetonatedMessagePartsForMessageItem:(id)arg0 chatContext:(id)arg1 photosPluginPayload:(id)arg2;
+ (id)_newMessagePartsForMessageItem:(id)arg0 chatContext:(id)arg1 photosPluginPayload:(id)arg2;
+ (id)_newMessagePartsForMessageItem:(id)arg0 chatContext:(id)arg1;
+ (id)_newMessagePartsForMessageItem:(id)arg0;
+ (id)_retractedMessagePartsForMessage:(id)arg0 parts:(id)arg1 retractedPartIndexes:(id)arg2;
+ (id)_richLinkRangesForMessageText:(id)arg0 sender:(id)arg1 isAllowlistedRichLinkSender:(bool)arg2;
+ (id)aggregatePartsForParts:(id)arg0 forMessage:(id)arg1 context:(id)arg2;
+ (id)chatItemGUIDForMessageGUID:(id)arg0 partIndex:(long long)arg1;
+ (id)messageBodyStringForAttachmentGUIDs:(id)arg0;
+ (id)messageBodyStringForCMMMessage:(id)arg0;
+ (long long)_attachmentStackAggregationThreshold;

- (_NSRange)messagePartRange;
- (_NSRange)originalMessagePartRange;
- (bool)canDelete;
- (bool)canRetract;
- (bool)canSendMessageAcknowledgment;
- (bool)chatInScrutinyMode;
- (bool)hasSubject;
- (bool)isAllowlistedRichLinkSender;
- (bool)isBusiness;
- (bool)isCorrupt;
- (bool)isEditedMessagePart;
- (bool)isFailedEditMessagePart;
- (bool)isFailedRetractMessagePart;
- (bool)isHighlighted;
- (bool)isRetractedMessagePart;
- (bool)requiresFaceTimeAttribution;
- (bool)requiresSiriAttribution;
- (id)_initWithItem:(id)arg0 index:(long long)arg1 messagePartRange:(_NSRange)arg2 syndicationBehavior:(long long)arg3;
- (id)_initWithItem:(id)arg0 index:(long long)arg1 messagePartRange:(_NSRange)arg2;
- (id)_initWithItem:(id)arg0 text:(id)arg1 index:(long long)arg2 messagePartRange:(_NSRange)arg3 visibleAssociatedMessageChatItems:(id)arg4;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)description;
- (id)fallbackCorruptText;
- (id)messageHighlightChatItem;
- (id)messageSummaryInfo;
- (id)replyContextPreviewChatItemForReply:(id)arg0 chatContext:(id)arg1;
- (id)text;
- (id)threadIdentifier;
- (id)threadIdentifierForTapback;
- (id)threadOriginator;
- (id)transcriptText;
- (id)visibleAssociatedMessageChatItems;
- (long long)index;
- (long long)messagePartAttributeName;
- (long long)syndicationBehavior;
- (long long)syndicationStatus;
- (long long)syndicationType;
- (unsigned char)contentType;
- (unsigned long long)replyCount;
- (void)_setIndex:(long long)arg0;
- (void)_setVisibleAssociatedMessageChatItems:(id)arg0;
- (void)setAllowlistedRichLinkSender:(bool)arg0;
- (void)setChatInScrutinyMode:(bool)arg0;
- (void)setIsBusiness:(bool)arg0;
- (void)setMessagePartRange:(_NSRange)arg0;
- (void)setReplyCount:(unsigned long long)arg0;

@end
