// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMMessageAcknowledgmentChatItem : IMAssociatedMessageChatItem

- (Class)__ck_chatItemClass;
- (id)_initWithItem:(id)arg0 sender:(id)arg1 tapback:(id)arg2;
- (id)copyWithZone:(_NSZone *)arg0;

@end
