// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMNicknameController : NSObject

@property (nonatomic) bool isInitialLoad;
@property (retain, nonatomic) IMNickname *personalNickname;
@property (retain, nonatomic) NSDictionary *activeRecords;
@property (retain, nonatomic) NSDictionary *archivedNicknames;
@property (retain, nonatomic) NSDictionary *handledNicknames;
@property (retain, nonatomic) NSDictionary *ignoredRecords;
@property (retain, nonatomic) NSDictionary *pendingNicknameUpdates;
@property (retain, nonatomic) NSMutableDictionary *responseHandlers;
@property (retain, nonatomic) NSMutableSet *scrutinyNicknameHandles;
@property (retain, nonatomic) NSSet *allowListedHandlesForSharing;
@property (retain, nonatomic) NSSet *denyListedHandlesForSharing;
@property (retain, nonatomic) NSSet *transitionedHandles;

+ (bool)accountsMatchUpToUseNicknames;
+ (bool)multiplePhoneNumbersTiedToAppleID;
+ (id)sharedInstance;

- (bool)_canUpdatePersonalNickname;
- (bool)_nicknameFeatureEnabled;
- (bool)handleIsAllowedForSharing:(id)arg0;
- (bool)handleIsDeniedForSharing:(id)arg0;
- (bool)hasObservedTransitionForHandleID:(id)arg0;
- (bool)iCloudSignedInToUseNicknames;
- (bool)isActiveForNickname:(id)arg0;
- (bool)isIgnoredForNickname:(id)arg0;
- (bool)isInitialLoad;
- (bool)isInitialLoadComplete;
- (bool)shouldOfferNicknameSharingForChat:(id)arg0;
- (bool)shouldOfferNicknameSharingForHandles:(id)arg0;
- (id)IMSharedHelperMD5Helper:(id)arg0;
- (id)_handleIDsForHandle:(id)arg0;
- (id)activeRecords;
- (id)allowListedHandlesForSharing;
- (id)archivedNicknameForHandleIDs:(id)arg0;
- (id)archivedNicknames;
- (id)contactStore;
- (id)createSharedProfileStateOracleForHandles:(id)arg0;
- (id)currentNicknameForHandleIDs:(id)arg0;
- (id)daemonController;
- (id)denyListedHandlesForSharing;
- (id)getNicknameHandlesUnderScrutiny;
- (id)handledNicknames;
- (id)handlesForNicknamesUnderScrutiny;
- (id)ignoredRecords;
- (id)imageDataForHandle:(id)arg0;
- (id)init;
- (id)meCardSharingState;
- (id)nicknameForHandle:(id)arg0;
- (id)nicknameForHandleIDs:(id)arg0;
- (id)pendingNicknameForHandleIDs:(id)arg0;
- (id)pendingNicknameUpdates;
- (id)personNameComponentsForHandle:(id)arg0;
- (id)personalNickname;
- (id)responseHandlers;
- (id)scrutinyNicknameHandles;
- (id)transitionedHandles;
- (id)truncateNameIfNeeded:(id)arg0;
- (unsigned long long)nicknameUpdateForHandle:(id)arg0 nicknameIfAvailable:(id *)arg1;
- (void)_broadcastNicknamePreferencesDidChange:(id)arg0;
- (void)acceptPendingNicknameForHandleID:(id)arg0 updateType:(unsigned long long)arg1;
- (void)allowHandlesForNicknameSharing:(id)arg0 forChat:(id)arg1 fromHandle:(id)arg2 forceSend:(bool)arg3;
- (void)allowHandlesForNicknameSharing:(id)arg0 fromHandle:(id)arg1 forceSend:(bool)arg2;
- (void)clearHandleFromScrutiny:(id)arg0;
- (void)clearPendingNicknameUpdatesForHandle:(id)arg0 forceClear:(bool)arg1;
- (void)clearPendingNicknameUpdatesForHandle:(id)arg0;
- (void)clearPendingNicknameUpdatesForHandleIDs:(id)arg0;
- (void)denyHandlesForNicknameSharing:(id)arg0;
- (void)fetchPersonalNicknameWithCompletion:(id /* block */)arg0;
- (void)ignorePendingNicknameUpdatesForHandle:(id)arg0;
- (void)ignorePendingNicknameUpdatesForHandleIDs:(id)arg0;
- (void)markAllAsPending;
- (void)markHandleUnderScrutiny:(id)arg0;
- (void)markNickname:(id)arg0 asActive:(bool)arg1;
- (void)markNicknameAsIgnored:(id)arg0;
- (void)markTransitionAsObservedForHandleID:(id)arg0 isAutoUpdate:(bool)arg1;
- (void)sendNameOnlyToHandleIDs:(id)arg0 fromHandleID:(id)arg1;
- (void)sendPersonalNicknameToHandle:(id)arg0 fromHandle:(id)arg1;
- (void)sendPersonalNicknameToHandle:(id)arg0;
- (void)setActiveRecords:(id)arg0;
- (void)setAllowListedHandlesForSharing:(id)arg0;
- (void)setArchivedNicknames:(id)arg0;
- (void)setDenyListedHandlesForSharing:(id)arg0;
- (void)setHandledNicknames:(id)arg0;
- (void)setIgnoredRecords:(id)arg0;
- (void)setIsInitialLoad:(bool)arg0;
- (void)setNicknameHandlesUnderScrutiny;
- (void)setPendingNicknameUpdates:(id)arg0;
- (void)setPersonalNickname:(id)arg0;
- (void)setPersonalNicknameFromOnboardingResult:(id)arg0;
- (void)setResponseHandlers:(id)arg0;
- (void)setScrutinyNicknameHandles:(id)arg0;
- (void)setTransitionedHandles:(id)arg0;
- (void)updateIsActiveList:(id)arg0;
- (void)updateIsIgnoredList:(id)arg0;
- (void)updateLocalNicknameStore;
- (void)updatePendingNicknameForHandleIDs:(id)arg0;
- (void)updatePendingNicknames:(id)arg0 handledNicknames:(id)arg1 archivedNicknames:(id)arg2;
- (void)updatePersonalNickname:(id)arg0;
- (void)updatePersonalNicknameIfNecessaryWithMeCardSharingResult:(id)arg0;
- (void)updateSharingAllowList:(id)arg0 denyList:(id)arg1;
- (void)updateTransitionedNicknameHandles:(id)arg0;

@end
