// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMPinnedConversationsController : NSObject

@property (nonatomic) bool hasCompletedInitialization;
@property (nonatomic) bool hasDefferedPinnedConversationsDidChangeNotification;
@property (nonatomic) long long numberOfPendingForceSyncs;
@property (retain, nonatomic) NSDictionary *chatMetadata;
@property (retain, nonatomic) NSOrderedSet *pinnedConversationIdentifierSet;
@property (retain, nonatomic) NSUbiquitousKeyValueStore *dataStore;

+ (bool)processSupportsPinnedConversations;
+ (id)_forceSyncDispatchQueue;
+ (id)_ubiquitousDispatchQueue;
+ (id)pinConfigurationMigrationKey;
+ (id)requiredKeys;
+ (id)sharedInstance;
+ (long long)currentPinConfigurationRevision;
+ (long long)currentPinConfigurationVersion;
+ (unsigned long long)maximumNumberOfPinnedConversations;

- (bool)_canPostPinnedConversationsDidChangeNotification;
- (bool)_updateLocalStoreWithPinConfiguration:(id)arg0;
- (bool)hasCompletedInitialization;
- (bool)hasDefferedPinnedConversationsDidChangeNotification;
- (bool)pinConfigurationHasCompatibleVersion:(id)arg0;
- (bool)pinConfigurationHasCurrentVersion:(id)arg0;
- (bool)pinConfigurationIsValid:(id)arg0;
- (bool)pinnedConversationsContainsChat:(id)arg0;
- (bool)shouldSync;
- (bool)shouldUpdateExistingPinConfig:(id)arg0 withProposedPinConfig:(id)arg1;
- (bool)shouldWriteProposedPinConfiguration:(id)arg0 toUbiquitousStoreWithExistingPinConfiguration:(id)arg1;
- (id)_dictionaryWithPinnedConversationIdentifiers:(id)arg0 chatMetadata:(id)arg1 updateReason:(id)arg2 timestamp:(id)arg3;
- (id)_locallyStoredPinConfiguration;
- (id)_metadataDictionaryForChat:(id)arg0;
- (id)_ubiquitousPinConfigurationInStore:(id)arg0;
- (id)chatMetadata;
- (id)chatMetadataFromPinConfiguration:(id)arg0;
- (id)dataStore;
- (id)dictionaryWithPinnedConversationIdentifiers:(id)arg0 chatMetadata:(id)arg1 updateReason:(id)arg2;
- (id)init;
- (id)matchingIdentifierForChat:(id)arg0 inIdentifierSet:(id)arg1 withMetadata:(id)arg2;
- (id)matchingIdentifierForChat:(id)arg0;
- (id)mostUpToDatePinConfigurationByComparingPinConfiguration:(id)arg0 toOtherPinConfiguration:(id)arg1;
- (id)pinnedConversationIdentifierSet;
- (id)pinnedConversationIdentifiers;
- (id)pinnedConversationIdentifiersFromPinConfiguration:(id)arg0;
- (id)validatedPinConfigurationWithCurrentVersionForPinConfiguration:(id)arg0;
- (long long)numberOfPendingForceSyncs;
- (unsigned long long)pinIndexForChat:(id)arg0 inIdentifierSet:(id)arg1 withMetadata:(id)arg2;
- (void)_connectedToDaemon:(id)arg0;
- (void)_fetchUbiquitousPinConfiguration:(id /* block */)arg0;
- (void)_handleChatGroupIDDidChangeNotification:(id)arg0;
- (void)_postDeferredPinnedConversationsDidChangeNotificationIfNecessary;
- (void)_postPinnedConversationsDidChangeNotification;
- (void)_setPinnedConversationIdentifiers:(id)arg0 withChatMetadata:(id)arg1 updateReason:(id)arg2 shouldUpdateStores:(bool)arg3;
- (void)_updateUbiquitousStoreWithPinConfiguration:(id)arg0 completion:(id /* block */)arg1;
- (void)conversationWasDeletedWithIdentifier:(id)arg0;
- (void)conversationsWereDeletedWithIdentifiers:(id)arg0;
- (void)fetchMostUpToDatePinConfiguration:(id /* block */)arg0;
- (void)fetchPinnedConversationIdentifiersFromLocalStore;
- (void)forceSynchronizeUbiquitousStore;
- (void)handleNSUbiquitousKeyValueStoreDidChangeExternallyNotification:(id)arg0;
- (void)imCloudKitHooksSetEnabledDidReturn:(id)arg0;
- (void)performPinConfigValidationAndMigrationIfNecessary;
- (void)setChatMetadata:(id)arg0;
- (void)setDataStore:(id)arg0;
- (void)setHasCompletedInitialization:(bool)arg0;
- (void)setHasDefferedPinnedConversationsDidChangeNotification:(bool)arg0;
- (void)setNumberOfPendingForceSyncs:(long long)arg0;
- (void)setPinnedChats:(id)arg0 withUpdateReason:(id)arg1;
- (void)setPinnedConversationIdentifierSet:(id)arg0;
- (void)synchronizeLocalDataStore;
- (void)updateStoresWithPinConfiguration:(id)arg0;

@end
