// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMSharedUtilities.framework/Versions/A/IMSharedUtilities
@interface IMStickerPack : NSObject

@property (copy, nonatomic) NSString *GUID;
@property (copy, nonatomic) NSString *appBundleIdentifier;
@property (copy, nonatomic) NSString *appVersion;
@property (copy, nonatomic) NSString *name;
@property (copy, nonatomic) NSURL *displayAssetURL;
@property (copy, nonatomic) NSURL *fileURL;
@property (readonly, copy, nonatomic) NSDictionary *dictionaryRepresentation;
@property (readonly, nonatomic) NSSet *stickers;

- (id)GUID;
- (id)_generatePackGUIDWithPackID:(id)arg0 appBundleID:(id)arg1 appVersion:(id)arg2;
- (id)appBundleIdentifier;
- (id)appVersion;
- (id)description;
- (id)dictionaryRepresentation;
- (id)displayAssetURL;
- (id)fileURL;
- (id)initWithDictionary:(id)arg0;
- (id)initWithGUID:(id)arg0 name:(id)arg1 displayAssetURL:(id)arg2 fileURL:(id)arg3 appBundleIdentifier:(id)arg4 appVersion:(id)arg5;
- (id)initWithStickerPackProperties:(id)arg0 stickerPackBundleURL:(id)arg1 appBundleIdentifier:(id)arg2 appVersion:(id)arg3;
- (id)name;
- (id)stickers;
- (void)addSticker:(id)arg0;
- (void)setAppBundleIdentifier:(id)arg0;
- (void)setAppVersion:(id)arg0;
- (void)setDisplayAssetURL:(id)arg0;
- (void)setFileURL:(id)arg0;
- (void)setGUID:(id)arg0;
- (void)setName:(id)arg0;

@end
