// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMTapbackSender : NSObject

@property (readonly, nonatomic) IMChat *chat;
@property (readonly, nonatomic) IMTapback *tapback;
@property (readonly, nonatomic) NSAttributedString *attributedContentString;
@property (readonly, nonatomic) NSAttributedString *messageContent;
@property (readonly, nonatomic) NSDictionary *messageSummaryInfo;
@property (readonly, nonatomic) NSString *backwardCompatibilityString;
@property (readonly, nonatomic) NSString *messageGUID;
@property (readonly, nonatomic) NSString *threadIdentifier;
@property (readonly, nonatomic) _NSRange messagePartRange;

- (_NSRange)messagePartRange;
- (id)attributedContentString;
- (id)backwardCompatibilityString;
- (id)chat;
- (id)initWithTapback:(id)arg0 chat:(id)arg1 messageGUID:(id)arg2 messagePartRange:(_NSRange)arg3 messageSummaryInfo:(id)arg4 threadIdentifier:(id)arg5;
- (id)initWithTapback:(id)arg0 chat:(id)arg1 messagePartChatItem:(id)arg2;
- (id)messageContent;
- (id)messageGUID;
- (id)messageSummaryInfo;
- (id)tapback;
- (id)threadIdentifier;
- (void)send;

@end
