// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMSharedUtilities.framework/Versions/A/IMSharedUtilities
@interface IMTapback : NSObject <NSSecureCoding, NSCopying, IMRemoteObjectCoding>

@property (readonly, nonatomic) IMTapback *counterpart;
@property (readonly, nonatomic) IMTapback *removedTapbackCounterpart;
@property (readonly, nonatomic) IMTapback *visibleTapbackCounterpart;
@property (readonly, nonatomic) NSString *representation;
@property (readonly, nonatomic) NSString *serializedTapbackString;
@property (readonly, nonatomic) bool removed;
@property (readonly, nonatomic) bool sendable;
@property (readonly, nonatomic) long long associatedMessageType;

+ (bool)isValidAssociatedMessageType:(long long)arg0;
+ (bool)isValidRepresentation:(id)arg0;
+ (bool)supportsSecureCoding;
+ (id)tapbackWithAssociatedMessageType:(long long)arg0 messageSummaryInfo:(id)arg1 usePlaceholderEmojiIfNeeded:(bool)arg2;
+ (id)tapbackWithAssociatedMessageType:(long long)arg0 messageSummaryInfo:(id)arg1;
+ (id)tapbackWithAssociatedMessageType:(long long)arg0 representation:(id)arg1 usePlaceholderEmojiIfNeeded:(bool)arg2;
+ (id)tapbackWithAssociatedMessageType:(long long)arg0 representation:(id)arg1;
+ (id)tapbackWithSerializedString:(id)arg0;
+ (id)tapbacksForAssociatedMessageTypes:(id)arg0;

- (bool)isEqual:(id)arg0;
- (bool)isRemoved;
- (bool)isSendable;
- (bool)shouldQuoteContentString:(id)arg0;
- (id)actionString;
- (id)adjustMessageSummaryInfoForSending:(id)arg0;
- (id)backwardCompatibilityStringFormatForMessageSummaryInfo:(id)arg0;
- (id)backwardCompatibilityStringWithMessageSummaryInfo:(id)arg0;
- (id)contentTypeStringForMessageSummaryInfo:(id)arg0;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)counterpart;
- (id)description;
- (id)init;
- (id)initWithAssociatedMessageType:(long long)arg0 representation:(id)arg1;
- (id)initWithAssociatedMessageType:(long long)arg0;
- (id)initWithCoder:(id)arg0;
- (id)initWithIMRemoteObjectSerializedDictionary:(id)arg0;
- (id)longContentTypeStringForPluginBundleID:(id)arg0 pluginDisplayName:(id)arg1;
- (id)previewStringFormatForMessageSummaryInfo:(id)arg0 isFromMe:(bool)arg1;
- (id)previewStringWithMessageSummaryInfo:(id)arg0 senderDisplayName:(id)arg1 isFromMe:(bool)arg2;
- (id)removedTapbackCounterpart;
- (id)representation;
- (id)serializedTapbackString;
- (id)visibleTapbackCounterpart;
- (long long)associatedMessageType;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg0;
- (void)encodeWithIMRemoteObjectSerializedDictionary:(id)arg0;

@end
