// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/Frameworks/Messages.framework/Versions/A/Messages
@interface MSConversation : NSObject

@property (readonly, copy, nonatomic) NSArray *draftAssetArchives;
@property (readonly, nonatomic) NSArray *recipientAddresses;
@property (readonly, nonatomic) NSData *engramID;
@property (readonly, nonatomic) NSString *conversationIdentifier;
@property (readonly, nonatomic) NSString *iMessageLoginID;
@property (readonly, nonatomic) NSString *senderAddress;
@property (readonly, nonatomic) NSUUID *identifier;
@property (readonly, nonatomic) NSUUID *localParticipantIdentifier;
@property (readonly, nonatomic) bool isBusiness;
@property (readonly, nonatomic) bool isiMessage;
@property (retain, nonatomic) MSMessage *selectedMessage;
@property (retain, nonatomic) NSArray *remoteParticipantIdentifiers;
@property (retain, nonatomic) _MSMessageAppContext *context;
@property (weak, nonatomic) id<MSConversationDelegate> delegate;

+ (id)activeConversation;

- (bool)isBusiness;
- (bool)isiMessage;
- (id)_initWithState:(id)arg0 context:(id)arg1;
- (id)context;
- (id)conversationIdentifier;
- (id)delegate;
- (id)draftAssetArchives;
- (id)engramID;
- (id)iMessageLoginID;
- (id)identifier;
- (id)inputMessagePayload;
- (id)localParticipantIdentifier;
- (id)recipientAddresses;
- (id)recipientIdentifiers;
- (id)remoteParticipantIdentifiers;
- (id)selectedMessage;
- (id)senderAddress;
- (id)senderIdentifier;
- (void)_insertAssetArchive:(id)arg0 completionHandler:(id /* block */)arg1;
- (void)_insertAssetArchive:(id)arg0 skipShelf:(bool)arg1 completionHandler:(id /* block */)arg2;
- (void)_insertAttachment:(id)arg0 adamID:(id)arg1 appName:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)_insertAttachment:(id)arg0 withAlternateFilename:(id)arg1 skipShelf:(bool)arg2 completionHandler:(id /* block */)arg3;
- (void)_insertMessage:(id)arg0 localizedChangeDescription:(id)arg1 skipShelf:(bool)arg2 completionHandler:(id /* block */)arg3;
- (void)_insertMessage:(id)arg0 skipShelf:(bool)arg1 completionHandler:(id /* block */)arg2;
- (void)_insertRichLink:(id)arg0 skipShelf:(bool)arg1 completionHandler:(id /* block */)arg2;
- (void)_insertSticker:(id)arg0 skipShelf:(bool)arg1 completionHandler:(id /* block */)arg2;
- (void)_insertSticker:(id)arg0 skipShelf:(bool)arg1 frameInWindowCoordinates:(CGRect)arg2 completionHandler:(id /* block */)arg3;
- (void)_insertText:(id)arg0 skipShelf:(bool)arg1 completionHandler:(id /* block */)arg2;
- (void)_removeAssetArchiveWithIdentifier:(id)arg0 completionHandler:(id /* block */)arg1;
- (void)_sendAssetArchive:(id)arg0 completionHandler:(id /* block */)arg1;
- (void)_updateWithState:(id)arg0;
- (void)insertAttachment:(id)arg0 withAlternateFilename:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)insertImage:(id)arg0 completionHandler:(id /* block */)arg1;
- (void)insertMediaAtURL:(id)arg0 attributionURL:(id)arg1 attributionIcon:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)insertMediaAtURL:(id)arg0 completionHandler:(id /* block */)arg1;
- (void)insertMessage:(id)arg0 completionHandler:(id /* block */)arg1;
- (void)insertMessage:(id)arg0 localizedChangeDescription:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)insertRichLink:(id)arg0 completionHandler:(id /* block */)arg1;
- (void)insertSticker:(id)arg0 completionHandler:(id /* block */)arg1;
- (void)insertSticker:(id)arg0 withSourceFrame:(CGRect)arg1 completionHandler:(id /* block */)arg2;
- (void)insertStickerWithImage:(id)arg0 completionHandler:(id /* block */)arg1;
- (void)insertStickerWithMediaAtURL:(id)arg0 completionHandler:(id /* block */)arg1;
- (void)insertText:(id)arg0 completionHandler:(id /* block */)arg1;
- (void)sendAttachment:(id)arg0 withAlternateFilename:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)sendMessage:(id)arg0 completionHandler:(id /* block */)arg1;
- (void)sendMessage:(id)arg0 localizedChangeDescription:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)sendRichLink:(id)arg0 completionHandler:(id /* block */)arg1;
- (void)sendSticker:(id)arg0 completionHandler:(id /* block */)arg1;
- (void)sendText:(id)arg0 completionHandler:(id /* block */)arg1;
- (void)setContext:(id)arg0;
- (void)setDelegate:(id)arg0;
- (void)setRemoteParticipantIdentifiers:(id)arg0;
- (void)setSelectedMessage:(id)arg0;
- (void)stageMessage:(id)arg0 localizedChangeDescription:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)unstageAllItems;
- (void)updateMessagePayload:(id)arg0 completionHandler:(id /* block */)arg1;

@end
