// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/Frameworks/Messages.framework/Versions/A/Messages
@interface MSMessage : NSObject <NSCopying, NSSecureCoding>

@property (copy, nonatomic) MSMessageLayout *layout;
@property (copy, nonatomic) NSData *_data;
@property (copy, nonatomic) NSError *error;
@property (copy, nonatomic) NSString *accessibilityLabel;
@property (copy, nonatomic) NSString *breadcrumbText;
@property (copy, nonatomic) NSString *statusText;
@property (copy, nonatomic) NSString *summaryText;
@property (copy, nonatomic) NSURL *URL;
@property (nonatomic) bool isFromMe;
@property (nonatomic) bool pending;
@property (nonatomic) bool requiresValidation;
@property (nonatomic) bool shouldExpire;
@property (readonly, nonatomic) MSSession *session;
@property (retain, nonatomic) NSDate *time;
@property (retain, nonatomic) NSString *senderAddress;
@property (retain, nonatomic) NSUUID *senderParticipantIdentifier;

+ (bool)supportsSecureCoding;

- (bool)isEqual:(id)arg0;
- (bool)isFromMe;
- (bool)isPending;
- (bool)requiresValidation;
- (bool)shouldExpire;
- (id)URL;
- (id)_data;
- (id)_payloadDataFromAppIconData:(id)arg0 appName:(id)arg1 adamID:(id)arg2 allowDataPayloads:(bool)arg3;
- (id)_pluginPayloadWithAppIconData:(id)arg0 appName:(id)arg1 adamID:(id)arg2 allowDataPayloads:(bool)arg3;
- (id)_pluginPayloadWithAppIconData:(id)arg0 appName:(id)arg1 allowDataPayloads:(bool)arg2;
- (id)_sanitizedCopy;
- (id)_shallowCopy;
- (id)accessibilityLabel;
- (id)breadcrumbText;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)error;
- (id)init;
- (id)initWithCoder:(id)arg0;
- (id)initWithSession:(id)arg0;
- (id)layout;
- (id)senderAddress;
- (id)senderParticipantIdentifier;
- (id)session;
- (id)statusText;
- (id)summaryText;
- (id)time;
- (unsigned long long)hash;
- (void)_mergeSanitizedDataFromMessage:(id)arg0;
- (void)_mergeSanitizedKeepingModifiedMessage:(id)arg0;
- (void)_sanitize;
- (void)encodeWithCoder:(id)arg0;
- (void)setAccessibilityLabel:(id)arg0;
- (void)setBreadcrumbText:(id)arg0;
- (void)setError:(id)arg0;
- (void)setIsFromMe:(bool)arg0;
- (void)setLayout:(id)arg0;
- (void)setPending:(bool)arg0;
- (void)setRequiresValidation:(bool)arg0;
- (void)setSenderAddress:(id)arg0;
- (void)setSenderParticipantIdentifier:(id)arg0;
- (void)setShouldExpire:(bool)arg0;
- (void)setStatusText:(id)arg0;
- (void)setSummaryText:(id)arg0;
- (void)setTime:(id)arg0;
- (void)setURL:(id)arg0;
- (void)set_data:(id)arg0;

@end
