// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/SPOwner.framework/Versions/A/SPOwner
@interface SPCommand : NSObject <NSCopying, NSSecureCoding>

@property (copy, nonatomic) NSDate *expiration;
@property (copy, nonatomic) NSNumber *duration;
@property (copy, nonatomic) NSString *lostModeEmail;
@property (copy, nonatomic) NSString *lostModeMessage;
@property (copy, nonatomic) NSString *lostModePhoneNumber;
@property (copy, nonatomic) NSString *obfuscatedIdentifier;
@property (copy, nonatomic) NSUUID *beaconIdentifier;
@property (copy, nonatomic) NSUUID *identifier;
@property (copy, nonatomic) SPHandle *handle;
@property (nonatomic) bool enableLostMode;
@property (nonatomic) long long playSoundContext;
@property (nonatomic) long long type;
@property (readonly, copy, nonatomic) NSString *taskName;

+ (bool)supportsSecureCoding;
+ (id)beginLeashingWithBeaconUUID:(id)arg0;
+ (id)connectToBeaconUUID:(id)arg0;
+ (id)disableLostModeForBeaconUUID:(id)arg0;
+ (id)disableNotifyWhenFound:(id)arg0;
+ (id)disconnectFromBeaconUUID:(id)arg0;
+ (id)enableLostModeForBeaconUUID:(id)arg0 message:(id)arg1 phoneNumber:(id)arg2 email:(id)arg3;
+ (id)enableNotifyWhenFound:(id)arg0;
+ (id)endLeashingWithBeaconUUID:(id)arg0;
+ (id)locate:(id)arg0;
+ (id)playSoundWithBeaconUUID:(id)arg0 duration:(double)arg1;
+ (id)playSoundWithBeaconUUID:(id)arg0 withContext:(long long)arg1;
+ (id)playSoundWithBeaconUUID:(id)arg0;
+ (id)setObfuscatedIdentifier:(id)arg0;
+ (id)startBTFindingWithBeaconUUID:(id)arg0;
+ (id)startNotifyWhenFound:(id)arg0;
+ (id)stopBTFindingWithBeaconUUID:(id)arg0;
+ (id)stopNotifyWhenFound:(id)arg0;
+ (id)stopSoundWithBeaconUUID:(id)arg0;
+ (id)unpairWithBeaconUUID:(id)arg0;
+ (id)updateAccessoryFirmware:(id)arg0;

- (bool)enableLostMode;
- (id)beaconIdentifier;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)duration;
- (id)expiration;
- (id)handle;
- (id)identifier;
- (id)initWithBeaconUUID:(id)arg0 type:(long long)arg1 expiration:(id)arg2 duration:(id)arg3 handle:(id)arg4 lostModeEmail:(id)arg5 lostModeMessage:(id)arg6 lostModePhoneNumber:(id)arg7 obfuscatedIdentifier:(id)arg8 identifier:(id)arg9;
- (id)initWithBeaconUUID:(id)arg0 type:(long long)arg1 expiration:(id)arg2 duration:(id)arg3 handle:(id)arg4 lostModeMessage:(id)arg5 lostModePhoneNumber:(id)arg6 obfuscatedIdentifier:(id)arg7;
- (id)initWithBeaconUUID:(id)arg0 type:(long long)arg1 expiration:(id)arg2 duration:(id)arg3 playSoundContext:(long long)arg4 handle:(id)arg5 lostModeMessage:(id)arg6 lostModePhoneNumber:(id)arg7 obfuscatedIdentifier:(id)arg8 identifier:(id)arg9;
- (id)initWithCoder:(id)arg0;
- (id)lostModeEmail;
- (id)lostModeMessage;
- (id)lostModePhoneNumber;
- (id)obfuscatedIdentifier;
- (id)taskName;
- (long long)playSoundContext;
- (long long)type;
- (void)encodeWithCoder:(id)arg0;
- (void)setBeaconIdentifier:(id)arg0;
- (void)setDuration:(id)arg0;
- (void)setEnableLostMode:(bool)arg0;
- (void)setExpiration:(id)arg0;
- (void)setHandle:(id)arg0;
- (void)setIdentifier:(id)arg0;
- (void)setLostModeEmail:(id)arg0;
- (void)setLostModeMessage:(id)arg0;
- (void)setLostModePhoneNumber:(id)arg0;
- (void)setObfuscatedIdentifier:(id)arg0;
- (void)setPlaySoundContext:(long long)arg0;
- (void)setType:(long long)arg0;

@end
