// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/SPOwner.framework/Versions/A/SPOwner
@interface SPSafeLocation : NSObject <NSSecureCoding, NSCopying>

@property (copy, nonatomic) CLLocation *location;
@property (copy, nonatomic) NSSet *associatedBeacons;
@property (copy, nonatomic) NSString *name;
@property (copy, nonatomic) NSUUID *identifier;
@property (nonatomic) long long approvalState;
@property (nonatomic) long long type;
@property (readonly, nonatomic) double altitude;
@property (readonly, nonatomic) double course;
@property (readonly, nonatomic) double courseAccuracy;
@property (readonly, nonatomic) double horizontalAccuracy;
@property (readonly, nonatomic) double latitude;
@property (readonly, nonatomic) double longitude;
@property (readonly, nonatomic) double speed;
@property (readonly, nonatomic) double speedAccuracy;
@property (readonly, nonatomic) double verticalAccuracy;

+ (bool)supportsSecureCoding;

- (bool)isEqual:(id)arg0;
- (double)altitude;
- (double)course;
- (double)courseAccuracy;
- (double)horizontalAccuracy;
- (double)latitude;
- (double)longitude;
- (double)speed;
- (double)speedAccuracy;
- (double)verticalAccuracy;
- (id)associatedBeacons;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)debugDescription;
- (id)identifier;
- (id)initWithCoder:(id)arg0;
- (id)initWithIdentifier:(id)arg0 type:(long long)arg1 name:(id)arg2 location:(id)arg3 associatedBeacons:(id)arg4 approvalState:(long long)arg5;
- (id)initWithType:(long long)arg0 name:(id)arg1 location:(id)arg2 approvalState:(long long)arg3;
- (id)location;
- (id)mutableSafeLocation;
- (id)name;
- (long long)approvalState;
- (long long)type;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg0;
- (void)setApprovalState:(long long)arg0;
- (void)setAssociatedBeacons:(id)arg0;
- (void)setIdentifier:(id)arg0;
- (void)setLocation:(id)arg0;
- (void)setName:(id)arg0;
- (void)setType:(long long)arg0;

@end
