// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/Versions/A/TelephonyUtilities
@interface TUConversationLink : NSObject <NSCopying, NSSecureCoding>

@property (copy, nonatomic) NSData *publicKey;
@property (copy, nonatomic) NSSet *invitedMemberHandles;
@property (copy, nonatomic) NSString *linkName;
@property (copy, nonatomic) NSString *pseudonym;
@property (nonatomic) bool locallyCreated;
@property (nonatomic) long long linkLifetimeScope;
@property (readonly, copy, nonatomic) NSString *displayName;
@property (readonly, nonatomic) NSURL *URL;
@property (retain, nonatomic) NSDate *creationDate;
@property (retain, nonatomic) NSDate *deletionDate;
@property (retain, nonatomic) NSDate *expirationDate;
@property (retain, nonatomic) NSString *URLFragment;
@property (retain, nonatomic) NSUUID *groupUUID;
@property (retain, nonatomic) TUHandle *originatorHandle;

+ (bool)checkMatchingConversationLinkCriteriaForURL:(id)arg0;
+ (bool)supportsSecureCoding;
+ (id)baseURLComponentsForURL:(id)arg0;
+ (id)baseURLStrings;
+ (id)baseURLs;
+ (id)conversationLinkComponentsFromURL:(id)arg0;
+ (id)conversationLinkForURL:(id)arg0;
+ (id)featureFlags;
+ (id)preferredBaseURL;
+ (id)preferredBaseURLString;
+ (id)prefixedPseudonymFor:(id)arg0;
+ (id)publicKeyForBase64EncodedString:(id)arg0;
+ (id)userConfiguration;
+ (unsigned long long)conversationLinkVersion;

- (bool)allInvitedMembersInContactsChecking:(id)arg0;
- (bool)canCreateConversations;
- (bool)isEqual:(id)arg0;
- (bool)isEqualToConversationLink:(id)arg0;
- (bool)isEquivalentToConversationLink:(id)arg0;
- (bool)isEquivalentToPseudonym:(id)arg0 andPublicKey:(id)arg1;
- (bool)isLocallyCreated;
- (id)URL;
- (id)URLFragment;
- (id)base64PublicKey;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)creationDate;
- (id)deletionDate;
- (id)description;
- (id)displayName;
- (id)expirationDate;
- (id)fetchedResults;
- (id)generateDisplayName;
- (id)groupUUID;
- (id)initWithCoder:(id)arg0;
- (id)initWithDescriptor:(id)arg0;
- (id)initWithPseudonym:(id)arg0 publicKey:(id)arg1 groupUUID:(id)arg2 originatorHandle:(id)arg3 creationDate:(id)arg4 deletionDate:(id)arg5 expirationDate:(id)arg6 invitedMemberHandles:(id)arg7 locallyCreated:(bool)arg8 linkName:(id)arg9 linkLifetimeScope:(long long)arg10;
- (id)initWithPseudonym:(id)arg0 publicKey:(id)arg1 groupUUID:(id)arg2 originatorHandle:(id)arg3;
- (id)invitedMemberHandles;
- (id)linkName;
- (id)originatorHandle;
- (id)pseudonym;
- (id)publicKey;
- (id)unprefixedPseudonym;
- (id)valueForKey:(id)arg0;
- (long long)linkLifetimeScope;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg0;
- (void)setCreationDate:(id)arg0;
- (void)setDeletionDate:(id)arg0;
- (void)setExpirationDate:(id)arg0;
- (void)setGroupUUID:(id)arg0;
- (void)setInvitedMemberHandles:(id)arg0;
- (void)setLinkLifetimeScope:(long long)arg0;
- (void)setLinkName:(id)arg0;
- (void)setLocallyCreated:(bool)arg0;
- (void)setOriginatorHandle:(id)arg0;
- (void)setPseudonym:(id)arg0;
- (void)setPublicKey:(id)arg0;
- (void)setURLFragment:(id)arg0;

@end
