// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

@protocol TUConversationManagerDataSourceDelegate

// required
- (void)activeParticipant:(id)arg0 addedHighlightToConversation:(id)arg1 highlightIdentifier:(id)arg2 oldHighlightIdentifier:(id)arg3 isFirstAdd:(id)arg4;
- (void)activeParticipant:(id)arg0 removedHighlightFromConversation:(id)arg1 highlightIdentifier:(id)arg2;
- (void)activityAuthorizationsChangedForDataSource:(id)arg0 oldActivityAuthorizedBundleIdentifiers:(id)arg1;
- (void)addedCollaborationDictionary:(id)arg0 forConversation:(id)arg1;
- (void)conversation:(id)arg0 addedMembersLocally:(id)arg1;
- (void)conversation:(id)arg0 buzzedMember:(id)arg1;
- (void)conversation:(id)arg0 collaborationStateChanged:(id)arg1 highlightIdentifier:(id)arg2;
- (void)conversation:(id)arg0 didChangeSceneAssociationForActivitySession:(id)arg1;
- (void)conversation:(id)arg0 didChangeStateForActivitySession:(id)arg1;
- (void)conversation:(id)arg0 participant:(id)arg1 addedNotice:(id)arg2;
- (void)conversation:(id)arg0 receivedActivitySessionEvent:(id)arg1;
- (void)conversation:(id)arg0 screenSharingChangedForParticipant:(id)arg1;
- (void)conversationManagerDataSource:(id)arg0 conversation:(id)arg1 appLaunchState:(id)arg2 forActivitySession:(id)arg3;
- (void)conversationManagerDataSource:(id)arg0 didChangeActivatedConversationLinks:(id)arg1;
- (void)conversationManagerDataSource:(id)arg0 messagesGroupDetailsForMessagesGroupId:(id)arg1 completionHandler:(id)arg2;
- (void)conversationUpdatedMessagesGroupPhoto:(id)arg0;
- (void)conversationsChangedForDataSource:(id)arg0 conversationsByGroupUUID:(id)arg1 oldConversationsByGroupUUID:(id)arg2;
- (void)conversationsChangedForDataSource:(id)arg0 updatedIncomingPendingConversationsByGroupUUID:(id)arg1;
- (void)receivedTrackedPendingMember:(id)arg0 forConversationLink:(id)arg1;
- (void)remoteScreenShareAttributesChanged:(id)arg0 isLocallySharing:(id)arg1;
- (void)remoteScreenShareEndedWithReason:(id)arg0;
- (void)screenSharingAvailableChanged:(id)arg0;
- (void)serverDisconnectedForDataSource:(id)arg0 oldConversationsByGroupUUID:(id)arg1;
- (void)sharePlayAvailableChanged:(id)arg0;

@end
