// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/Versions/A/TelephonyUtilities
@interface TUConversationLinkDescriptor : NSObject <NSCopying, NSSecureCoding>

@property (copy, nonatomic) NSData *privateKey;
@property (copy, nonatomic) NSData *publicKey;
@property (copy, nonatomic) NSSet *invitedHandles;
@property (copy, nonatomic) NSString *name;
@property (copy, nonatomic) NSString *pseudonym;
@property (nonatomic) bool activated;
@property (nonatomic) int version;
@property (nonatomic) long long linkLifetimeScope;
@property (retain, nonatomic) NSDate *creationDate;
@property (retain, nonatomic) NSDate *deletionDate;
@property (retain, nonatomic) NSDate *expirationDate;
@property (retain, nonatomic) NSUUID *groupUUID;
@property (retain, nonatomic) TUConversationLinkOriginator *originator;

+ (bool)supportsSecureCoding;

- (bool)isActivated;
- (bool)isEqual:(id)arg0;
- (bool)isEqualToConversationLinkDescriptor:(id)arg0;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)creationDate;
- (id)deletionDate;
- (id)description;
- (id)expirationDate;
- (id)groupUUID;
- (id)initWithCoder:(id)arg0;
- (id)initWithConversationLinkDescriptor:(id)arg0;
- (id)initWithGroupUUID:(id)arg0 originator:(id)arg1 pseudonym:(id)arg2 publicKey:(id)arg3;
- (id)invitedHandles;
- (id)mutableCopyWithZone:(_NSZone *)arg0;
- (id)name;
- (id)originator;
- (id)privateKey;
- (id)pseudonym;
- (id)publicKey;
- (int)version;
- (long long)linkLifetimeScope;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg0;
- (void)setActivated:(bool)arg0;
- (void)setCreationDate:(id)arg0;
- (void)setDeletionDate:(id)arg0;
- (void)setExpirationDate:(id)arg0;
- (void)setGroupUUID:(id)arg0;
- (void)setInvitedHandles:(id)arg0;
- (void)setLinkLifetimeScope:(long long)arg0;
- (void)setName:(id)arg0;
- (void)setOriginator:(id)arg0;
- (void)setPrivateKey:(id)arg0;
- (void)setPseudonym:(id)arg0;
- (void)setPublicKey:(id)arg0;
- (void)setVersion:(int)arg0;

@end
