// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/Versions/A/TelephonyUtilities
@interface TUHandle : NSObject <NSCopying, NSSecureCoding>

@property (copy, nonatomic) NSString *isoCountryCode;
@property (copy, nonatomic) NSString *siriDisplayName;
@property (copy, nonatomic) NSString *value;
@property (nonatomic) bool hasSetISOCountryCode;
@property (nonatomic) long long type;
@property (readonly, copy, nonatomic) NSDictionary *dictionaryRepresentation;
@property (readonly, copy, nonatomic) NSString *normalizedValue;
@property (readonly, nonatomic) bool shouldHideContact;

+ (bool)supportsSecureCoding;
+ (id)handleForCHRecentCall:(id)arg0 validHandlesOnly:(bool)arg1;
+ (id)handleForCHRecentCall:(id)arg0;
+ (id)handleFromMessagingData:(id)arg0;
+ (id)handleWithDestinationID:(id)arg0;
+ (id)handleWithDictionaryRepresentation:(id)arg0;
+ (id)handleWithPerson:(id)arg0;
+ (id)handleWithPersonHandle:(id)arg0;
+ (id)handlesForCHRecentCall:(id)arg0 validHandlesOnly:(bool)arg1;
+ (id)handlesForCHRecentCall:(id)arg0;
+ (id)normalizedEmailAddressHandleForValue:(id)arg0;
+ (id)normalizedGenericHandleForValue:(id)arg0;
+ (id)normalizedHandleWithDestinationID:(id)arg0;
+ (id)normalizedPhoneNumberHandleForValue:(id)arg0 isoCountryCode:(id)arg1;
+ (id)stringForType:(long long)arg0;
+ (long long)handleTypeForCHHandle:(id)arg0;

- (bool)hasSetISOCountryCode;
- (bool)isCanonicallyEqualToHandle:(id)arg0 isoCountryCode:(id)arg1;
- (bool)isEqual:(id)arg0;
- (bool)isEqualToHandle:(id)arg0;
- (bool)isEquivalentToHandle:(id)arg0;
- (bool)isValidForISOCountryCode:(id)arg0;
- (bool)shouldHideContact;
- (bool)shouldHideContactWithLockState:(bool)arg0;
- (id)canonicalHandleForISOCountryCode:(id)arg0;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)description;
- (id)dictionaryRepresentation;
- (id)init;
- (id)initWithCoder:(id)arg0;
- (id)initWithDestinationID:(id)arg0;
- (id)initWithHandle:(id)arg0;
- (id)initWithType:(long long)arg0 value:(id)arg1 normalizedValue:(id)arg2;
- (id)initWithType:(long long)arg0 value:(id)arg1 siriDisplayName:(id)arg2;
- (id)initWithType:(long long)arg0 value:(id)arg1;
- (id)isoCountryCode;
- (id)messagingData;
- (id)normalizedValue;
- (id)personHandle;
- (id)siriDisplayName;
- (id)value;
- (long long)type;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg0;
- (void)setHasSetISOCountryCode:(bool)arg0;
- (void)setIsoCountryCode:(id)arg0;
- (void)setSiriDisplayName:(id)arg0;
- (void)setType:(long long)arg0;
- (void)setValue:(id)arg0;

@end
