// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/Versions/A/TelephonyUtilities
@interface TULinkShareItem : NSObject

@property (copy, nonatomic) NSString *title;
@property (copy, nonatomic) NSURL *placeholder;
@property (retain, nonatomic) TUConversationLink *tuConversationLink;

- (id)initWithTUConversationLink:(id)arg0 title:(id)arg1 placeholder:(id)arg2;
- (id)initWithTUConversationLink:(id)arg0;
- (id)placeholder;
- (id)title;
- (id)tuConversationLink;
- (void)setPlaceholder:(id)arg0;
- (void)setTitle:(id)arg0;
- (void)setTuConversationLink:(id)arg0;

@end
