// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/Frameworks/Messages.framework/Versions/A/Messages
@interface _MSMessageCustomAcknowledgement : NSObject <NSCopying, NSSecureCoding>

@property (nonatomic) bool isFromMe;
@property (readonly, nonatomic) MSSession *session;
@property (readonly, nonatomic) NSDate *time;
@property (retain, nonatomic) NSString *senderAddress;
@property (retain, nonatomic) NSURL *URL;
@property (retain, nonatomic) NSUUID *senderParticipantIdentifier;

+ (bool)supportsSecureCoding;

- (bool)isFromMe;
- (id)URL;
- (id)_payloadDataFromAppName:(id)arg0 adamID:(id)arg1;
- (id)_pluginPayloadWithSelectedMessage:(id)arg0 appName:(id)arg1 adamID:(id)arg2;
- (id)_sanitizedCopy;
- (id)_shallowCopy;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)initWithCoder:(id)arg0;
- (id)initWithSession:(id)arg0 isFromMe:(bool)arg1 time:(id)arg2;
- (id)senderAddress;
- (id)senderParticipantIdentifier;
- (id)session;
- (id)time;
- (void)_sanitize;
- (void)encodeWithCoder:(id)arg0;
- (void)setIsFromMe:(bool)arg0;
- (void)setSenderAddress:(id)arg0;
- (void)setSenderParticipantIdentifier:(id)arg0;
- (void)setURL:(id)arg0;

@end
