// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/Stickers.framework/Versions/A/Stickers
@interface _STKImageGlyphRecencyObjCFacade : NSObject

- (id)init;
- (void)didUseCharacter:(id)arg0 completionHandler:(/* '"' */ id)arg1 :(unsigned short)arg2 :(unsigned short)arg3 :(/* 't' */ id)arg4 :(int)arg5 :(/* 'g' */ id)arg6 :(/* '"' */ id)arg7 :(id /* block */)arg8 :(/* '<' */ id)arg9 :(void)arg10 :(id /* block */)arg11 :(double)arg12 :(id)arg13 :(/* '"' */ id)arg14 :(unsigned short)arg15 :(/* 'E' */ id)arg16 :(/* '"' */ id)arg17 :(/* '>' */ id)arg18;
- (void)didUseEmoji:(id)arg0 completionHandler:(/* '"' */ id)arg1 :(unsigned short)arg2 :(unsigned short)arg3 :(/* 't' */ id)arg4 :(int)arg5 :(/* 'g' */ id)arg6 :(/* '"' */ id)arg7 :(id /* block */)arg8 :(/* '<' */ id)arg9 :(void)arg10 :(id /* block */)arg11 :(double)arg12 :(id)arg13 :(/* '"' */ id)arg14 :(unsigned short)arg15 :(/* 'E' */ id)arg16 :(/* '"' */ id)arg17 :(/* '>' */ id)arg18;
- (void)didUseSticker:(id)arg0 completionHandler:(/* '"' */ id)arg1 :(unsigned short)arg2 :(/* 'T' */ id)arg3 :(/* 'K' */ id)arg4 :(unsigned short)arg5 :(/* 't' */ id)arg6 :(int)arg7 :(char)arg8 :(/* 'k' */ id)arg9 :(/* 'e' */ id)arg10 :(/* '"' */ id)arg11 :(id /* block */)arg12 :(/* '<' */ id)arg13 :(void)arg14 :(id /* block */)arg15 :(double)arg16 :(id)arg17 :(/* '"' */ id)arg18 :(unsigned short)arg19 :(/* 'E' */ id)arg20 :(/* '"' */ id)arg21 :(/* '>' */ id)arg22;
- (void)resetRecentsWithCompletionHandler:(id /* block */)arg0 :(/* '<' */ id)arg1 :(void)arg2 :(id /* block */)arg3 :(id)arg4 :(/* '"' */ id)arg5 :(unsigned short)arg6 :(/* 'E' */ id)arg7 :(/* '"' */ id)arg8 :(/* '>' */ id)arg9;

@end
