// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/Stickers.framework/Versions/A/Stickers
@interface _STKSticker : NSObject

@property (nonatomic, readonly) NSArray *representations;
@property (nonatomic, readonly) NSData *metadata;
@property (nonatomic, readonly) NSString *accessibilityName;
@property (nonatomic, readonly) NSString *description;
@property (nonatomic, readonly) NSString *externalURI;
@property (nonatomic, readonly) NSString *name;
@property (nonatomic, readonly) NSString *rewrittenPrompt;
@property (nonatomic, readonly) NSString *sanitizedPrompt;
@property (nonatomic, readonly) NSString *searchText;
@property (nonatomic, readonly) NSUUID *identifier;
@property (nonatomic, readonly) _STKStickerAttributionInfo *attributionInfo;
@property (nonatomic, readonly) long long effectType;

- (id)accessibilityName;
- (id)attributionInfo;
- (id)description;
- (id)externalURI;
- (id)identifier;
- (id)init;
- (id)metadata;
- (id)name;
- (id)representations;
- (id)rewrittenPrompt;
- (id)sanitizedPrompt;
- (id)searchText;
- (long long)effectType;

@end
