// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/Stickers.framework/Versions/A/Stickers
@interface _STKStickerRepresentation : NSObject

@property (nonatomic, readonly) CGSize size;
@property (nonatomic, readonly) NSData *data;
@property (nonatomic, readonly) NSString *description;
@property (nonatomic, readonly) NSString *role;
@property (nonatomic, readonly) NSUUID *identifier;
@property (nonatomic, readonly) NSUUID *stickerIdentifier;
@property (nonatomic, readonly) UTType *uti;
@property (nonatomic, readonly) _STKStickerEffect *effect;

+ (id)roles;

- (CGSize)size;
- (id)data;
- (id)description;
- (id)effect;
- (id)identifier;
- (id)init;
- (id)role;
- (id)stickerIdentifier;
- (id)uti;

@end
