// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/Stickers.framework/Versions/A/Stickers
@interface _STKStickerRepresentationRole : NSObject

@property (nonatomic, readonly) NSString *animatedVariant;
@property (nonatomic, readonly) NSString *keyboardPreview;
@property (nonatomic, readonly) NSString *stillVariant;

- (id)animatedVariant;
- (id)init;
- (id)keyboardPreview;
- (id)stillVariant;

@end
