// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/Stickers.framework/Versions/A/Stickers
@interface _STKMessagesObjCStoreFacade : NSObject

- (bool)donateStickerToRecentsWithIdentifier:(id)arg0 representations:(id)arg1 stickerEffectEnum:(long long)arg2 externalURI:(id)arg3 name:(id)arg4 accessibilityName:(id)arg5 metadata:(id)arg6 attributionInfo:(id)arg7 error:(id *)arg8;
- (id)init;

@end
