// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/ChatKit.framework/Versions/A/ChatKit
@interface CKScheduledUpdater : CKManualUpdater

@property (nonatomic) bool updateSynchronouslyIfPossible;
@property (retain, nonatomic) NSCountedSet *holdingUpdatesKeys;

- (bool)isHoldingUpdates;
- (bool)isHoldingUpdatesForKey:(id)arg0;
- (bool)updateSynchronouslyIfPossible;
- (id)description;
- (id)holdingUpdatesKeys;
- (id)initWithTarget:(id)arg0 action:(SEL)arg1;
- (void)beginHoldingUpdatesForKey:(id)arg0;
- (void)dealloc;
- (void)endHoldingAllUpdates;
- (void)endHoldingAllUpdatesForKey:(id)arg0;
- (void)endHoldingUpdatesForKey:(id)arg0;
- (void)invalidate;
- (void)setHoldingUpdatesKeys:(id)arg0;
- (void)setNeedsUpdate;
- (void)setUpdateSynchronouslyIfPossible:(bool)arg0;
- (void)updateIfNeeded;

@end
