// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/ChatKit.framework/Versions/A/ChatKit
@interface CKSendLaterPluginInfo : NSObject <NSSecureCoding, NSCoding>

@property (nonatomic) bool showingDatePicker;
@property (nonatomic, copy) NSDate *selectedDate;

+ (bool)supportsSecureCoding;

- (bool)showingDatePicker;
- (id)init;
- (id)initWithCoder:(id)arg0;
- (id)initWithConversation:(id)arg0;
- (id)initWithSelectedDate:(id)arg0;
- (id)selectedDate;
- (void)addObserver:(id)arg0;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg0;
- (void)setSelectedDate:(id)arg0;
- (void)setShowingDatePicker:(bool)arg0;

@end
