// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/ChatKit.framework/Versions/A/ChatKit
@interface CKStickerMediaObject : CKImageMediaObject

@property (nonatomic, readonly) bool canUseAsBackground;

+ (bool)shouldShadePreview;

- (bool)canUseAsBackground;
- (id)attachmentSummary:(unsigned long long)arg0;

@end
