// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/ChatKit.framework/Versions/A/ChatKit
@interface CKStickerReactionSession : NSObject

@property (nonatomic, readonly) bool didSendSticker;
@property (nonatomic, retain) CKConversation *conversation;
@property (nonatomic, retain) CKMessagePartChatItem *chatItem;
@property (nonatomic, retain) CKTranscriptBalloonCell *cell;

- (bool)didSendSticker;
- (id)cell;
- (id)chatItem;
- (id)conversation;
- (id)init;
- (id)initWithConversation:(id)arg0 chatItem:(id)arg1 cell:(id)arg2;
- (void)sendSticker:(id)arg0;
- (void)setCell:(id)arg0;
- (void)setChatItem:(id)arg0;
- (void)setConversation:(id)arg0;

@end
