// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

@protocol FindMyLocate.LocationServiceClientXPC

// required
- (void)locationsForHandles:(id)arg0 completion:(id)arg1;
- (void)locationsUnavailableFor:(id)arg0 completion:(id)arg1;

@end
