// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/FindMyDevice.framework/Versions/A/FindMyDevice
@interface FMDSharedConfiguration : NSObject

@property (readonly, nonatomic) NSString *localeString;

+ (id)localizedStringWithKey:(id)arg0;
+ (id)sharedInstance;

- (id)_createAwarenessStringsDictionaryWithData:(id)arg0 key:(id)arg1 deviceClasses:(id)arg2;
- (id)_createFollowUpStringsDictionaryWithData:(id)arg0 key:(id)arg1 deviceClasses:(id)arg2;
- (id)contentsWithLocale:(id)arg0;
- (id)defaultEntryForConfiguration:(id)arg0 deviceClasses:(id)arg1;
- (id)entryForConfiguration:(id)arg0 deviceClasses:(id)arg1 locale:(id)arg2;
- (id)entryForConfiguration:(id)arg0 deviceClasses:(id)arg1;
- (id)expiryDateWithContents:(id)arg0;
- (id)fileURLWithLocale:(id)arg0;
- (id)localeString;
- (id)sharedConfigurationDictionaryFromData:(id)arg0 key:(id)arg1 deviceClasses:(id)arg2;
- (void)downloadWithLocale:(id)arg0 reply:(id /* block */)arg1;
- (void)downloadWithReply:(id /* block */)arg0;
- (void)forceDownloadWithLocale:(id)arg0 reply:(id /* block */)arg1;
- (void)forceDownloadWithReply:(id /* block */)arg0;
- (void)getTheftAndLossCoverageWithSerialNumber:(id)arg0 reply:(id /* block */)arg1;

@end
