// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/FMF.framework/Versions/A/FMF
@interface FMFFriendshipRequest : NSObject <NSCopying, NSSecureCoding>

@property (assign) long long requestType;
@property (retain) FMFHandle *fromHandle;
@property (retain) NSDate *endDate;
@property (retain) NSSet *toHandles;
@property (retain) NSString *groupId;
@property (retain) NSString *requestId;

+ (bool)supportsSecureCoding;
+ (id)friendshipRequestToHandles:(id)arg0 fromHandle:(id)arg1 withType:(long long)arg2 groupId:(id)arg3 withEndDate:(id)arg4;

- (id)copyWithZone:(_NSZone *)arg0;
- (id)description;
- (id)endDate;
- (id)fromHandle;
- (id)groupId;
- (id)initWithCoder:(id)arg0;
- (id)initWithFromHandle:(id)arg0 toHandle:(id)arg1 ofType:(long long)arg2 groupId:(id)arg3 endDate:(id)arg4 requestId:(id)arg5;
- (id)requestId;
- (id)toHandles;
- (long long)requestType;
- (void)encodeWithCoder:(id)arg0;
- (void)setEndDate:(id)arg0;
- (void)setFromHandle:(id)arg0;
- (void)setGroupId:(id)arg0;
- (void)setRequestId:(id)arg0;
- (void)setRequestType:(long long)arg0;
- (void)setToHandles:(id)arg0;

@end
