// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/FMF.framework/Versions/A/FMF
@interface FMFFence : NSObject <NSCopying, NSSecureCoding>

@property (nonatomic) bool active;
@property (nonatomic) bool fromMe;
@property (nonatomic) bool recurring;
@property (nonatomic) unsigned long long locationType;
@property (readonly) bool supported;
@property (readonly, nonatomic) NSDate *inviteDate;
@property (readonly, nonatomic) NSString *displayLocationName;
@property (readonly, nonatomic) bool isMuted;
@property (readonly, nonatomic) bool onMe;
@property (readonly, nonatomic) bool regionAllowed;
@property (readonly, nonatomic) bool useCloudKitStore;
@property (readonly, nonatomic) bool useIDSTrigger;
@property (retain, nonatomic) CLLocation *location;
@property (retain, nonatomic) FMFPlacemark *placemark;
@property (retain, nonatomic) FMFSchedule *schedule;
@property (retain, nonatomic) NSArray *followerIds;
@property (retain, nonatomic) NSArray *recipients;
@property (retain, nonatomic) NSDate *muteEndDate;
@property (retain, nonatomic) NSDate *timestamp;
@property (retain, nonatomic) NSString *acceptanceStatus;
@property (retain, nonatomic) NSString *ckRecordName;
@property (retain, nonatomic) NSString *ckRecordZoneOwnerName;
@property (retain, nonatomic) NSString *createdByIdentifier;
@property (retain, nonatomic) NSString *friendIdentifier;
@property (retain, nonatomic) NSString *identifier;
@property (retain, nonatomic) NSString *label;
@property (retain, nonatomic) NSString *pendingIdentifier;
@property (retain, nonatomic) NSString *trigger;
@property (retain, nonatomic) NSString *type;

+ (bool)isAllowedAtLocation:(CLLocationCoordinate2D)arg0;
+ (bool)supportsSecureCoding;
+ (id)endDateForMuteTimespan:(unsigned long long)arg0;
+ (id)genericFriendName;

- (bool)isActive;
- (bool)isEqual:(id)arg0;
- (bool)isFromMe;
- (bool)isMuted;
- (bool)isOnMe;
- (bool)isRecurring;
- (bool)isRegionAllowed;
- (bool)isSupported;
- (bool)shouldUseCloudKitStore;
- (bool)shouldUseIDSTrigger;
- (id)acceptanceStatus;
- (id)ckRecordName;
- (id)ckRecordZoneOwnerName;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)createdByIdentifier;
- (id)description;
- (id)displayLocationName;
- (id)followerIds;
- (id)friendIdentifier;
- (id)handlesForArray:(id)arg0;
- (id)identifier;
- (id)initWithCoder:(id)arg0;
- (id)initWithDictionary:(id)arg0;
- (id)initWithRecipient:(id)arg0 location:(id)arg1 placemark:(id)arg2 label:(id)arg3 trigger:(id)arg4 type:(id)arg5 locationType:(unsigned long long)arg6 recurring:(bool)arg7;
- (id)inviteDate;
- (id)label;
- (id)localizedNotificationStringForFollower:(id)arg0 locationName:(id)arg1;
- (id)localizedRequestNotificationStringForFollower:(id)arg0 locationName:(id)arg1;
- (id)localizedSubtitleStringWithLocationName:(id)arg0;
- (id)localizedWillBeNotifiedStringForFollower:(id)arg0 locationName:(id)arg1;
- (id)location;
- (id)locationForDictionary:(id)arg0;
- (id)muteEndDate;
- (id)pendingIdentifier;
- (id)placemark;
- (id)recipients;
- (id)schedule;
- (id)timestamp;
- (id)trigger;
- (id)type;
- (unsigned long long)hash;
- (unsigned long long)locationType;
- (void)encodeWithCoder:(id)arg0;
- (void)setAcceptanceStatus:(id)arg0;
- (void)setActive:(bool)arg0;
- (void)setCkRecordName:(id)arg0;
- (void)setCkRecordZoneOwnerName:(id)arg0;
- (void)setCreatedByIdentifier:(id)arg0;
- (void)setFollowerIds:(id)arg0;
- (void)setFriendIdentifier:(id)arg0;
- (void)setFromMe:(bool)arg0;
- (void)setIdentifier:(id)arg0;
- (void)setLabel:(id)arg0;
- (void)setLocation:(id)arg0;
- (void)setLocationType:(unsigned long long)arg0;
- (void)setMuteEndDate:(id)arg0;
- (void)setPendingIdentifier:(id)arg0;
- (void)setPlacemark:(id)arg0;
- (void)setRecipients:(id)arg0;
- (void)setRecurring:(bool)arg0;
- (void)setSchedule:(id)arg0;
- (void)setTimestamp:(id)arg0;
- (void)setTrigger:(id)arg0;
- (void)setType:(id)arg0;
- (void)updateFenceLocation:(id)arg0 placemark:(id)arg1 label:(id)arg2 trigger:(id)arg3 type:(id)arg4 locationType:(unsigned long long)arg5;
- (void)updateFenceMuteEndDate:(id)arg0;

@end
