// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/FMF.framework/Versions/A/FMF
@interface FMFSchedule : NSObject <NSSecureCoding, NSCopying>

@property (nonatomic) long long daysOfWeek;
@property (nonatomic) unsigned long long endHour;
@property (nonatomic) unsigned long long endMin;
@property (nonatomic) unsigned long long spanDays;
@property (nonatomic) unsigned long long startHour;
@property (nonatomic) unsigned long long startMin;
@property (readonly) NSString *validityError;
@property (readonly, nonatomic) NSCalendar *_gregorian;
@property (readonly, nonatomic) NSDictionary *dictionary;
@property (readonly, nonatomic) NSString *localizedDaysOfWeekString;
@property (readonly, nonatomic) NSString *localizedEndTimeString;
@property (readonly, nonatomic) NSString *localizedStartTimeString;
@property (retain, nonatomic) NSTimeZone *timeZone;

+ (bool)supportsSecureCoding;
+ (id)_dateFromHour:(unsigned long long)arg0 andMinute:(unsigned long long)arg1;
+ (id)_dayStringForDayOfWeek:(long long)arg0;
+ (id)_stringForDaysOfWeek:(long long)arg0;
+ (id)firstDateFromDates:(id)arg0 order:(long long)arg1;
+ (id)localizedDaysOfWeekStringFor:(long long)arg0;
+ (id)localizedTimeStringForHour:(unsigned long long)arg0 andMinute:(unsigned long long)arg1 timeStyle:(unsigned long long)arg2;
+ (id)localizedTimeStringForHour:(unsigned long long)arg0 andMinute:(unsigned long long)arg1;
+ (void)_enumerateDaysOfWeekInFMFDaysOfWeek:(long long)arg0 callback:(id /* block */)arg1;

- (bool)isCurrentAt:(id)arg0;
- (bool)isEqual:(id)arg0;
- (id)_daysOfWeek;
- (id)_endDateForStartDate:(id)arg0;
- (id)_gregorian;
- (id)_nextStartDateOnDayOfWeek:(long long)arg0 from:(id)arg1 options:(unsigned long long)arg2;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)description;
- (id)dictionary;
- (id)initWithCoder:(id)arg0;
- (id)initWithDictionary:(id)arg0;
- (id)localizedDaysOfWeekString;
- (id)localizedEndTimeString;
- (id)localizedStartTimeString;
- (id)nextStartDateFrom:(id)arg0 options:(unsigned long long)arg1;
- (id)nextStartOrEndDateFrom:(id)arg0;
- (id)previousStartDateFrom:(id)arg0;
- (id)timeZone;
- (id)validityError;
- (long long)daysOfWeek;
- (unsigned long long)endHour;
- (unsigned long long)endMin;
- (unsigned long long)hash;
- (unsigned long long)spanDays;
- (unsigned long long)startHour;
- (unsigned long long)startMin;
- (void)encodeWithCoder:(id)arg0;
- (void)setDaysOfWeek:(long long)arg0;
- (void)setEndHour:(unsigned long long)arg0;
- (void)setEndMin:(unsigned long long)arg0;
- (void)setSpanDays:(unsigned long long)arg0;
- (void)setStartHour:(unsigned long long)arg0;
- (void)setStartMin:(unsigned long long)arg0;
- (void)setTimeZone:(id)arg0;

@end
