// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/FindMyLocateObjCWrapper.framework/Versions/A/FindMyLocateObjCWrapper
@interface FMLDevice : NSObject

@property (assign) bool isActive;
@property (assign) bool isAutoMeCapable;
@property (assign) bool isCompanion;
@property (assign) bool isThisDevice;
@property (copy) NSString *deviceName;
@property (copy) NSString *identifier;
@property (copy) NSString *idsDeviceId;

- (bool)isActive;
- (bool)isAutoMeCapable;
- (bool)isCompanion;
- (bool)isEqual:(id)arg0;
- (bool)isThisDevice;
- (id)comparisonIdentifier;
- (id)debugDescription;
- (id)description;
- (id)deviceName;
- (id)identifier;
- (id)idsDeviceId;
- (id)initWithIdentifier:(id)arg0 deviceName:(id)arg1 idsDeviceId:(id)arg2 isActive:(bool)arg3 isThisDevice:(bool)arg4 isCompanion:(bool)arg5 isAutoMeCapable:(bool)arg6;
- (unsigned long long)hash;
- (void)setDeviceName:(id)arg0;
- (void)setIdentifier:(id)arg0;
- (void)setIdsDeviceId:(id)arg0;
- (void)setIsActive:(bool)arg0;
- (void)setIsAutoMeCapable:(bool)arg0;
- (void)setIsCompanion:(bool)arg0;
- (void)setIsThisDevice:(bool)arg0;

@end
