// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/FindMyLocateObjCWrapper.framework/Versions/A/FindMyLocateObjCWrapper
@interface FMLHandle : NSObject

@property (copy) NSString *identifier;

+ (id)handleWithIdentifier:(id)arg0;

- (bool)isEqual:(id)arg0;
- (id)comparisonIdentifier;
- (id)debugDescription;
- (id)description;
- (id)identifier;
- (unsigned long long)hash;
- (void)setIdentifier:(id)arg0;

@end
