// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/NotesShared.framework/Versions/A/NotesShared
@interface ICNoteContainer : ICCloudSyncingObject <ICNoteContainer>

@property (copy, nonatomic) NSData *subFolderOrderMergeableData;
@property (nonatomic) bool isHiddenNoteContainer;
@property (nonatomic) bool subFolderOrderMergeableDataDirty;
@property (nonatomic) int sortOrder;
@property (nonatomic) long long dateHeadersType;
@property (readonly) Class superclass;
@property (readonly) NSManagedObjectContext *managedObjectContext;
@property (readonly) unsigned long long hash;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, copy, nonatomic) NSString *accountName;
@property (readonly, copy, nonatomic) NSString *cacheKey;
@property (readonly, copy, nonatomic) NSString *titleForNavigationBar;
@property (readonly, copy, nonatomic) NSString *titleForTableViewCell;
@property (readonly, nonatomic) ICAccount *noteContainerAccount;
@property (readonly, nonatomic) ICCROrderedSet *subFolderIdentifiersOrderedSet;
@property (readonly, nonatomic) ICFolderCustomNoteSortType *customNoteSortType;
@property (readonly, nonatomic) NSArray *visibleNotes;
@property (readonly, nonatomic) NSArray *visibleSubFolders;
@property (readonly, nonatomic) NSString *containerIdentifier;
@property (readonly, nonatomic) bool canBeSharedViaICloud;
@property (readonly, nonatomic) bool deleted;
@property (readonly, nonatomic) bool isAllNotesContainer;
@property (readonly, nonatomic) bool isModernCustomFolder;
@property (readonly, nonatomic) bool isSharedReadOnly;
@property (readonly, nonatomic) bool isSharedViaICloud;
@property (readonly, nonatomic) bool isShowingDateHeaders;
@property (readonly, nonatomic) bool isTrashFolder;
@property (readonly, nonatomic) bool supportsDateHeaders;
@property (readonly, nonatomic) bool supportsEditingNotes;
@property (readonly, nonatomic) unsigned long long visibleNotesCount;
@property (retain, nonatomic) ICAccount *owner;
@property (retain, nonatomic) ICTTOrderedSetVersionedDocument *subFolderIdentifiersOrderedSetDocument;
@property (retain, nonatomic) NSString *accountNameForAccountListSorting;
@property (retain, nonatomic) NSString *nestedTitleForSorting;

+ (id)keyPathsForValuesAffectingCloudAccount;

- (bool)canBeSharedViaICloud;
- (bool)isAllNotesContainer;
- (bool)isModernCustomFolder;
- (bool)isSharedReadOnly;
- (bool)isSharedViaICloud;
- (bool)isShowingDateHeaders;
- (bool)isSubFolderOrderMergeableDataDirty;
- (bool)isTrashFolder;
- (bool)mergeWithSubFolderMergeableData:(id)arg0;
- (bool)noteIsVisible:(id)arg0;
- (bool)supportsDateHeaders;
- (bool)supportsEditingNotes;
- (bool)supportsVisibilityTestingType:(long long)arg0;
- (id)accountName;
- (id)cacheKey;
- (id)cloudAccount;
- (id)containerIdentifier;
- (id)customNoteSortType;
- (id)noteContainerAccount;
- (id)noteVisibilityTestingForSearchingAccount;
- (id)predicateForPinnedNotes;
- (id)predicateForSearchableAttachments;
- (id)predicateForSearchableNotes;
- (id)predicateForVisibleNotes;
- (id)subFolderIdentifiersOrderedSet;
- (id)subFolderIdentifiersOrderedSetDocument;
- (id)subFolderOrderMergeableData;
- (id)titleForNavigationBar;
- (id)titleForTableViewCell;
- (id)visibleNotes;
- (id)visibleSubFolders;
- (unsigned long long)visibleNotesCount;
- (void)applyDateHeadersType:(long long)arg0;
- (void)saveSubFolderMergeableDataIfNeeded;
- (void)setSubFolderIdentifiersOrderedSetDocument:(id)arg0;
- (void)setSubFolderOrderMergeableData:(id)arg0;
- (void)setSubFolderOrderMergeableDataDirty:(bool)arg0;
- (void)updateSubFolderMergeableDataChangeCount;
- (void)willRefresh:(bool)arg0;
- (void)willSave;
- (void)willTurnIntoFault;
- (void)writeSubFolderMergeableData;

@end
