// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/NotesShared.framework/Versions/A/NotesShared
@interface ICNoteData : NSManagedObject

@property (nonatomic) bool didBlockLastSave;
@property (nonatomic) bool needsToBeSaved;
@property (nonatomic) bool settingNoteData;
@property (readonly, nonatomic) NSData *primitiveData;
@property (retain, nonatomic) ICNote *note;
@property (retain, nonatomic) NSData *cryptoInitializationVector;
@property (retain, nonatomic) NSData *cryptoTag;
@property (retain, nonatomic) NSData *data;

- (bool)didBlockLastSave;
- (bool)isSettingNoteData;
- (bool)needsToBeSaved;
- (bool)saveNoteDataIfNeeded;
- (void)setCryptoInitializationVector:(id)arg0;
- (void)setCryptoTag:(id)arg0;
- (void)setDidBlockLastSave:(bool)arg0;
- (void)setNeedsToBeSaved:(bool)arg0;
- (void)setSettingNoteData:(bool)arg0;
- (void)willAccessValueForKey:(id)arg0;
- (void)willSave;

@end
