// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMChatHistoryController : NSObject

@property (retain) NSMutableDictionary *_runningQueries;

+ (id)sharedInstance;

- (id)_runningQueries;
- (id)init;
- (void)dealloc;
- (void)itemQuery:(id)arg0 finishedWithResult:(id)arg1 chatGUIDs:(id)arg2;
- (void)loadItemWithGUID:(id)arg0 completionBlock:(id /* block */)arg1;
- (void)loadMessageItemWithGUID:(id)arg0 completionBlock:(id /* block */)arg1;
- (void)loadMessageWithGUID:(id)arg0 completionBlock:(id /* block */)arg1;
- (void)messageItemQuery:(id)arg0 finishedWithResult:(id)arg1 chatGUIDs:(id)arg2;
- (void)messageQuery:(id)arg0 finishedWithResult:(id)arg1 chatGUIDs:(id)arg2;
- (void)set_runningQueries:(id)arg0;

@end
