// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMChatInfo : NSObject <NSCopying>

@property (nonatomic) bool downloadingPendingSatelliteMessages;
@property (nonatomic) bool hasCancellableScheduledMessage;
@property (nonatomic) long long isFiltered;
@property (nonatomic) unsigned long long pendingIncomingSatelliteMessageCount;
@property (nonatomic) unsigned long long unreadMessageCount;
@property (retain, nonatomic) NSDictionary *pendingGroupModification;
@property (retain, nonatomic) NSDictionary *transcriptBackgroundDetails;
@property (retain, nonatomic) NSString *chatIdentifier;
@property (retain, nonatomic) NSString *lastAddressedLocalHandle;
@property (retain, nonatomic) NSString *lastAddressedSIMID;
@property (retain, nonatomic) NSString *transcriptBackgroundChannelTransferGUID;

- (bool)downloadingPendingSatelliteMessages;
- (bool)hasCancellableScheduledMessage;
- (id)chatIdentifier;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)initWithChatDictionary:(id)arg0;
- (id)lastAddressedLocalHandle;
- (id)lastAddressedSIMID;
- (id)pendingGroupModification;
- (id)transcriptBackgroundChannelTransferGUID;
- (id)transcriptBackgroundDetails;
- (long long)isFiltered;
- (unsigned long long)pendingIncomingSatelliteMessageCount;
- (unsigned long long)unreadMessageCount;
- (void)setChatIdentifier:(id)arg0;
- (void)setDownloadingPendingSatelliteMessages:(bool)arg0;
- (void)setHasCancellableScheduledMessage:(bool)arg0;
- (void)setIsFiltered:(long long)arg0;
- (void)setLastAddressedLocalHandle:(id)arg0;
- (void)setLastAddressedSIMID:(id)arg0;
- (void)setPendingGroupModification:(id)arg0;
- (void)setPendingIncomingSatelliteMessageCount:(unsigned long long)arg0;
- (void)setTranscriptBackgroundChannelTransferGUID:(id)arg0;
- (void)setTranscriptBackgroundDetails:(id)arg0;
- (void)setUnreadMessageCount:(unsigned long long)arg0;
- (void)updateWithChatDictionary:(id)arg0 isPartialUpdate:(bool)arg1;

@end
