// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMDaemonListener : NSObject <IMDaemonListening_Internal, IMDaemonListening>

@property (nonatomic) bool _hidingDisconnect;
@property (readonly) Class superclass;
@property (readonly) unsigned long long hash;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic) NSArray *allServices;
@property (readonly, nonatomic) NSDictionary *persistentProperties;
@property (readonly, nonatomic) NSDictionary *properties;
@property (readonly, nonatomic) NSMutableDictionary *_contexts;
@property (readonly, nonatomic) NSString *myStatusMessage;
@property (readonly, nonatomic) bool hasPostedSetupComplete;
@property (readonly, nonatomic) bool holdingChatMessages;
@property (readonly, nonatomic) bool setupComplete;
@property (readonly, nonatomic) bool shouldHoldChatMessages;
@property (readonly, nonatomic) unsigned int myIdleTime;
@property (readonly, nonatomic) unsigned long long myStatus;
@property (readonly, nonatomic) unsigned long long vcCapabilities;

- (bool)_hidingDisconnect;
- (bool)hasPostedSetupComplete;
- (bool)isHoldingChatMessages;
- (bool)isSetupComplete;
- (bool)shouldHoldChatMessages;
- (id)_contexts;
- (id)_stampForContext:(id)arg0;
- (id)allServices;
- (id)myStatusMessage;
- (id)persistentProperties;
- (id)properties;
- (id)serviceWithName:(id)arg0;
- (id)valueOfPersistentProperty:(id)arg0;
- (id)valueOfProperty:(id)arg0;
- (unsigned int)myIdleTime;
- (unsigned long long)myStatus;
- (unsigned long long)vcCapabilities;
- (void)_noteDisconnected;
- (void)_resetPostedSetupCompleted;
- (void)_setHidingDisconnect:(bool)arg0;
- (void)_setStamp:(id)arg0 forContext:(id)arg1;
- (void)addHandler:(id)arg0;
- (void)holdChatMessages;
- (void)releaseHeldChatMessages;
- (void)removeHandler:(id)arg0;

@end
