// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

@protocol IMDaemonAnyProtocol

// required
- (void)acceptPendingNicknameForHandleID:(id)arg0 updateType:(id)arg1;
- (void)allowHandleIDsForNicknameSharing:(id)arg0 onChatGUIDs:(id)arg1 fromHandle:(id)arg2 forceSend:(id)arg3;
- (void)askHandleIDToShareTheirScreen:(id)arg0 isContact:(id)arg1;
- (void)clearPendingNicknamePhotoUpdateForHandleIDs:(id)arg0;
- (void)clearPendingNicknameUpdatesForHandleIDs:(id)arg0;
- (void)conference:(id)arg0 account:(id)arg1 notifyInvitationCancelledFromPerson:(id)arg2;
- (void)consumeCodeWithMessageGUID:(id)arg0;
- (void)denyHandleIDsForNicknameSharing:(id)arg0;
- (void)downloadPurgedAttachmentsForIDs:(id)arg0 style:(id)arg1 onServices:(id)arg2 chatID:(id)arg3;
- (void)downloadStickerPackWithGUID:(id)arg0 isIncomingMessage:(id)arg1 ignoreCache:(id)arg2;
- (void)downloadStickerWithGUID:(id)arg0;
- (void)eagerUploadCancel:(id)arg0;
- (void)eagerUploadTransfer:(id)arg0 recipients:(id)arg1;
- (void)fetchActiveNicknamesWithReply:(id)arg0;
- (void)fetchAutoDeletionPreferenceWithReply:(id)arg0;
- (void)fetchGroupPhotoPathsForChatsWithGroupIDs:(id)arg0 completionHandler:(id)arg1;
- (void)fetchHandleSharingStateWithReply:(id)arg0;
- (void)fetchIgnoredNicknameHandlesWithReply:(id)arg0;
- (void)fetchNicknamesWithReply:(id)arg0;
- (void)fetchPersonalNicknameWithReply:(id)arg0;
- (void)fetchTransitionedNicknameHandlesWithReply:(id)arg0;
- (void)fetchUnknownSenderRecordsWithReply:(id)arg0;
- (void)forceReloadChatRegistryWithQueryID:(id)arg0;
- (void)holdBuddyUpdatesAccount:(id)arg0;
- (void)ignorePendingNicknameUpdatesForHandleIDs:(id)arg0;
- (void)initiateQuickSwitch;
- (void)inviteHandleIDToShareMyScreen:(id)arg0 isContact:(id)arg1;
- (void)markAllNicknamesAsPending;
- (void)markMessageAsNeedingFileTransferGUIDRepairWithGUID:(id)arg0;
- (void)markMessageAsReadWithGUID:(id)arg0 callerOrigin:(id)arg1 reply:(id)arg2;
- (void)markNicknamesAsTransitionedForHandleIDs:(id)arg0 isAutoUpdate:(id)arg1;
- (void)markPlayedForIDs:(id)arg0 style:(id)arg1 onServices:(id)arg2 message:(id)arg3;
- (void)markPlayedForMessageGUID:(id)arg0;
- (void)markProfileRecords:(id)arg0 asActive:(id)arg1;
- (void)markProfileRecordsAsIgnored:(id)arg0;
- (void)markReadForMessageGUID:(id)arg0 callerOrigin:(id)arg1 queryID:(id)arg2;
- (void)markUnreadForMessageGUID:(id)arg0 IDs:(id)arg1 style:(id)arg2 services:(id)arg3;
- (void)nicknamePreferencesDidChange;
- (void)onboardDeleteVerificationCodesIfNeededWithMessage:(id)arg0 reply:(id)arg1;
- (void)onboardDeleteVerificationCodesIfNeededWithReply:(id)arg0;
- (void)playSendSoundForMessageGUID:(id)arg0 callerOrigin:(id)arg1;
- (void)preWarm;
- (void)requestBuddyPicturesAndPropertiesForAccount:(id)arg0;
- (void)requestGroupsAccount:(id)arg0;
- (void)requestNetworkDataAvailability;
- (void)requestOneTimeCodeStatus;
- (void)requestPendingACInvites;
- (void)requestPendingVCInvites;
- (void)requestPersistenceServiceEndpointWithReply:(id)arg0;
- (void)requestProperty:(id)arg0 ofPerson:(id)arg1 account:(id)arg2;
- (void)requestQOSClassWhileServicingRequestsWithID:(id)arg0;
- (void)requestSetupWithClientID:(id)arg0 capabilities:(id)arg1 context:(id)arg2 reply:(id)arg3;
- (void)requestSetupXPCObjectWithClientID:(id)arg0 capabilities:(id)arg1 context:(id)arg2 reply:(id)arg3;
- (void)resumeBuddyUpdatesAccount:(id)arg0;
- (void)sendClearNotice:(id)arg0 toHandles:(id)arg1 reply:(id)arg2;
- (void)sendNameOnlyToHandleIDs:(id)arg0 fromHandleID:(id)arg1;
- (void)sendNotice:(id)arg0 toHandles:(id)arg1 fromHandle:(id)arg2 reply:(id)arg3;
- (void)sendNotificationMessageToUniqueID:(id)arg0 withCommand:(id)arg1;
- (void)setAutoDeletionPreference:(id)arg0;
- (void)setNewPersonalNickname:(id)arg0;
- (void)setValue:(id)arg0 ofPersistentProperty:(id)arg1;
- (void)setValue:(id)arg0 ofProperty:(id)arg1 ofPerson:(id)arg2 account:(id)arg3;
- (void)setValue:(id)arg0 ofProperty:(id)arg1;
- (void)simulateOneTimeCodeArriving:(id)arg0;
- (void)startWatchingBuddy:(id)arg0 account:(id)arg1;
- (void)stopWatchingBuddy:(id)arg0 account:(id)arg1;
- (void)terminateForcingIfNeeded:(id)arg0;

@end
