// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMSharedUtilities.framework/Versions/A/IMSharedUtilities
@interface IMEmojiTapback : IMTapback

@property (nonatomic, readonly) IMEmojiTapback *counterpart;
@property (nonatomic, readonly) IMEmojiTapback *removedTapbackCounterpart;
@property (nonatomic, readonly) IMEmojiTapback *visibleTapbackCounterpart;
@property (nonatomic, readonly) NSString *associatedMessageEmoji;
@property (nonatomic, readonly) NSString *description;

+ (bool)isValidAssociatedMessageType:(long long)arg0;

- (bool)isEqual:(id)arg0;
- (bool)isEqualIgnoringModifiersToEmojiTapback:(id)arg0;
- (id)actionStringFormatWithAdaptiveImageGlyphAvailable:(bool)arg0;
- (id)associatedMessageEmoji;
- (id)counterpart;
- (id)description;
- (id)initWithAssociatedMessageType:(long long)arg0;
- (id)initWithCoder:(id)arg0;
- (id)initWithEmoji:(id)arg0 isRemoved:(bool)arg1;
- (id)initWithIMRemoteObjectSerializedDictionary:(id)arg0;
- (id)messageForChat:(id)arg0 messageGUID:(id)arg1 messagePartRange:(_NSRange)arg2 messageSummaryInfo:(id)arg3 threadIdentifier:(id)arg4;
- (id)reactionStringWithAdaptiveImageGlyph:(id)arg0 isCommSafetySensitiveProvider:(id /* block */)arg1;
- (id)removedTapbackCounterpart;
- (id)visibleTapbackCounterpart;

@end
