// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMHandleAvailabilityManager : NSObject <SKStatusSubscriptionServiceDelegate>

@property (nonatomic) long long currentCacheGeneration;
@property (readonly) Class superclass;
@property (readonly) unsigned long long hash;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (retain, nonatomic) NSMutableDictionary *currentSubscriptionCache;
@property (retain, nonatomic) NSMutableDictionary *lastKnownSubscriptionCache;
@property (retain, nonatomic) NSMutableSet *pendingFetchesForCacheKeys;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *privateWorkQueue;
@property (retain, nonatomic) SKStatusSubscriptionService *subscriptionService;

+ (id)sharedInstance;

- (id)_cachedStatusSubscriptionForIMHandle:(id)arg0 fromCache:(id)arg1 cacheDescription:(id)arg2 cacheMiss:(bool *)arg3;
- (id)_skHandleForIMHandle:(id)arg0;
- (id)_skHandleForString:(id)arg0;
- (id)_subscriptionCacheKeyForHandle:(id)arg0;
- (id)availabilityStatusPublishedDateForHandle:(id)arg0;
- (id)currentSubscriptionCache;
- (id)init;
- (id)lastKnownSubscriptionCache;
- (id)pendingFetchesForCacheKeys;
- (id)privateWorkQueue;
- (id)statusSubscriptionForHandle:(id)arg0;
- (id)subscriptionService;
- (long long)_availablityFromStatusSubscription:(id)arg0 handleID:(id)arg1;
- (long long)availabilityForHandle:(id)arg0;
- (long long)currentCacheGeneration;
- (void)_clearCurrentSubscriptionCache;
- (void)_postNotificationForUpdatedStatusWithSubscription:(id)arg0;
- (void)beginObservingAvailabilityForHandle:(id)arg0;
- (void)endObservingAvailabilityForHandle:(id)arg0;
- (void)fetchPersonalAvailabilityWithCompletion:(id /* block */)arg0;
- (void)fetchUpdatedStatusAndUpdateCachesForHandle:(id)arg0 lastKnownStatus:(id)arg1;
- (void)fetchUpdatedStatusForHandle:(id)arg0 completion:(id /* block */)arg1;
- (void)setCurrentCacheGeneration:(long long)arg0;
- (void)setCurrentSubscriptionCache:(id)arg0;
- (void)setLastKnownSubscriptionCache:(id)arg0;
- (void)setPendingFetchesForCacheKeys:(id)arg0;
- (void)setPrivateWorkQueue:(id)arg0;
- (void)setSubscriptionService:(id)arg0;
- (void)subscriptionInvitationReceived:(id)arg0;
- (void)subscriptionReceivedStatusUpdate:(id)arg0;
- (void)subscriptionServiceDaemonDisconnected:(id)arg0;
- (void)subscriptionStateChanged:(id)arg0;

@end
