// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMMessageAcknowledgmentChatItem : IMAssociatedMessageChatItem

@property (readonly, copy, nonatomic) IMMessage *message;
@property (readonly, copy, nonatomic) NSArray *fileTransferGUIDs;

- (Class)__ck_chatItemClass;
- (bool)containsTransferGUID:(id)arg0;
- (bool)isEqualToTapback:(id)arg0;
- (bool)supportsCommunicationSafety;
- (id)_initWithItem:(id)arg0 sender:(id)arg1 tapback:(id)arg2;
- (id)commSafetyTransferGUID;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)fileTransferGUIDs;
- (id)message;

@end
