// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMSharedUtilities.framework/Versions/A/IMSharedUtilities
@interface IMNickname : NSObject <NSCopying, NSSecureCoding>

@property (copy, nonatomic) NSDate *archivedDate;
@property (copy, nonatomic) NSString *firstName;
@property (copy, nonatomic) NSString *lastName;
@property (nonatomic, readonly) bool hasObservedTransition;
@property (nonatomic, readonly) bool isActive;
@property (nonatomic, readonly) bool isIgnored;
@property (readonly, nonatomic) NSData *imageHash;
@property (readonly, nonatomic) NSData *wallpaperImageHash;
@property (readonly, nonatomic) NSData *wallpaperLowResImageHash;
@property (readonly, nonatomic) NSString *concatenatedImageHash;
@property (readonly, nonatomic) NSString *nameHash;
@property (retain, nonatomic) IMNicknameAvatarImage *avatar;
@property (retain, nonatomic) IMNicknameAvatarRecipe *avatarRecipe;
@property (retain, nonatomic) IMWallpaper *wallpaper;
@property (retain, nonatomic) NSDictionary *preBlastDoorPayloadData;
@property (retain, nonatomic) NSString *displayName;
@property (retain, nonatomic) NSString *handle;
@property (retain, nonatomic) NSString *recordID;
@property (retain, nonatomic) _NSAttributedStringGrammarInflection *pronouns;

+ (bool)supportsSecureCoding;
+ (id)nameHashWithFirstName:(id)arg0 lastName:(id)arg1;
+ (id)processSetOfUnknownSenderRecords:(id)arg0;
+ (id)uniqueFilePathForWritingImageData;
+ (id)uniqueFilePathForWritingWallpaperData;

- (bool)hasObservedTransition;
- (bool)isActive;
- (bool)isEqual:(id)arg0;
- (bool)isEqualToNickname:(id)arg0 options:(unsigned long long)arg1;
- (bool)isIgnored;
- (bool)isUpdateFromNickname:(id)arg0 withOptions:(unsigned long long)arg1;
- (id)_imageHashCreatedInChunks:(id)arg0;
- (id)_sharingState;
- (id)archivedDate;
- (id)avatar;
- (id)avatarRecipe;
- (id)concatenatedImageHash;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)dataRepresentation;
- (id)description;
- (id)dictionaryRepresentation;
- (id)displayName;
- (id)firstName;
- (id)handle;
- (id)imageHash;
- (id)init;
- (id)initWithCoder:(id)arg0;
- (id)initWithDictionaryRepresentation:(id)arg0;
- (id)initWithFirstName:(id)arg0 lastName:(id)arg1 avatar:(id)arg2 pronouns:(id)arg3 wallpaper:(id)arg4 avatarRecipe:(id)arg5;
- (id)initWithFirstName:(id)arg0 lastName:(id)arg1 avatar:(id)arg2 pronouns:(id)arg3 wallpaper:(id)arg4;
- (id)initWithFirstName:(id)arg0 lastName:(id)arg1 avatar:(id)arg2 pronouns:(id)arg3;
- (id)initWithMeContact:(id)arg0;
- (id)initWithPublicDictionaryRepresentationWithoutAvatar:(id)arg0;
- (id)lastName;
- (id)nameHash;
- (id)persistedDictionaryRepresentation;
- (id)preBlastDoorPayloadData;
- (id)pronouns;
- (id)publicDictionaryRepresentation;
- (id)publicDictionaryRepresentationWithoutAvatar;
- (id)recordID;
- (id)wallpaper;
- (id)wallpaperImageHash;
- (id)wallpaperLowResImageHash;
- (void)encodeWithCoder:(id)arg0;
- (void)setArchivedDate:(id)arg0;
- (void)setAvatar:(id)arg0;
- (void)setAvatarRecipe:(id)arg0;
- (void)setDisplayName:(id)arg0;
- (void)setFirstName:(id)arg0;
- (void)setHandle:(id)arg0;
- (void)setLastName:(id)arg0;
- (void)setPreBlastDoorPayloadData:(id)arg0;
- (void)setPronouns:(id)arg0;
- (void)setRecordID:(id)arg0;
- (void)setWallpaper:(id)arg0;
- (void)updateNameFromContact:(id)arg0;

@end
