// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMPollOption : NSObject

@property (nonatomic, readonly) NSAttributedString *attributedPollText;
@property (nonatomic, readonly) NSString *optionIdentifier;
@property (nonatomic, readonly) NSString *pollText;

- (id)attributedPollText;
- (id)init;
- (id)initWithOptionIdentifier:(id)arg0 pollText:(id)arg1 attributedPollText:(id)arg2;
- (id)optionIdentifier;
- (id)pollText;

@end
