// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMScheduledSectionDateChatItem : IMTranscriptChatItem

@property (readonly, nonatomic) NSDate *date;

- (Class)__ck_chatItemClass;
- (bool)isEqual:(id)arg0;
- (bool)isEqualToScheduledDateChatItem:(id)arg0;
- (id)date;
- (id)initWithItem:(id)arg0;
- (unsigned long long)hash;

@end
