// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMSharedUtilities.framework/Versions/A/IMSharedUtilities
@interface IMSticker : NSObject

@property (copy, nonatomic) NSAdaptiveImageGlyph *cachedAdaptiveImageGlyphForSkippingPreviewGenerationOnly;
@property (copy, nonatomic) NSArray *representations;
@property (copy, nonatomic) NSData *metadata;
@property (copy, nonatomic) NSDictionary *attributionInfo;
@property (copy, nonatomic) NSString *accessibilityLabel;
@property (copy, nonatomic) NSString *accessibilityName;
@property (copy, nonatomic) NSString *adaptiveImageGlyphContentDescription;
@property (copy, nonatomic) NSString *adaptiveImageGlyphContentIdentifier;
@property (copy, nonatomic) NSString *ballonBundleID;
@property (copy, nonatomic) NSString *externalURI;
@property (copy, nonatomic) NSString *moodCategory;
@property (copy, nonatomic) NSString *sanitizedPrompt;
@property (copy, nonatomic) NSString *searchText;
@property (copy, nonatomic) NSString *stickerName;
@property (copy, nonatomic) NSString *stickerPackGUID;
@property (copy, nonatomic) NSURL *animatedImageCacheURLFromExtension;
@property (copy, nonatomic) NSURL *fileURL;
@property (nonatomic) long long stickerEffectType;
@property (nonatomic) unsigned long long initialFrameIndex;
@property (readonly, copy, nonatomic) NSString *stickerGUID;
@property (readonly, copy, nonatomic) NSString *textToSpeechName;
@property (readonly, copy, nonatomic) UIImage *image;
@property (readonly, nonatomic) NSString *uniqueID;
@property (readonly, nonatomic) bool isEmojiSticker;
@property (retain, nonatomic) NSData *recipe;

+ (CGSize)calculatedRecentsItemWidthFromStickersUltraExtensionForStickerChatItem:(id)arg0 collectionViewWidth:(double)arg1;
+ (IMAssociatedMessageGeometryDescriptor)geometryDescriptorFromUserInfoDictionary:(id)arg0;
+ (bool)dragItemIsRepositioningSticker:(id)arg0;
+ (bool)dragItemIsSticker:(id)arg0;
+ (bool)dropSessionIsRepositioningSticker:(id)arg0;
+ (double)calculatePreviewScaleWithTargetSize:(CGSize)arg0 imageData:(id)arg1;
+ (id)saveAdaptiveImageGlyphToTemporaryFile:(id)arg0;
+ (id)stickerWithMSMessageMediaPayload:(id)arg0;
+ (id)userInfoDictionaryWithExternalURI:(id)arg0;
+ (id)userInfoDictionaryWithGeometryDescriptor:(IMAssociatedMessageGeometryDescriptor)arg0;
+ (id)userInfoDictionaryWithLayoutIntent:(unsigned long long)arg0 parentPreviewWidth:(double)arg1 xScalar:(double)arg2 yScalar:(double)arg3 scale:(double)arg4 rotation:(double)arg5 initialFrameIndex:(unsigned long long)arg6 externalURI:(id)arg7;
+ (id)userInfoDictionaryWithLayoutIntent:(unsigned long long)arg0 parentPreviewWidth:(double)arg1 xScalar:(double)arg2 yScalar:(double)arg3 scale:(double)arg4 rotation:(double)arg5 initialFrameIndex:(unsigned long long)arg6 stickerPositionVersion:(unsigned long long)arg7 externalURI:(id)arg8;

- (bool)isEmojiSticker;
- (bool)isEqual:(id)arg0;
- (bool)prepareToSend;
- (double)calculatePreviewScaleWithTargetSize:(CGSize)arg0;
- (id)accessibilityLabel;
- (id)accessibilityName;
- (id)adaptiveImageGlyphContentDescription;
- (id)adaptiveImageGlyphContentIdentifier;
- (id)animatedImageCacheURLFromExtension;
- (id)attributionInfo;
- (id)ballonBundleID;
- (id)cachedAdaptiveImageGlyphForSkippingPreviewGenerationOnly;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)description;
- (id)externalURI;
- (id)fileURL;
- (id)getSafeExternalURI;
- (id)image;
- (id)imageData;
- (id)init;
- (id)initWithAdaptiveImageGlyphFromUnknownSource:(id)arg0;
- (id)initWithStickerID:(id)arg0 stickerPackID:(id)arg1 fileURL:(id)arg2 accessibilityLabel:(id)arg3 accessibilityName:(id)arg4 moodCategory:(id)arg5 stickerName:(id)arg6 textToSpeechName:(id)arg7;
- (id)initWithStickerID:(id)arg0 stickerPackID:(id)arg1 fileURL:(id)arg2 accessibilityLabel:(id)arg3 accessibilityName:(id)arg4 moodCategory:(id)arg5 stickerName:(id)arg6;
- (id)initWithStickerID:(id)arg0 stickerPackID:(id)arg1 fileURL:(id)arg2 accessibilityLabel:(id)arg3 accessibilityName:(id)arg4 searchText:(id)arg5 sanitizedPrompt:(id)arg6 moodCategory:(id)arg7 stickerName:(id)arg8 effectType:(long long)arg9 textToSpeechName:(id)arg10;
- (id)initWithStickerID:(id)arg0 stickerPackID:(id)arg1 fileURL:(id)arg2 accessibilityLabel:(id)arg3 accessibilityName:(id)arg4 searchText:(id)arg5 sanitizedPrompt:(id)arg6 moodCategory:(id)arg7 stickerName:(id)arg8 effectType:(long long)arg9;
- (id)initWithStickerID:(id)arg0 stickerPackID:(id)arg1 fileURL:(id)arg2 accessibilityLabel:(id)arg3 accessibilityName:(id)arg4 searchText:(id)arg5 sanitizedPrompt:(id)arg6 moodCategory:(id)arg7 stickerName:(id)arg8 textToSpeechName:(id)arg9;
- (id)initWithStickerID:(id)arg0 stickerPackID:(id)arg1 fileURL:(id)arg2 accessibilityLabel:(id)arg3 accessibilityName:(id)arg4 searchText:(id)arg5 sanitizedPrompt:(id)arg6 moodCategory:(id)arg7 stickerName:(id)arg8;
- (id)initWithStickerIdentifier:(id)arg0 stickerPackID:(id)arg1 representations:(id)arg2 effectType:(long long)arg3 initialFrameIndex:(unsigned long long)arg4 externalURI:(id)arg5 stickerName:(id)arg6 accessibilityLabel:(id)arg7 accessibilityName:(id)arg8 searchText:(id)arg9 sanitizedPrompt:(id)arg10 metadata:(id)arg11;
- (id)initWithStickerPropertyDictionary:(id)arg0 stickerPackID:(id)arg1 stickerPackBundlePath:(id)arg2;
- (id)initWithUISticker:(id)arg0 adaptiveImageGlyph:(id)arg1;
- (id)metadata;
- (id)moodCategory;
- (id)recipe;
- (id)representations;
- (id)sanitizedPrompt;
- (id)searchText;
- (id)stickerEffectViewForStickerChatItem:(id)arg0;
- (id)stickerGUID;
- (id)stickerName;
- (id)stickerPackGUID;
- (id)textToSpeechName;
- (id)uiSticker;
- (id)uniqueID;
- (long long)stickerEffectType;
- (unsigned long long)hash;
- (unsigned long long)initialFrameIndex;
- (void)setAccessibilityLabel:(id)arg0;
- (void)setAccessibilityName:(id)arg0;
- (void)setAdaptiveImageGlyphContentDescription:(id)arg0;
- (void)setAdaptiveImageGlyphContentIdentifier:(id)arg0;
- (void)setAnimatedImageCacheURLFromExtension:(id)arg0;
- (void)setAttributionInfo:(id)arg0;
- (void)setBallonBundleID:(id)arg0;
- (void)setCachedAdaptiveImageGlyphForSkippingPreviewGenerationOnly:(id)arg0;
- (void)setExternalURI:(id)arg0;
- (void)setFileURL:(id)arg0;
- (void)setInitialFrameIndex:(unsigned long long)arg0;
- (void)setMetadata:(id)arg0;
- (void)setMoodCategory:(id)arg0;
- (void)setRecipe:(id)arg0;
- (void)setRepresentations:(id)arg0;
- (void)setSanitizedPrompt:(id)arg0;
- (void)setSearchText:(id)arg0;
- (void)setStickerEffectType:(long long)arg0;
- (void)setStickerName:(id)arg0;
- (void)setStickerPackGUID:(id)arg0;
- (void)stickerEffectViewSnapshotForStickerChatItem:(id)arg0 completion:(id /* block */)arg1;
- (void)stickerViewForStickerChatItem:(id)arg0 snapshotEffectView:(bool)arg1 completion:(id /* block */)arg2;

@end
