// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMSharedUtilities.framework/Versions/A/IMSharedUtilities
@interface IMStickerTapback : IMTapback

@property (nonatomic, readonly) IMStickerTapback *counterpart;
@property (nonatomic, readonly) IMStickerTapback *removedTapbackCounterpart;
@property (nonatomic, readonly) IMStickerTapback *visibleTapbackCounterpart;
@property (nonatomic, readonly) NSString *stickerIdentifier;
@property (nonatomic, readonly) NSString *transferGUID;
@property (nonatomic, readonly) long long commSafetySensitivityState;

+ (bool)isValidAssociatedMessageType:(long long)arg0;

- (bool)isEqual:(id)arg0;
- (id)actionStringFormatWithAdaptiveImageGlyphAvailable:(bool)arg0;
- (id)adaptiveImageGlyphForPreviewStringWithAdaptiveImageGlyphProvider:(id /* block */)arg0;
- (id)counterpart;
- (id)initWithAssociatedMessageType:(long long)arg0;
- (id)initWithCoder:(id)arg0;
- (id)initWithIMRemoteObjectSerializedDictionary:(id)arg0;
- (id)initWithTransferGUID:(id)arg0 isRemoved:(bool)arg1;
- (id)messageForChat:(id)arg0 messageGUID:(id)arg1 messagePartRange:(_NSRange)arg2 messageSummaryInfo:(id)arg3 threadIdentifier:(id)arg4;
- (id)reactionStringWithAdaptiveImageGlyph:(id)arg0 isCommSafetySensitiveProvider:(id /* block */)arg1;
- (id)removedTapbackCounterpart;
- (id)stickerIdentifier;
- (id)transferGUID;
- (id)visibleTapbackCounterpart;
- (long long)commSafetySensitivityState;

@end
