// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/Frameworks/Messages.framework/Versions/A/Messages
@interface MSMessageTemplateLayout : MSMessageLayout <NSSecureCoding>

@property (copy, nonatomic) NSString *caption;
@property (copy, nonatomic) NSString *imageSubtitle;
@property (copy, nonatomic) NSString *imageTitle;
@property (copy, nonatomic) NSString *subcaption;
@property (copy, nonatomic) NSString *trailingCaption;
@property (copy, nonatomic) NSString *trailingSubcaption;
@property (copy, nonatomic) NSURL *mediaFileURL;
@property (retain, nonatomic) NSData *mediaData;
@property (retain, nonatomic) NSString *mediaType;
@property (retain, nonatomic) UIImage *image;

+ (bool)supportsSecureCoding;

- (bool)isEqual:(id)arg0;
- (id)_sanitizedCopy;
- (id)caption;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)image;
- (id)imageSubtitle;
- (id)imageTitle;
- (id)init;
- (id)initWithCoder:(id)arg0;
- (id)mediaData;
- (id)mediaFileURL;
- (id)mediaType;
- (id)subcaption;
- (id)trailingCaption;
- (id)trailingSubcaption;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg0;
- (void)setCaption:(id)arg0;
- (void)setImage:(id)arg0;
- (void)setImageSubtitle:(id)arg0;
- (void)setImageTitle:(id)arg0;
- (void)setMediaData:(id)arg0;
- (void)setMediaFileURL:(id)arg0;
- (void)setMediaType:(id)arg0;
- (void)setSubcaption:(id)arg0;
- (void)setTrailingCaption:(id)arg0;
- (void)setTrailingSubcaption:(id)arg0;

@end
