// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/Frameworks/Messages.framework/Versions/A/Messages
@interface MSMessageLiveLayout : MSMessageLayout <NSSecureCoding>

@property (nonatomic) bool liveEditableInEntryView;
@property (nonatomic) bool sendAlternateLayoutAsText;
@property (readonly, nonatomic) MSMessageTemplateLayout *alternateLayout;
@property (retain, nonatomic) NSArray *requiredCapabilities;

+ (bool)supportsSecureCoding;

- (bool)liveEditableInEntryView;
- (bool)sendAlternateLayoutAsText;
- (id)_sanitizedCopy;
- (id)alternateLayout;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)init;
- (id)initWithAlternateLayout:(id)arg0;
- (id)initWithCoder:(id)arg0;
- (id)requiredCapabilities;
- (void)encodeWithCoder:(id)arg0;
- (void)setLiveEditableInEntryView:(bool)arg0;
- (void)setRequiredCapabilities:(id)arg0;
- (void)setSendAlternateLayoutAsText:(bool)arg0;

@end
