// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/SPOwner.framework/Versions/A/SPOwner
@interface SPBeaconManager : NSObject

@property (copy, nonatomic) id /* block */ beaconingKeyChangedBlockWithCompletion;
@property (copy, nonatomic) id /* block */ nearbyTokensChangedBlockWithCompletion;
@property (copy, nonatomic) id /* block */ stateChangedBlockWithCompletion;
@property (copy, nonatomic) id /* block */ statusChangedBlockWithCompletion;
@property (retain, nonatomic) FMXPCServiceDescription *serviceDescription;
@property (retain, nonatomic) FMXPCServiceDescription *userAgentServiceDescription;
@property (retain, nonatomic) FMXPCSession *session;
@property (retain, nonatomic) FMXPCSession *userAgentSession;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) SPBeaconManagerSimpleBeaconUpdateInterface *simpleBeaconUpdateInterface;
@property (retain, nonatomic) SPLocalBeaconManager *localBeaconingManager;
@property (retain, nonatomic) id<SPBeaconManagerXPCProtocol> proxy;
@property (retain, nonatomic) id<SPBeaconManagerXPCProtocol> userAgentProxy;

- (id /* block */)beaconingKeyChangedBlockWithCompletion;
- (id /* block */)nearbyTokensChangedBlockWithCompletion;
- (id /* block */)stateChangedBlockWithCompletion;
- (id /* block */)statusChangedBlockWithCompletion;
- (id)init;
- (id)localBeaconingManager;
- (id)proxy;
- (id)queue;
- (id)remoteInterface;
- (id)serviceDescription;
- (id)session;
- (id)simpleBeaconUpdateInterface;
- (id)userAgentProxy;
- (id)userAgentServiceDescription;
- (id)userAgentSession;
- (void)allBeaconingKeysForUUID:(id)arg0 dateInterval:(id)arg1 forceGenerate:(bool)arg2 completion:(id /* block */)arg3;
- (void)allBeaconsOfType:(id)arg0 completion:(id /* block */)arg1;
- (void)allBeaconsOfTypes:(id)arg0 completion:(id /* block */)arg1;
- (void)allBeaconsOfTypes:(id)arg0 includeDupes:(bool)arg1 includeHidden:(bool)arg2 completion:(id /* block */)arg3;
- (void)allBeaconsWithCompletion:(id /* block */)arg0;
- (void)allDuriansWithCompletion:(id /* block */)arg0;
- (void)beaconForUUID:(id)arg0 completion:(id /* block */)arg1;
- (void)beaconingKeysForUUID:(id)arg0 dateInterval:(id)arg1 completion:(id /* block */)arg2;
- (void)connectedToBeacon:(id)arg0 withIndex:(unsigned long long)arg1 completion:(id /* block */)arg2;
- (void)connectedToBeacon:(id)arg0 withIndex:(unsigned long long)arg1;
- (void)connectionTokensForBeaconUUID:(id)arg0 completion:(id /* block */)arg1;
- (void)connectionTokensForBeaconUUID:(id)arg0 criteria:(id)arg1 completion:(id /* block */)arg2;
- (void)connectionTokensForBeaconUUID:(id)arg0 dateInterval:(id)arg1 completion:(id /* block */)arg2;
- (void)createDuplicateBeaconsForBeacon:(id)arg0 skipGroupIdentifier:(bool)arg1 count:(long long)arg2 completion:(id /* block */)arg3;
- (void)createKeyReconcilerWithCompletion:(id /* block */)arg0;
- (void)createOwnedDeviceKeyRecordForUUID:(id)arg0 completion:(id /* block */)arg1;
- (void)dealloc;
- (void)fetchFirmwareVersionForBeacon:(id)arg0 completion:(id /* block */)arg1;
- (void)fetchKeyMapFileDescriptorForBeacon:(id)arg0 completion:(id /* block */)arg1;
- (void)fetchUserStatsForBeacon:(id)arg0 completion:(id /* block */)arg1;
- (void)invalidate;
- (void)isLPEMModeSupported:(id /* block */)arg0;
- (void)keySyncMetadataWithcompletion:(id /* block */)arg0;
- (void)notificationBeaconForSubscriptionId:(id)arg0 completion:(id /* block */)arg1;
- (void)ownedDeviceKeyRecordsForUUID:(id)arg0 completion:(id /* block */)arg1;
- (void)postedLocalNotifyWhenFoundNotificationForUUID:(id)arg0 completion:(id /* block */)arg1;
- (void)purgeOwnedDeviceKeyRecordsForUUID:(id)arg0 completion:(id /* block */)arg1;
- (void)removeDuplicateBeaconsWithCompletion:(id /* block */)arg0;
- (void)repairDataStore:(id /* block */)arg0;
- (void)roleCategoriesWithCompletion:(id /* block */)arg0;
- (void)setAlignmentUncertainty:(double)arg0 atIndex:(unsigned long long)arg1 date:(id)arg2 forBeacon:(id)arg3 completion:(id /* block */)arg4;
- (void)setBeaconingKeyChangedBlockWithCompletion:(id /* block */)arg0;
- (void)setCurrentWildKeyIndex:(long long)arg0 forBeacon:(id)arg1 completion:(id /* block */)arg2;
- (void)setKeyRollInterval:(unsigned long long)arg0 forBeacon:(id)arg1 completion:(id /* block */)arg2;
- (void)setLocalBeaconingManager:(id)arg0;
- (void)setNearbyTokensChangedBlockWithCompletion:(id /* block */)arg0;
- (void)setProxy:(id)arg0;
- (void)setQueue:(id)arg0;
- (void)setRole:(long long)arg0 forBeacon:(id)arg1 completion:(id /* block */)arg2;
- (void)setServiceDescription:(id)arg0;
- (void)setSession:(id)arg0;
- (void)setSimpleBeaconUpdateInterface:(id)arg0;
- (void)setStateChangedBlockWithCompletion:(id /* block */)arg0;
- (void)setStatusChangedBlockWithCompletion:(id /* block */)arg0;
- (void)setSuppressLPEMBeaconing:(bool)arg0 completion:(id /* block */)arg1;
- (void)setUserAgentProxy:(id)arg0;
- (void)setUserAgentServiceDescription:(id)arg0;
- (void)setUserAgentSession:(id)arg0;
- (void)setUserHasAcknowledgedFindMy:(bool)arg0 completion:(id /* block */)arg1;
- (void)setWildKeyBase:(unsigned long long)arg0 interval:(unsigned long long)arg1 fallback:(unsigned long long)arg2 forBeacon:(id)arg3 completion:(id /* block */)arg4;
- (void)start;
- (void)startUpdatingSimpleBeaconsWithContext:(id)arg0 collectionDifference:(id /* block */)arg1 completion:(id /* block */)arg2;
- (void)stopUpdatingSimpleBeaconsWithCompletion:(id /* block */)arg0;
- (void)submitDeviceEvent:(id)arg0 source:(unsigned int)arg1 attachedTo:(id)arg2 completion:(id /* block */)arg3;
- (void)unacceptedBeaconsWithCompletion:(id /* block */)arg0;
- (void)updateBeacon:(id)arg0 updates:(id)arg1 completion:(id /* block */)arg2;
- (void)updateObfuscatedIdentifierWithCompletion:(id /* block */)arg0;
- (void)userHasAcknowledgeFindMyWithCompletion:(id /* block */)arg0;

@end
