// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/SPOwner.framework/Versions/A/SPOwner
@interface SPLostModeInfo : NSObject <NSCopying, NSSecureCoding>

@property (copy, nonatomic) NSDate *timestamp;
@property (copy, nonatomic) NSString *email;
@property (copy, nonatomic) NSString *message;
@property (copy, nonatomic) NSString *phoneNumber;

+ (bool)supportsSecureCoding;

- (id)copyWithZone:(_NSZone *)arg0;
- (id)email;
- (id)initWithCoder:(id)arg0;
- (id)initWithMessage:(id)arg0 email:(id)arg1 phoneNumber:(id)arg2 timestamp:(id)arg3;
- (id)message;
- (id)phoneNumber;
- (id)timestamp;
- (void)encodeWithCoder:(id)arg0;
- (void)setEmail:(id)arg0;
- (void)setMessage:(id)arg0;
- (void)setPhoneNumber:(id)arg0;
- (void)setTimestamp:(id)arg0;

@end
