// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/Stickers.framework/Versions/A/Stickers
@interface STKSticker : NSObject <NSSecureCoding>

@property (nonatomic) double creationDate;
@property (nonatomic) double lastUsedDate;
@property (nonatomic) double libraryIndex;
@property (nonatomic) long long byteCount;
@property (nonatomic) long long effect;
@property (nonatomic, copy) NSArray *representations;
@property (nonatomic, copy) NSData *metadata;
@property (nonatomic, copy) NSString *accessibilityName;
@property (nonatomic, copy) NSString *externalURI;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *promptPrimaryLanguageIdentifier;
@property (nonatomic, copy) NSString *rewrittenPrompt;
@property (nonatomic, copy) NSString *sanitizedPrompt;
@property (nonatomic, copy) NSString *searchText;
@property (nonatomic, copy) NSUUID *_companionRecentUUID;
@property (nonatomic, readonly) NSArray *distributionRestrictions_ObjC;
@property (nonatomic, readonly) NSString *description;
@property (nonatomic, readonly) NSUUID *id;
@property (nonatomic, readonly) NSUUID *identifier;
@property (nonatomic, readonly) bool canDistribute;
@property (nonatomic, readonly) bool distributionIsRestricted;
@property (nonatomic, readonly) bool isGeneratedSticker;
@property (nonatomic, readonly) bool prefersAnimation;
@property (nonatomic, readonly) long long hash;
@property (nonatomic, retain) STKStickerAttributionInfo *attributionInfo;

+ (bool)supportsSecureCoding;
+ (id)kGenmojiFirstBetaReleaseDate;

- (bool)canDistribute;
- (bool)distributionIsRestricted;
- (bool)isEqual:(id)arg0;
- (bool)isGeneratedSticker;
- (bool)prefersAnimation;
- (double)creationDate;
- (double)lastUsedDate;
- (double)libraryIndex;
- (id)_companionRecentUUID;
- (id)accessibilityName;
- (id)attributionInfo;
- (id)description;
- (id)distributionRestrictions_ObjC;
- (id)externalURI;
- (id)id;
- (id)identifier;
- (id)init;
- (id)initWithCoder:(id)arg0;
- (id)metadata;
- (id)name;
- (id)promptPrimaryLanguageIdentifier;
- (id)representations;
- (id)rewrittenPrompt;
- (id)sanitizedPrompt;
- (id)searchText;
- (long long)byteCount;
- (long long)effect;
- (long long)hash;
- (void)encodeWithCoder:(id)arg0;
- (void)setAccessibilityName:(id)arg0;
- (void)setAttributionInfo:(id)arg0;
- (void)setByteCount:(long long)arg0;
- (void)setCreationDate:(double)arg0;
- (void)setEffect:(long long)arg0;
- (void)setExternalURI:(id)arg0;
- (void)setLastUsedDate:(double)arg0;
- (void)setLibraryIndex:(double)arg0;
- (void)setMetadata:(id)arg0;
- (void)setName:(id)arg0;
- (void)setPromptPrimaryLanguageIdentifier:(id)arg0;
- (void)setRepresentations:(id)arg0;
- (void)setRewrittenPrompt:(id)arg0;
- (void)setSanitizedPrompt:(id)arg0;
- (void)setSearchText:(id)arg0;
- (void)set_companionRecentUUID:(id)arg0;

@end
