// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/Stickers.framework/Versions/A/Stickers
@interface STKStickerAttributionInfo : NSObject <NSSecureCoding>

@property (nonatomic, copy) NSString *bundleIdentifier;
@property (nonatomic, readonly) NSNumber *adamID;
@property (nonatomic, readonly) NSString *description;
@property (nonatomic, readonly) NSString *name;
@property (nonatomic, readonly) long long hash;

+ (bool)supportsSecureCoding;

- (bool)isEqual:(id)arg0;
- (id)adamID;
- (id)bundleIdentifier;
- (id)description;
- (id)init;
- (id)initWithCoder:(id)arg0;
- (id)name;
- (long long)hash;
- (void)encodeWithCoder:(id)arg0;
- (void)setBundleIdentifier:(id)arg0;

@end
