// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/Stickers.framework/Versions/A/Stickers
@interface STKStickerRepresentation : NSObject <NSSecureCoding>

@property (nonatomic) bool isPreferred;
@property (nonatomic) long long byteCount;
@property (nonatomic, copy) NSData *data;
@property (nonatomic, copy) NSString *role;
@property (nonatomic, readonly) CGSize size;
@property (nonatomic, readonly) NSString *description;
@property (nonatomic, readonly) NSUUID *identifier;
@property (nonatomic, readonly) UTType *uti;
@property (nonatomic, readonly) bool isAnimated;
@property (nonatomic, readonly) long long hash;
@property (nonatomic, readonly) long long version;

+ (bool)supportsSecureCoding;

- (CGSize)size;
- (bool)isAnimated;
- (bool)isEqual:(id)arg0;
- (bool)isPreferred;
- (id)data;
- (id)description;
- (id)identifier;
- (id)init;
- (id)initWithCoder:(id)arg0;
- (id)role;
- (id)uti;
- (long long)byteCount;
- (long long)hash;
- (long long)version;
- (void)encodeWithCoder:(id)arg0;
- (void)setByteCount:(long long)arg0;
- (void)setData:(id)arg0;
- (void)setIsPreferred:(bool)arg0;
- (void)setRole:(id)arg0;

@end
