// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/Versions/A/TelephonyUtilities
@interface TUConversationMember : NSObject <NSCopying, NSSecureCoding>

@property (copy, nonatomic) NSString *nickname;
@property (copy, nonatomic) NSString *stableDeviceIdentifier;
@property (copy, nonatomic) TUConversationMemberAssociation *association;
@property (copy, nonatomic) TUConversationParticipantCluster *proposedParticipantCluster;
@property (copy, nonatomic) TUHandle *lightweightPrimary;
@property (copy, nonatomic) TUHandle *splitSessionPrimary;
@property (nonatomic) bool isLightweightMember;
@property (nonatomic) bool isOtherInvitedHandle;
@property (nonatomic) bool isSplitSessionMember;
@property (nonatomic) bool joinedFromLetMeIn;
@property (nonatomic) long long validationSource;
@property (nonatomic) unsigned long long lightweightPrimaryParticipantIdentifier;
@property (readonly, copy, nonatomic) NSArray *idsDestinations;
@property (readonly, copy, nonatomic) NSSet *handles;
@property (readonly, copy, nonatomic) NSString *idsDestination;
@property (readonly, copy, nonatomic) NSString *idsFromID;
@property (readonly, nonatomic) TUHandle *handle;
@property (readonly, nonatomic) bool needsContactLookupForDisplayName;
@property (readonly, nonatomic) bool validated;
@property (retain, nonatomic) NSDate *dateInitiatedLetMeIn;
@property (retain, nonatomic) NSDate *dateReceivedLetMeIn;
@property (retain, nonatomic) TUVoucher *associationVoucher;

+ (bool)supportsSecureCoding;

- (bool)isEqual:(id)arg0;
- (bool)isEqualToMember:(id)arg0;
- (bool)isLightweightMember;
- (bool)isOtherInvitedHandle;
- (bool)isSplitSessionMember;
- (bool)isValidated;
- (bool)joinedFromLetMeIn;
- (bool)needsContactLookupForDisplayName;
- (bool)pseudonym;
- (bool)representsSameMemberAs:(id)arg0;
- (id)association;
- (id)associationVoucher;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)dateInitiatedLetMeIn;
- (id)dateReceivedLetMeIn;
- (id)description;
- (id)handle;
- (id)handles;
- (id)idsDestination;
- (id)idsDestinations;
- (id)idsFromID;
- (id)initWithCoder:(id)arg0;
- (id)initWithContact:(id)arg0 additionalHandles:(id)arg1;
- (id)initWithContact:(id)arg0;
- (id)initWithDestination:(id)arg0;
- (id)initWithDestinations:(id)arg0;
- (id)initWithHandle:(id)arg0 nickname:(id)arg1 joinedFromLetMeIn:(bool)arg2;
- (id)initWithHandle:(id)arg0 nickname:(id)arg1;
- (id)initWithHandle:(id)arg0;
- (id)initWithHandles:(id)arg0;
- (id)lightweightPrimary;
- (id)nickname;
- (id)proposedParticipantCluster;
- (id)splitSessionPrimary;
- (id)stableDeviceIdentifier;
- (long long)validationSource;
- (unsigned long long)hash;
- (unsigned long long)lightweightPrimaryParticipantIdentifier;
- (void)encodeWithCoder:(id)arg0;
- (void)setAssociation:(id)arg0;
- (void)setAssociationVoucher:(id)arg0;
- (void)setDateInitiatedLetMeIn:(id)arg0;
- (void)setDateReceivedLetMeIn:(id)arg0;
- (void)setIsLightweightMember:(bool)arg0;
- (void)setIsOtherInvitedHandle:(bool)arg0;
- (void)setIsSplitSessionMember:(bool)arg0;
- (void)setJoinedFromLetMeIn:(bool)arg0;
- (void)setLightweightPrimary:(id)arg0;
- (void)setLightweightPrimaryParticipantIdentifier:(unsigned long long)arg0;
- (void)setNickname:(id)arg0;
- (void)setProposedParticipantCluster:(id)arg0;
- (void)setSplitSessionPrimary:(id)arg0;
- (void)setStableDeviceIdentifier:(id)arg0;
- (void)setValidationSource:(long long)arg0;

@end
