// Generated by swift/Tools/private-api on macOS 26.5.2.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/Versions/A/TelephonyUtilities
@interface TUJoinContinuityConversationRequest : NSObject <NSSecureCoding>

@property (readonly, nonatomic) NSUUID *uuid;
@property (readonly, nonatomic) bool isAudioEnabled;
@property (readonly, nonatomic) bool isVideoEnabled;
@property (readonly, nonatomic) bool wantsStagingArea;

+ (bool)supportsSecureCoding;
+ (id)requestForJoinWithUUID:(id)arg0 isAudioEnabled:(bool)arg1 isVideoEnabled:(bool)arg2;
+ (id)requestForStagingAreaWithUUID:(id)arg0;

- (bool)isAudioEnabled;
- (bool)isVideoEnabled;
- (bool)wantsStagingArea;
- (id)description;
- (id)initWithCoder:(id)arg0;
- (id)initWithUUID:(id)arg0 isAudioEnabled:(bool)arg1 isVideoEnabled:(bool)arg2 wantsStagingArea:(bool)arg3;
- (id)uuid;
- (void)encodeWithCoder:(id)arg0;

@end
