//  TokenAuthDefaultOffTests
//  That the token system does not exist until it is switched on.
//
//  "Available but unused" drifting into "used" is exactly the kind of change that would not
//  announce itself: nothing would fail, the server would simply start generating key
//  material, exposing endpoints, and evaluating headers that a default install is supposed
//  to have no notion of.
//
//  So the posture is asserted as facts rather than trusted as convention.
//
//  NO REAL CREDENTIALS — see CONTRIBUTING.md.

import BBSettings
import Foundation
import Testing

@testable import BBAuth

/// The narrow secret store BBAuth declares, backed by a dictionary.
private final class RecordingSecrets: SecretStoring, @unchecked Sendable {
  private let lock = NSLock()
  private var storage: [String: String] = [:]
  private var _reads: [String] = []
  private var _writes: [String] = []

  var writes: [String] { lock.withLock { _writes } }

  func get(_ key: String) throws -> String? {
    lock.withLock {
      _reads.append(key)
      return storage[key]
    }
  }
  func set(_ key: String, value: String) throws {
    lock.withLock {
      _writes.append(key)
      storage[key] = value
    }
  }
  func delete(_ key: String) throws {
    lock.withLock { _ = storage.removeValue(forKey: key) }
  }
}

@Suite("Token auth is dormant by default")
struct TokenAuthDefaultOffTests {

  /// The default is `password`, and nothing else.
  @Test("The shipping default is password mode")
  func defaultMode() async {
    let service = TokenAuthService()
    #expect(await service.mode == .password)
    #expect(await !service.isEnabled)
  }

  /// The endpoints must 404, not 401 — a 401 tells an attacker the endpoint exists, and it
  /// would also make the route table differ from the Node server's, which the parity
  /// harness diffs strictly.
  @Test("Token auth is off by default and on only when the mode says so")
  func offByDefault() async {
    #expect(await !TokenAuthService().isEnabled)
    #expect(
      await TokenAuthService(
        configuration: TokenAuthConfiguration(mode: .token),
        secrets: RecordingSecrets()
      ).isEnabled)
  }

  /// No new key material on a fresh install. A signing key the user did not ask for is a
  /// secret they now have to protect and back up.
  @Test("No signing key is generated by default")
  func noSigningKey() async {
    let secrets = RecordingSecrets()
    let service = TokenAuthService(secrets: secrets)

    // Exercise the paths that would create one if anything were eager.
    _ = await service.isEnabled
    _ = try? await service.devices()
    #expect(await !service.hasGeneratedSigningKey())
    #expect(secrets.writes.isEmpty, "nothing should have been written to the Keychain")
  }

  /// BearerTokenScheme is not constructed, so a Bearer header is not evaluated — it falls
  /// through to the password scheme, which treats it as a candidate password and fails.
  @Test("A Bearer header is ignored rather than evaluated")
  func bearerHeaderIgnored() async {
    let service = TokenAuthService()
    let chain = await service.chain(passwordProvider: { PasswordDigest("correct-horse") })

    let outcome = await chain.authenticate(
      CredentialPresentation(
        authorizationHeader: "Bearer eyJhbGciOiJFZERTQSJ9.eyJzdWIiOiJ4In0.c2ln",
        path: "/api/v1/ping"
      )
    )

    // Failed, not authenticated — and specifically not "revoked" or "expired", which
    // would mean a token scheme had looked at it.
    guard case .failed(let failure) = outcome else {
      Issue.record("expected failure, got \(outcome)")
      return
    }
    #expect(failure == .invalidCredential)
  }

  /// The password path is completely unaffected by any of this.
  @Test("Password authentication is unchanged")
  func passwordStillWorks() async {
    let service = TokenAuthService()
    let chain = await service.chain(passwordProvider: { PasswordDigest("correct-horse") })

    let outcome = await chain.authenticate(
      CredentialPresentation(
        queryParameters: ["password": "correct-horse"], path: "/api/v1/ping"
      )
    )
    guard case .authenticated(let principal) = outcome else {
      Issue.record("expected the password to authenticate, got \(outcome)")
      return
    }
    // No device identity — which is the limitation token auth exists to fix.
    #expect(principal.deviceID == nil)
    #expect(principal.scopes == Scope.all)
  }

  /// Every endpoint refuses while off. The routes are unregistered so this should be
  /// unreachable — but a handler that answered anyway would silently undo the posture.
  @Test("Every token endpoint refuses while disabled")
  func endpointsRefuseWhileDisabled() async {
    let service = TokenAuthService()

    await #expect(throws: EnrollmentError.notEnabled) {
      _ = try await service.issueEnrollmentCode()
    }
    await #expect(throws: EnrollmentError.notEnabled) {
      _ = try await service.enroll(
        name: "Phone", platform: "android", passwordAuthenticated: true
      )
    }
    await #expect(throws: EnrollmentError.notEnabled) {
      _ = try await service.issueToken(clientId: "bb_x", clientSecret: "y")
    }
    await #expect(throws: EnrollmentError.notEnabled) {
      _ = try await service.rotateSecret(clientId: "bb_x", currentSecret: "y")
    }
    await #expect(throws: EnrollmentError.notEnabled) {
      try await service.revoke(deviceID: DeviceID("x"))
    }
  }

  /// No enrollment state on a fresh install.
  @Test("No device state exists by default")
  func noDeviceState() async throws {
    #expect(try await TokenAuthService().devices().isEmpty)
  }

  /// Turning it on is one setting, with no rebuild — and turning it off is equally clean,
  /// because the password scheme never stopped working.
  @Test("Enabling and disabling is a single setting")
  func switchingIsOneSetting() async {
    let secrets = RecordingSecrets()
    let enabled = TokenAuthService(
      configuration: TokenAuthConfiguration(mode: .both), secrets: secrets
    )
    #expect(await enabled.isEnabled)

    // Under `both`, the password still authenticates.
    let chain = await enabled.chain(passwordProvider: { PasswordDigest("correct-horse") })
    let outcome = await chain.authenticate(
      CredentialPresentation(queryParameters: ["password": "correct-horse"])
    )
    guard case .authenticated = outcome else {
      Issue.record("password should still work under `both`, got \(outcome)")
      return
    }
  }
}
