//  SchemaProfileReadTests
//  The read path against every macOS schema this server supports.
//
//  Apple changes chat.db with each release — 82 message columns on Ventura, 88 on Sonoma,
//  94 on Sequoia — and `SchemaProfile` exists so capability follows the COLUMNS PRESENT
//  rather than the OS version. That design was tested one layer up, against synthetic column
//  sets handed to the serializer, and one layer down not at all: every other chat.db test in
//  this suite runs against `ChatDatabaseFixture`, a single hand-written modern schema.
//
//  The untested middle was the part that actually breaks. `SchemaProfile.detect` inspects
//  real columns and `select(_:)` builds SQL from them; a SELECT naming a column a release
//  does not have fails inside SQLite, long before a serializer sees anything, and no test
//  would have caught it.
//
//  The databases are real Apple schemas, generated by Tools/chatdb-fixtures/generate.py from
//  the dumps in macos/database/samples. The generator existed and CI ran its self-test, but
//  nothing had ever read what it produced.
//
//  To add a release: drop its schema dump in macos/database/samples/<release>/, add it to
//  PROFILES in the generator, regenerate into ChatDBFixtures, and add it below. What breaks
//  will be a SELECT.

import BBPersistence
import BBSerialization
import Foundation
import Testing

@testable import BBIMessage

/// What every generated fixture contains, identical across profiles so a difference in a
/// result is a difference in the SCHEMA handling rather than in the data.
enum Seeded {
  static let messages = 7
  static let chats = 3
  static let handles = 3
  static let attachments = 1
}

struct Profile: CustomStringConvertible, Sendable {
  let name: String
  /// The macOS major this release reports. `SchemaProfile.detect` uses it for one thing
  /// only — the date unit, which moved to nanoseconds at macOS 11 — so it is carried
  /// alongside the schema rather than guessed from it.
  let osMajorVersion: Int
  var description: String { name }
  static let all = [
    Profile(name: "ventura", osMajorVersion: 13),
    Profile(name: "sonoma", osMajorVersion: 14),
    Profile(name: "sequoia", osMajorVersion: 15),
  ]

  /// Copied out of the bundle before opening.
  ///
  /// `ReadOnlyDatabase` opens by path and SQLite wants to place its `-wal` and `-shm`
  /// companions beside the file; a resource inside an `.xctest` bundle is not somewhere to
  /// be doing that, and on a read-only volume it fails outright.
  func open() throws -> (ReadOnlyDatabase, URL) {
    guard
      let source = Bundle.module.url(
        forResource: "chat-\(name)", withExtension: "db", subdirectory: "ChatDBFixtures")
    else {
      throw ProfileError.fixtureMissing(name)
    }
    let directory = URL(fileURLWithPath: NSTemporaryDirectory())
      .appendingPathComponent("bb-schema-\(name)-\(UUID().uuidString)")
    try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
    let copy = directory.appendingPathComponent("chat.db")
    try FileManager.default.copyItem(at: source, to: copy)
    return (try ReadOnlyDatabase(path: copy.path), directory)
  }

  enum ProfileError: Error { case fixtureMissing(String) }
}

@Suite("Read path across macOS schemas")
struct SchemaProfileReadTests {

  /// Capability is derived, not declared.
  ///
  /// Asserted against the database's OWN columns rather than against a table of expected
  /// answers per release: a hardcoded list would be a second description of the schema that
  /// could disagree with the first, which is the failure `SchemaProfile` exists to avoid.
  @Test("Detected capabilities follow the columns actually present", arguments: Profile.all)
  func capabilitiesFollowColumns(_ profile: Profile) async throws {
    let (database, directory) = try profile.open()
    defer { try? FileManager.default.removeItem(at: directory) }

    let columns = try await database.columns(of: "message")
    let detected = try await SchemaProfile.detect(
      in: database, osMajorVersion: profile.osMajorVersion)

    #expect(detected.supportsEditedMessages == columns.contains("date_edited"))
    #expect(detected.supportsMessageParts == columns.contains("part_count"))
    #expect(detected.supportsQuietDelivery == columns.contains("was_delivered_quietly"))
    #expect(detected.supportsPayloadData == columns.contains("payload_data"))
    #expect(detected.supportsThreading == columns.contains("thread_originator_guid"))
    #expect(detected.supportsScheduledMessages == columns.contains("schedule_state"))
    #expect(
      detected.supportsMessageSummaryInfo == columns.contains("message_summary_info"))
  }

  /// The regression this suite is really for.
  ///
  /// Every read the server performs, against every schema. A query that names a column the
  /// release does not have throws out of SQLite here rather than in front of a user whose
  /// Mac is a version behind.
  @Test("Every read query answers on every schema", arguments: Profile.all)
  func everyQueryAnswers(_ profile: Profile) async throws {
    let (database, directory) = try profile.open()
    defer { try? FileManager.default.removeItem(at: directory) }

    let detected = try await SchemaProfile.detect(
      in: database, osMajorVersion: profile.osMajorVersion)
    let repository = MessageRepository(database: database, profile: detected)

    let messages = try await repository.messages(
      MessageRepository.MessageQuery(limit: 100))
    #expect(messages.count == Seeded.messages)
    #expect(try await repository.messageCount() == Seeded.messages)

    let chats = try await repository.chats(includeArchived: true, limit: 100, offset: 0)
    #expect(chats.count == Seeded.chats)
    #expect(try await repository.chatCount(includeArchived: true) == Seeded.chats)

    let handles = try await repository.handles(limit: 100, offset: 0)
    #expect(handles.count == Seeded.handles)

    // The relational reads, which join across tables whose columns also move.
    let first = try #require(messages.first)
    _ = try await repository.chats(forMessageGUID: first.guid)
    _ = try await repository.attachments(forMessageGUID: first.guid)
    _ = try await repository.message(guid: first.guid)
    if let handleID = first.handleID {
      _ = try await repository.handle(rowID: handleID)
    }

    let chat = try #require(chats.first)
    _ = try await repository.participants(chatGUID: chat.guid)
    _ = try await repository.chat(guid: chat.guid)
    _ = try await repository.chatCountsByService(includeArchived: true)

    let handle = try #require(handles.first)
    _ = try await repository.chats(forHandleRowID: handle.rowID)
    _ = try await repository.handle(address: handle.id)

    // Change detection reads on a different path from the listing, and is what runs
    // continuously in production.
    _ = try await repository.messagesChanged(since: Date(timeIntervalSince1970: 0))
    _ = try await repository.updatedMessageCount(after: Date(timeIntervalSince1970: 0))
    _ = try await repository.iMessageAccount()
  }

  /// Ties the read path to the wire: a row that loads but cannot be serialized is no more
  /// use than one that does not load.
  @Test("Every message on every schema serializes", arguments: Profile.all)
  func everyMessageSerializes(_ profile: Profile) async throws {
    let (database, directory) = try profile.open()
    defer { try? FileManager.default.removeItem(at: directory) }

    let detected = try await SchemaProfile.detect(
      in: database, osMajorVersion: profile.osMajorVersion)
    let repository = MessageRepository(database: database, profile: detected)
    let serializer = MessageSerializer(profile: detected)

    for row in try await repository.messages(MessageRepository.MessageQuery(limit: 100)) {
      let wire = serializer.serialize(row, context: MessageSerializer.Context())
      // Present on every release, so their absence means the projection broke rather
      // than that this schema lacks something.
      #expect(wire["guid"]?.stringValue == row.guid)
      #expect(wire["originalROWID"] != nil)
    }
  }

  /// Version-dependent fields are ABSENT on releases without the column, not null — the
  /// invariant `SerializationTests` pins against synthetic column sets, checked here
  /// against the real schemas.
  @Test("Scheduled-message fields appear only where the column exists", arguments: Profile.all)
  func versionDependentFieldsFollowTheSchema(_ profile: Profile) async throws {
    let (database, directory) = try profile.open()
    defer { try? FileManager.default.removeItem(at: directory) }

    let columns = try await database.columns(of: "message")
    let detected = try await SchemaProfile.detect(
      in: database, osMajorVersion: profile.osMajorVersion)
    #expect(detected.supportsScheduledMessages == columns.contains("schedule_state"))

    // Sequoia added it; Ventura and Sonoma do not have it. If a future regeneration makes
    // every profile alike, this suite has stopped discriminating and should be told so.
    if profile.name == "sequoia" {
      #expect(detected.supportsScheduledMessages)
    } else {
      #expect(!detected.supportsScheduledMessages)
    }
  }
}
