//  SchemaGeneration
//  Turning the recorded corpus into the committed schema table.
//
//  Runs deliberately, via `bb-openapi infer-schemas`, never as part of `emit`. See
//  FixtureSchemas for why the output is committed rather than derived on demand.

import BBHTTPAPI
import BBSerialization
import Foundation

public enum SchemaGeneration {

  /// Builds the schema table from every recording in the corpus.
  ///
  /// Only 200s contribute. An error envelope's `data` is a different shape from the success
  /// payload — a failed send returns the serialized message alongside a 500 — and merging the
  /// two would produce a schema describing neither.
  public static func generate(
    fixtureDirectory: String,
    entries: [RouteCatalog.Entry] = RouteCatalog.routes
  ) throws -> OrderedJSON {

    let exchanges = try FixtureCoverage.load(fixtureDirectory: fixtureDirectory)

    var requestSamples: [String: [JSONValue]] = [:]
    var responseSamples: [String: [JSONValue]] = [:]

    for exchange in exchanges where exchange.status == 200 {
      guard let index = FixtureCoverage.matchIndex(for: exchange, in: entries) else { continue }
      let operationID = OpenAPIDocument.operationID(for: entries[index])

      guard
        let data = FileManager.default.contents(
          atPath: (fixtureDirectory as NSString).appendingPathComponent(exchange.file)),
        let fixture = try? JSONValue.parse(data)
      else { continue }

      // Only JSON request bodies. A multipart body is recorded as text — the raw
      // `Content-Disposition` blob — and inferring a schema from it would mean writing a
      // MIME parser to describe a form whose fields are all strings anyway. The attachment
      // routes are therefore documented at the surface only, and that is written down rather
      // than left as a puzzle.
      if let body = fixture["request"]?["body"], body["kind"]?.stringValue == "json",
        let value = body["value"]
      {
        requestSamples[operationID, default: []].append(value)
      }

      // The ENVELOPE is already described by hand; what inference adds is `data`. Feeding it
      // the whole envelope would re-derive `status` and `message` badly — `status` would come
      // out as a plain integer where the hand-written schema says what it means.
      if let body = fixture["response"]?["body"], body["kind"]?.stringValue == "json",
        let payload = body["value"]?["data"]
      {
        responseSamples[operationID, default: []].append(payload)
      }
    }

    let operationIDs = Set(requestSamples.keys).union(responseSamples.keys).sorted()
    let operations = OrderedJSON.object(
      operationIDs.compactMap { id -> (key: String, value: OrderedJSON)? in
        let request = SchemaInference.infer(from: requestSamples[id] ?? [])
        let response = SchemaInference.infer(from: responseSamples[id] ?? [])
        guard request != nil || response != nil else { return nil }
        return (
          key: id,
          value: .obj([("request", request), ("response", response)])
        )
      })

    return .obj([
      (
        "$comment",
        .string(
          "GENERATED by `swift run bb-openapi infer-schemas` from the recorded corpus. "
            + "Inference from samples is unsound — see Sources/BBOpenAPI/SchemaInference.swift. "
            + "Hand corrections here are overwritten by the next run.")
      ),
      ("operations", operations),
    ])
  }
}
