// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/Stickers.framework/Versions/A/Stickers
@interface _STKStickerAttributionInfo : NSObject

@property (nonatomic, readonly) NSNumber *adamID;
@property (nonatomic, readonly) NSString *bundleIdentifier;
@property (nonatomic, readonly) NSString *description;
@property (nonatomic, readonly) NSString *name;

- (id)adamID;
- (id)bundleIdentifier;
- (id)description;
- (id)init;
- (id)initWithAdamID:(id)arg0 bundleIdentifier:(id)arg1 name:(id)arg2;
- (id)name;

@end
