// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/Stickers.framework/Versions/A/Stickers
@interface _STKStickerUIStickerRepresentation : NSObject

@property (nonatomic, readonly) CGSize size;
@property (nonatomic, readonly) NSData *data;
@property (nonatomic, readonly) NSString *description;
@property (nonatomic, readonly) NSString *role;
@property (nonatomic, readonly) NSString *type;

- (CGSize)size;
- (id)data;
- (id)description;
- (id)init;
- (id)initWithData:(id)arg0 type:(id)arg1 size:(CGSize)arg2 role:(id)arg3;
- (id)role;
- (id)type;

@end
