// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/ChatKit.framework/Versions/A/ChatKit
@interface CKAnimatedStickerMediaObject : CKAnimatedImageMediaObject

+ (bool)shouldShadePreview;

- (id)attachmentSummary:(unsigned long long)arg0;

@end
