// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/ChatKit.framework/Versions/A/ChatKit
@interface CKImageMediaObject : CKMediaObject <NSSecureCoding>

@property (readonly, nonatomic) CKImageData *imageData;
@property (readonly, nonatomic) PHLivePhoto *livePhoto;
@property (readonly, nonatomic) bool isAdaptiveImageGlyph;
@property (readonly, nonatomic) bool isIrisAsset;
@property (readonly, nonatomic) bool isSticker;
@property (readonly, nonatomic) bool screenshot;
@property (retain, nonatomic) IMSticker *sticker;
@property (retain, nonatomic) UIImage *thumbnail;

+ (Class)__ck_attachmentItemClass;
+ (Class)imageDataClass;
+ (bool)isPreviewable;
+ (bool)supportsSecureCoding;
+ (id)UTITypes;
+ (id)fallbackFilenamePrefix;

- (CGSize)bbSize;
- (CGSize)originalSize;
- (Class)replyContextBalloonViewClass;
- (bool)_ckEntityTranscriptCanPresentMediaObjectFullScreen;
- (bool)canExport;
- (bool)canShareItem;
- (bool)isAdaptiveImageGlyph;
- (bool)isIrisAsset;
- (bool)isPhotosCompatible;
- (bool)isScreenshot;
- (bool)isSticker;
- (bool)supportsUnknownSenderPreview;
- (bool)validatePreviewFormat;
- (id)attachmentSummary:(unsigned long long)arg0;
- (id)bbPreviewFillToSize:(CGSize)arg0;
- (id)calculateIrisVideoPath;
- (id)generatePreviewFromThumbnail:(id)arg0 width:(double)arg1 orientation:(char)arg2;
- (id)generateThumbnailFillToSize:(CGSize)arg0 contentAlignmentInsets:(UIEdgeInsets)arg1;
- (id)generateThumbnailForWidth:(double)arg0 orientation:(char)arg1;
- (id)getIrisVideoPath;
- (id)imageData;
- (id)initWithCoder:(id)arg0;
- (id)initWithTransfer:(id)arg0 context:(id)arg1 forceInlinePreview:(bool)arg2;
- (id)livePhoto;
- (id)location;
- (id)metricsCollectorMediaType;
- (id)pasteboardItemProvider;
- (id)previewItemTitle;
- (id)previewItemURL;
- (id)rtfDocumentItemsWithFormatString:(id)arg0 selectedTextRange:(_NSRange)arg1;
- (id)sticker;
- (id)thumbnail;
- (int)mediaType;
- (void)encodeWithCoder:(id)arg0;
- (void)legacyExport;
- (void)setSticker:(id)arg0;
- (void)setThumbnail:(id)arg0;

@end
