// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/ChatKit.framework/Versions/A/ChatKit
@interface CKMediaObjectManager : NSObject

@property (copy, nonatomic) NSArray *classes;
@property (copy, nonatomic) NSDictionary *UTITypes;
@property (copy, nonatomic) NSDictionary *dynTypes;
@property (retain, nonatomic) NSMutableDictionary *transfers;

+ (id)sharedInstance;

- (Class)classForFilename:(id)arg0;
- (Class)classForUTIType:(id)arg0;
- (Class)transferClass;
- (bool)_attachmentDataTooLargeToSend:(id)arg0 utiType:(id)arg1;
- (id)UTITypeForExtension:(id)arg0;
- (id)UTITypeForFilename:(id)arg0;
- (id)UTITypes;
- (id)allUTITypes;
- (id)classes;
- (id)dynTypes;
- (id)fileManager;
- (id)init;
- (id)mediaObjectWithData:(id)arg0 UTIType:(id)arg1 filename:(id)arg2 transcoderUserInfo:(id)arg3;
- (id)mediaObjectWithFileURL:(id)arg0 filename:(id)arg1 fileIsResolved:(bool)arg2 transcoderUserInfo:(id)arg3 attributionInfo:(id)arg4 adaptiveImageGlyphContentIdentifier:(id)arg5 adaptiveImageGlyphContentDescription:(id)arg6 hideAttachment:(bool)arg7 isScreenshot:(bool)arg8;
- (id)mediaObjectWithFileURL:(id)arg0 filename:(id)arg1 transcoderUserInfo:(id)arg2 attributionInfo:(id)arg3 adaptiveImageGlyphContentIdentifier:(id)arg4 adaptiveImageGlyphContentDescription:(id)arg5 hideAttachment:(bool)arg6;
- (id)mediaObjectWithFileURL:(id)arg0 filename:(id)arg1 transcoderUserInfo:(id)arg2;
- (id)mediaObjectWithSticker:(id)arg0 stickerUserInfo:(id)arg1;
- (id)mediaObjectWithTransferGUID:(id)arg0 imMessage:(id)arg1 chatContext:(id)arg2;
- (id)mediaObjectWithTransferGUID:(id)arg0 imMessage:(id)arg1;
- (id)transferWithFileURL:(id)arg0 transcoderUserInfo:(id)arg1 attributionInfo:(id)arg2 adaptiveImageGlyphContentIdentifier:(id)arg3 adaptiveImageGlyphContentDescription:(id)arg4 hideAttachment:(bool)arg5 isScreenshot:(bool)arg6;
- (id)transferWithFileURL:(id)arg0 transcoderUserInfo:(id)arg1 attributionInfo:(id)arg2 hideAttachment:(bool)arg3 isScreenshot:(bool)arg4 stickerEffectType:(unsigned long long)arg5;
- (id)transferWithFileURL:(id)arg0 transcoderUserInfo:(id)arg1 attributionInfo:(id)arg2 hideAttachment:(bool)arg3;
- (id)transferWithStickerFileURL:(id)arg0 transferUserInfo:(id)arg1 attributionInfo:(id)arg2 animatedImageCacheURL:(id)arg3 adaptiveImageGlyphContentIdentifier:(id)arg4 adaptiveImageGlyphContentDescription:(id)arg5;
- (id)transferWithTransferGUID:(id)arg0 imMessage:(id)arg1;
- (id)transfers;
- (void)_copyResolvedFileURL:(id)arg0 toURL:(id)arg1;
- (void)_previewGenerationFailedNotification:(id)arg0;
- (void)_previewGenerationSucceededNotification:(id)arg0;
- (void)dealloc;
- (void)setClasses:(id)arg0;
- (void)setDynTypes:(id)arg0;
- (void)setTransfers:(id)arg0;
- (void)setUTITypes:(id)arg0;
- (void)transferRemoved:(id)arg0;

@end
