// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/ChatKit.framework/Versions/A/ChatKit
@interface CKMessagePartChatItem : CKBalloonChatItem

@property (nonatomic) char cachedColor;
@property (readonly, copy, nonatomic) NSArray *messageAcknowledgments;
@property (readonly, nonatomic) CKAggregateAcknowledgmentChatItem *tapbacksChatItem;
@property (readonly, nonatomic) CKColor_t strokeColor;
@property (readonly, nonatomic) CKMessagePartHighlightChatItem *messageHighlightChatItem;
@property (readonly, nonatomic) IMMessage *message;
@property (readonly, nonatomic) IMMessageItem *messageItem;
@property (readonly, nonatomic) IMMessageItem *threadOriginator;
@property (readonly, nonatomic) NSArray *pasteboardItemProviders;
@property (readonly, nonatomic) NSArray *suggestedActionsList;
@property (readonly, nonatomic) NSArray *visibleAssociatedMessageChatItems;
@property (readonly, nonatomic) NSItemProvider *dragItemProvider;
@property (readonly, nonatomic) NSString *serviceName;
@property (readonly, nonatomic) NSString *threadIdentifier;
@property (readonly, nonatomic) _NSRange messagePartRange;
@property (readonly, nonatomic) _NSRange originalMessagePartRange;
@property (readonly, nonatomic) bool hasMessageAcknowledgment;
@property (readonly, nonatomic) bool hasStickers;
@property (readonly, nonatomic) bool hasVisibleAssociatedMessageItems;
@property (readonly, nonatomic) bool isBlackholed;
@property (readonly, nonatomic) bool isCorrupt;
@property (readonly, nonatomic) bool isReply;
@property (readonly, nonatomic) bool isReplyContextPreview;
@property (readonly, nonatomic) char balloonStyle;
@property (readonly, nonatomic) char color;
@property (readonly, nonatomic) long long index;
@property (readonly, nonatomic) unsigned long long scheduleState;
@property (readonly, nonatomic) unsigned long long scheduleType;

- (CKColor_t)strokeColor;
- (_NSRange)messagePartRange;
- (_NSRange)originalMessagePartRange;
- (bool)_isSURFRelatedMessage;
- (bool)canAttachStickers;
- (bool)canCopy;
- (bool)canForward;
- (bool)canInlineReply;
- (bool)canSendAsTextMessage;
- (bool)canSendAsTextMessageOverSatellite;
- (bool)canSendTapbacks;
- (bool)failed;
- (bool)hasMessageAcknowledgment;
- (bool)hasStickers;
- (bool)hasVisibleAssociatedMessageItems;
- (bool)isBlackholed;
- (bool)isCorrupt;
- (bool)isFromMe;
- (bool)isReply;
- (bool)isReplyContextPreview;
- (bool)stickersSnapToPoint;
- (char)balloonStyle;
- (char)cachedColor;
- (char)color;
- (double)timeIntervalSinceMessageSent;
- (id)aggregateAcknowledgmentChatItem;
- (id)compositionWithContext:(id)arg0;
- (id)description;
- (id)dragItemProvider;
- (id)fileURLForAttachment;
- (id)init;
- (id)initWithIMChatItem:(id)arg0 maxWidth:(double)arg1;
- (id)message;
- (id)messageAcknowledgments;
- (id)messageHighlightChatItem;
- (id)messageItem;
- (id)pasteboardItemProviders;
- (id)rtfDocumentItemsWithFormatString:(id)arg0 selectedTextRange:(_NSRange)arg1;
- (id)sender;
- (id)serviceName;
- (id)suggestedActionsList;
- (id)tapbackActionButtonImageName;
- (id)tapbacksChatItem;
- (id)threadIdentifier;
- (id)threadOriginator;
- (id)time;
- (id)visibleAssociatedMessageChatItems;
- (id)votingCounts;
- (long long)index;
- (long long)selectedType;
- (unsigned long long)scheduleState;
- (unsigned long long)scheduleType;
- (void)_setVisibleAssociatedMessageChatItems:(id)arg0;
- (void)configureBalloonView:(id)arg0;
- (void)setCachedColor:(char)arg0;

@end
