// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/FindMyDevice.framework/Versions/A/FindMyDevice
@interface FMDFMMManager : NSObject

@property (nonatomic) AuthorizationOpaqueRef *authRef;
@property (retain) FMDFMMAccountInfo *cachedAccountInfo;
@property (retain) LAContext *laContext;
@property (retain, nonatomic) FMNSXPCConnection *disableFMMConnection;

+ (id)sharedInstance;

- (AuthorizationOpaqueRef *)authRef;
- (bool)isFMMEnabled;
- (bool)needsLostModeExitAuth;
- (id)_adminAuthDataForRight:(char *)arg0;
- (id)_genericErrorForDisableContext:(unsigned long long)arg0;
- (id)addFMMAccount:(id)arg0;
- (id)cachedAccountInfo;
- (id)disableFMMConnection;
- (id)init;
- (id)laContext;
- (id)newErrorForCode:(int)arg0 message:(id)arg1;
- (id)removeFMMAccountWithUsername:(id)arg0 authRight:(id)arg1;
- (id)removeFMMAccountWithUsername:(id)arg0;
- (id)retrieveFMMAccount:(id *)arg0;
- (void)_createAuthRight;
- (void)_invalidateDisableFMMConnection;
- (void)_storeDisableFMMConnection:(id)arg0;
- (void)activationLockInfoForContext:(id)arg0 withCompletion:(id /* block */)arg1;
- (void)activationLockInfoForUnlockWithCompletion:(id /* block */)arg0;
- (void)activationLockInfoForValidationWithCompletion:(id /* block */)arg0;
- (void)addFMMAccount:(id)arg0 withCompletion:(id /* block */)arg1;
- (void)authenticateDeviceOwnerWithCallback:(id /* block */)arg0;
- (void)clearFMMAccountsWithCompletion:(id /* block */)arg0;
- (void)dealloc;
- (void)didChangeFMMAccountInfo:(id)arg0;
- (void)didReceiveLostModeExitAuthToken:(id)arg0;
- (void)didRemoveLocalFindableAccessory:(id)arg0 completion:(id /* block */)arg1;
- (void)disableFMMUsingToken:(id)arg0 deviceOwnerCredentials:(id)arg1 inContext:(unsigned long long)arg2 usingCallback:(id /* block */)arg3;
- (void)disableFMMUsingToken:(id)arg0 inContext:(unsigned long long)arg1 usingCallback:(id /* block */)arg2;
- (void)enableActivationLockWithCompletion:(id /* block */)arg0;
- (void)eraseAllContentAndSettingsUsingCallback:(id /* block */)arg0;
- (void)fetchAPNSTokenWithCompletion:(id /* block */)arg0;
- (void)fetchDeviceOwnerAuthContext:(id /* block */)arg0;
- (void)initiateLostModeExitAuthWithCompletion:(id /* block */)arg0;
- (void)isActivationLockCapableWithCompletion:(id /* block */)arg0;
- (void)isActivationLockedWithCompletion:(id /* block */)arg0;
- (void)locationCommandWithCompletion:(id /* block */)arg0;
- (void)locationPayloadWithCompletion:(id /* block */)arg0;
- (void)needsDeviceOwnerCredentials:(id /* block */)arg0;
- (void)performActivationLockOperationWithContext:(id)arg0 withCompletion:(id /* block */)arg1;
- (void)registerObservers;
- (void)removeActivationLockForMacOSUserWithPassword:(id)arg0 withCompletion:(id /* block */)arg1;
- (void)removeActivationLockForiCloudUser:(id)arg0 authenticationPET:(id)arg1 withCompletion:(id /* block */)arg2;
- (void)removeFMMAccountWithUsername:(id)arg0 authRight:(id)arg1 completion:(id /* block */)arg2;
- (void)removeFMMAccountWithUsername:(id)arg0 authRight:(id)arg1 deviceOwnerCredentials:(id)arg2 completion:(id /* block */)arg3;
- (void)removeFMMAccountWithUsername:(id)arg0 completion:(id /* block */)arg1;
- (void)removeManagedActivationLockWithCode:(id)arg0 withCompletion:(id /* block */)arg1;
- (void)retrieveFMMAccountWithCompletion:(id /* block */)arg0;
- (void)setAuthRef:(AuthorizationOpaqueRef *)arg0;
- (void)setCachedAccountInfo:(id)arg0;
- (void)setDisableFMMConnection:(id)arg0;
- (void)setLaContext:(id)arg0;
- (void)shouldPromptForCredentialsForDeviceActivation:(id /* block */)arg0;
- (void)shouldResumeCardsForUser:(id)arg0 withCompletion:(id /* block */)arg1;
- (void)signatureHeadersWithData:(id)arg0 completion:(id /* block */)arg1;
- (void)simulatePushWithPayload:(id)arg0 completion:(id /* block */)arg1;
- (void)unregisterObservers;
- (void)updateCredentialsContextForDeviceActivation:(id)arg0 completion:(id /* block */)arg1;
- (void)validateActivationLockForiCloudUser:(id)arg0 authenticationPET:(id)arg1 withCompletion:(id /* block */)arg2;

@end
