// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/FMF.framework/Versions/A/FMF
@interface FMFHandle : NSObject <NSCopying, NSSecureCoding>

@property (assign) bool pending;
@property (assign) bool reachable;
@property (assign) long long idsStatus;
@property (copy) NSNumber *trackingTimestamp;
@property (copy) NSString *identifier;
@property (copy) NSString *qualifiedIdentifier;
@property (copy, nonatomic) NSArray *aliasServerIds;
@property (copy, nonatomic) NSArray *invitationSentToIds;
@property (copy, nonatomic) NSDictionary *expiresByGroupId;
@property (copy, nonatomic) NSNumber *dsid;
@property (copy, nonatomic) NSNumber *favoriteOrder;
@property (copy, nonatomic) NSString *_idsCorrelationIdentifierInternal;
@property (copy, nonatomic) NSString *_prettyNameInternal;
@property (copy, nonatomic) NSString *hashedDSID;
@property (copy, nonatomic) NSString *serverId;
@property (nonatomic) bool isFamilyMember;

+ (bool)supportsSecureCoding;
+ (id)familyHandleWithId:(id)arg0 dsid:(id)arg1;
+ (id)handleWithId:(id)arg0 serverId:(id)arg1;
+ (id)handleWithId:(id)arg0;

- (bool)isEqual:(id)arg0;
- (bool)isFamilyMember;
- (bool)isPending;
- (bool)isPhoneNumber;
- (bool)isSharingThroughGroupId:(id)arg0;
- (bool)reachable;
- (id)IDSRecipientFromHandle:(id)arg0;
- (id)_idsCorrelationIdentifierInternal;
- (id)_prettyNameInternal;
- (id)aliasServerIds;
- (id)cachedPrettyName;
- (id)comparisonIdentifier;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)debugDescription;
- (id)description;
- (id)dsid;
- (id)expiresByGroupId;
- (id)favoriteOrder;
- (id)hashedDSID;
- (id)identifier;
- (id)initWithCoder:(id)arg0;
- (id)invitationSentToIds;
- (id)prettyName;
- (id)qualifiedIdentifier;
- (id)recordId;
- (id)sanitizePhoneNumber:(id)arg0;
- (id)serverId;
- (id)trackingTimestamp;
- (long long)idsStatus;
- (long long)prettyNameCompare:(id)arg0;
- (unsigned long long)hash;
- (void)abPreferencesDidChange;
- (void)addressBookDidChange;
- (void)clearFavoriteOrder;
- (void)correlationIdentifierForHandle:(id)arg0 withCompletion:(id /* block */)arg1;
- (void)encodeWithCoder:(id)arg0;
- (void)idsCorrelationIdentifierWithCompletion:(id /* block */)arg0;
- (void)prettyNameWithCompletion:(id /* block */)arg0;
- (void)setAliasServerIds:(id)arg0;
- (void)setDsid:(id)arg0;
- (void)setExpiresByGroupId:(id)arg0;
- (void)setFavoriteOrder:(id)arg0;
- (void)setHashedDSID:(id)arg0;
- (void)setICloudId:(id)arg0;
- (void)setIdentifier:(id)arg0;
- (void)setIdsStatus:(long long)arg0;
- (void)setInvitationSentToIds:(id)arg0;
- (void)setIsFamilyMember:(bool)arg0;
- (void)setPending:(bool)arg0;
- (void)setQualifiedIdentifier:(id)arg0;
- (void)setReachable:(bool)arg0;
- (void)setServerId:(id)arg0;
- (void)setTrackingTimestamp:(id)arg0;
- (void)set_idsCorrelationIdentifierInternal:(id)arg0;
- (void)set_prettyNameInternal:(id)arg0;

@end
