// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/FindMyLocateObjCWrapper.framework/Versions/A/FindMyLocateObjCWrapper
@interface FMLFriend : NSObject

@property (assign) bool originatedFromTheSameClient;
@property (assign) long long handleType;
@property (assign) long long origin;
@property (retain) FMLHandle *handle;
@property (retain) NSDate *createdAt;
@property (retain) NSDate *expiry;

- (bool)isEqual:(id)arg0;
- (bool)originatedFromTheSameClient;
- (id)comparisonIdentifier;
- (id)createdAt;
- (id)debugDescription;
- (id)description;
- (id)expiry;
- (id)handle;
- (id)initWithHandle:(id)arg0 handleType:(long long)arg1 createDate:(id)arg2 expiry:(id)arg3 origin:(long long)arg4 originatedFromTheSameClient:(bool)arg5;
- (long long)handleType;
- (long long)origin;
- (unsigned long long)hash;
- (void)setCreatedAt:(id)arg0;
- (void)setExpiry:(id)arg0;
- (void)setHandle:(id)arg0;
- (void)setHandleType:(long long)arg0;
- (void)setOrigin:(long long)arg0;
- (void)setOriginatedFromTheSameClient:(bool)arg0;

@end
