// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/NotesShared.framework/Versions/A/NotesShared
@interface ICInvitation : NSManagedObject

@property (copy, nonatomic) NSData *serverShareData;
@property (copy, nonatomic) NSData *thumbnailDataDark;
@property (copy, nonatomic) NSData *thumbnailDataLight;
@property (copy, nonatomic) NSDate *creationDate;
@property (copy, nonatomic) NSDate *modificationDate;
@property (copy, nonatomic) NSDate *receivedDate;
@property (copy, nonatomic) NSString *rootObjectType;
@property (copy, nonatomic) NSString *snippet;
@property (copy, nonatomic) NSString *title;
@property (copy, nonatomic) NSURL *shareURL;
@property (nonatomic) long long noteCount;
@property (nonatomic) long long noteCountRecursive;
@property (nonatomic) long long snippetAttachmentCount;
@property (nonatomic) long long subfolderCount;
@property (nonatomic) long long subfolderCountRecursive;
@property (nonatomic) short snippetAttachmentType;
@property (retain, nonatomic) CKShare *serverShare;
@property (retain, nonatomic) ICAccount *account;
@property (retain, nonatomic) ICCloudSyncingObject *rootObject;

+ (id)allInvitationsInContext:(id)arg0;
+ (id)invitationWithShareURL:(id)arg0 context:(id)arg1;
+ (id)invitationsMatchingPredicate:(id)arg0 context:(id)arg1;
+ (id)makeInvitationIfNeededWithShareURL:(id)arg0 account:(id)arg1 context:(id)arg2;
+ (id)makeInvitationWithShareURL:(id)arg0 account:(id)arg1 context:(id)arg2;
+ (id)predicateForPendingInvitationsInAccount:(id)arg0 receivedSince:(id)arg1;
+ (id)predicateForPendingInvitationsInAccount:(id)arg0;
+ (id)shareSystemFieldsTransformer;

- (id)serverShare;
- (void)setServerShare:(id)arg0;

@end
