// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/NotesShared.framework/Versions/A/NotesShared
@interface ICSearchQuery : NSObject

@property (nonatomic) bool wasForceStopped;
@property (readonly, nonatomic) NSDictionary *queryResults;
@property (readonly, nonatomic) bool modernResultsOnly;
@property (retain, nonatomic) CSSearchQuery *searchQuery;
@property (retain, nonatomic) ICRankingQueriesDefinition *rankingQueriesDefinition;
@property (retain, nonatomic) NSArray *externalRankingQueries;
@property (retain, nonatomic) NSMutableDictionary *mutableQueryResults;
@property (retain, nonatomic) NSObject<OS_dispatch_semaphore> *synchronousSemaphore;

+ (id)defaultAttributesToReturnFromCoreSpotlight;

- (bool)modernResultsOnly;
- (bool)run:(id *)arg0;
- (bool)wasForceStopped;
- (double)timeoutInterval;
- (id)attributesToFetch;
- (id)externalRankingQueries;
- (id)initWithExternalRankingQueries:(id)arg0;
- (id)initWithRankingQueriesDefinition:(id)arg0;
- (id)mutableQueryResults;
- (id)newSearchQueryContext;
- (id)newSearchQueryWithContext:(id)arg0;
- (id)queryResults;
- (id)queryResultsToAddFromBatch:(id)arg0;
- (id)rankingQueries;
- (id)rankingQueriesDefinition;
- (id)searchQuery;
- (id)synchronousSemaphore;
- (void)cancel;
- (void)forceStop;
- (void)queryFinishedRunningWithError:(id)arg0;
- (void)setExternalRankingQueries:(id)arg0;
- (void)setMutableQueryResults:(id)arg0;
- (void)setRankingQueriesDefinition:(id)arg0;
- (void)setSearchQuery:(id)arg0;
- (void)setSynchronousSemaphore:(id)arg0;
- (void)setWasForceStopped:(bool)arg0;
- (void)setupWithAttributes:(id)arg0;

@end
