// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/IDS.framework/Versions/A/IDS
@interface IDSIDQueryController : NSObject <TUIDSIDQueryController>

@property (readonly) Class superclass;
@property (readonly) unsigned long long hash;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;

+ (id)sharedInstance;

- (bool)_flushQueryCacheForService:(id)arg0;
- (bool)_hasCacheForService:(id)arg0;
- (bool)_warmupQueryCacheForService:(id)arg0;
- (bool)currentIDStatusForDestination:(id)arg0 service:(id)arg1 listenerID:(id)arg2 queue:(id)arg3 completionBlock:(id /* block */)arg4;
- (bool)currentIDStatusForDestination:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3 queue:(id)arg4 completionBlock:(id /* block */)arg5;
- (bool)currentIDStatusForDestination:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 respectExpiry:(bool)arg3 listenerID:(id)arg4 queue:(id)arg5 completionBlock:(id /* block */)arg6;
- (bool)currentIDStatusForDestination:(id)arg0 service:(id)arg1 respectExpiry:(bool)arg2 listenerID:(id)arg3 queue:(id)arg4 completionBlock:(id /* block */)arg5;
- (bool)currentIDStatusForDestinations:(id)arg0 service:(id)arg1 listenerID:(id)arg2 queue:(id)arg3 completionBlock:(id /* block */)arg4;
- (bool)currentIDStatusForDestinations:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3 queue:(id)arg4 completionBlock:(id /* block */)arg5;
- (bool)currentIDStatusForDestinations:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 respectExpiry:(bool)arg3 listenerID:(id)arg4 queue:(id)arg5 completionBlock:(id /* block */)arg6;
- (bool)currentIDStatusForDestinations:(id)arg0 service:(id)arg1 respectExpiry:(bool)arg2 listenerID:(id)arg3 queue:(id)arg4 completionBlock:(id /* block */)arg5;
- (bool)currentRemoteDevicesForDestinations:(id)arg0 service:(id)arg1 listenerID:(id)arg2 queue:(id)arg3 completionBlock:(id /* block */)arg4;
- (bool)currentRemoteDevicesForDestinations:(id)arg0 service:(id)arg1 listenerID:(id)arg2 queue:(id)arg3 completionBlockWithError:(id /* block */)arg4;
- (bool)currentRemoteDevicesForDestinations:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3 queue:(id)arg4 completionBlock:(id /* block */)arg5;
- (bool)currentRemoteDevicesForDestinations:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3 queue:(id)arg4 completionBlockWithError:(id /* block */)arg5;
- (bool)forceRefreshIDStatusForDestinations:(id)arg0 service:(id)arg1 listenerID:(id)arg2 queue:(id)arg3 completionBlock:(id /* block */)arg4;
- (bool)forceRefreshIDStatusForDestinations:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3 queue:(id)arg4 completionBlock:(id /* block */)arg5;
- (bool)idInfoForDestinations:(id)arg0 service:(id)arg1 infoTypes:(unsigned long long)arg2 options:(id)arg3 listenerID:(id)arg4 queue:(id)arg5 completionBlock:(id /* block */)arg6;
- (bool)idInfoForDestinations:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 infoTypes:(unsigned long long)arg3 options:(id)arg4 listenerID:(id)arg5 queue:(id)arg6 completionBlock:(id /* block */)arg7;
- (bool)participantsForDestinations:(id)arg0 service:(id)arg1 listenerID:(id)arg2 queue:(id)arg3 completionBlock:(id /* block */)arg4;
- (bool)participantsForDestinations:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3 queue:(id)arg4 completionBlock:(id /* block */)arg5;
- (bool)refreshIDStatusForDestination:(id)arg0 service:(id)arg1 listenerID:(id)arg2 queue:(id)arg3 completionBlock:(id /* block */)arg4;
- (bool)refreshIDStatusForDestination:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3 queue:(id)arg4 completionBlock:(id /* block */)arg5;
- (bool)refreshIDStatusForDestinations:(id)arg0 service:(id)arg1 listenerID:(id)arg2 queue:(id)arg3 completionBlock:(id /* block */)arg4;
- (bool)refreshIDStatusForDestinations:(id)arg0 service:(id)arg1 listenerID:(id)arg2 queue:(id)arg3 errorCompletionBlock:(id /* block */)arg4;
- (bool)refreshIDStatusForDestinations:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3 queue:(id)arg4 completionBlock:(id /* block */)arg5;
- (bool)refreshIDStatusForDestinations:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3 queue:(id)arg4 errorCompletionBlock:(id /* block */)arg5;
- (bool)removeListenerID:(id)arg0 forService:(id)arg1;
- (bool)requestIDStatusForDestination:(id)arg0 service:(id)arg1 listenerID:(id)arg2 queue:(id)arg3 completionBlock:(id /* block */)arg4;
- (bool)requestIDStatusForDestination:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3 queue:(id)arg4 completionBlock:(id /* block */)arg5;
- (bool)requestIDStatusForDestinations:(id)arg0 service:(id)arg1 listenerID:(id)arg2 queue:(id)arg3 completionBlock:(id /* block */)arg4;
- (bool)requestIDStatusForDestinations:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3 queue:(id)arg4 completionBlock:(id /* block */)arg5;
- (bool)requiredIDStatusForDestination:(id)arg0 service:(id)arg1 listenerID:(id)arg2 queue:(id)arg3 completionBlock:(id /* block */)arg4;
- (bool)requiredIDStatusForDestination:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3 queue:(id)arg4 completionBlock:(id /* block */)arg5;
- (bool)requiredIDStatusForDestinations:(id)arg0 service:(id)arg1 listenerID:(id)arg2 queue:(id)arg3 completionBlock:(id /* block */)arg4;
- (bool)requiredIDStatusForDestinations:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3 queue:(id)arg4 completionBlock:(id /* block */)arg5;
- (id)_currentCachedRemoteDevicesForDestinations:(id)arg0 service:(id)arg1 listenerID:(id)arg2;
- (id)_currentCachedRemoteDevicesForDestinations:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3;
- (id)_currentIDStatusForDestinations:(id)arg0 service:(id)arg1 listenerID:(id)arg2;
- (id)_currentIDStatusForDestinations:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3;
- (id)_currentIDStatusForDestinations:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 respectExpiry:(bool)arg3 listenerID:(id)arg4;
- (id)_currentIDStatusForDestinations:(id)arg0 service:(id)arg1 respectExpiry:(bool)arg2 listenerID:(id)arg3;
- (id)_refreshIDStatusForDestinations:(id)arg0 service:(id)arg1 listenerID:(id)arg2;
- (id)_refreshIDStatusForDestinations:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3;
- (id)init;
- (long long)_currentCachedIDStatusForDestination:(id)arg0 service:(id)arg1 listenerID:(id)arg2;
- (long long)_currentIDStatusForDestination:(id)arg0 service:(id)arg1 listenerID:(id)arg2;
- (long long)_currentIDStatusForDestination:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3;
- (long long)_currentIDStatusForDestination:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 respectExpiry:(bool)arg3 listenerID:(id)arg4;
- (long long)_currentIDStatusForDestination:(id)arg0 service:(id)arg1 respectExpiry:(bool)arg2 listenerID:(id)arg3;
- (long long)_refreshIDStatusForDestination:(id)arg0 service:(id)arg1 listenerID:(id)arg2;
- (long long)_refreshIDStatusForDestination:(id)arg0 service:(id)arg1 preferredFromID:(id)arg2 listenerID:(id)arg3;
- (void)_setCurrentIDStatus:(long long)arg0 forDestination:(id)arg1 service:(id)arg2;
- (void)addDelegate:(id)arg0 forService:(id)arg1 listenerID:(id)arg2 queue:(id)arg3;
- (void)addDelegate:(id)arg0 queue:(id)arg1;
- (void)addListenerID:(id)arg0 forService:(id)arg1;
- (void)dealloc;
- (void)flushQueryCache;
- (void)removeDelegate:(id)arg0 forService:(id)arg1 listenerID:(id)arg2;
- (void)removeDelegate:(id)arg0;
- (void)setFromID:(id)arg0;

@end
