// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMAssociatedMessageChatItem : IMTranscriptChatItem

@property (nonatomic) bool isReaction;
@property (nonatomic) unsigned long long stickerEffectType;
@property (readonly, nonatomic) IMAssociatedMessageGeometryDescriptor geometryDescriptor;
@property (readonly, nonatomic) IMEmojiSticker *emojiSticker;
@property (readonly, nonatomic) IMHandle *sender;
@property (readonly, nonatomic) IMTapback *tapback;
@property (readonly, nonatomic) NSDate *time;
@property (readonly, nonatomic) NSDictionary *messageSummaryInfo;
@property (readonly, nonatomic) NSString *associatedMessageEmoji;
@property (readonly, nonatomic) NSString *associatedMessageGUID;
@property (readonly, nonatomic) _NSRange associatedMessageRange;
@property (readonly, nonatomic) bool failed;
@property (readonly, nonatomic) bool isEmojiSticker;
@property (readonly, nonatomic) bool isFromMe;
@property (readonly, nonatomic) bool parentMessageIsFromMe;
@property (readonly, nonatomic) long long associatedMessageType;
@property (readonly, nonatomic) unsigned long long stickerPositionVersion;

- (IMAssociatedMessageGeometryDescriptor)geometryDescriptor;
- (_NSRange)associatedMessageRange;
- (bool)failed;
- (bool)isEmojiSticker;
- (bool)isFromMe;
- (bool)isReaction;
- (bool)parentMessageIsFromMe;
- (id)_imAssociatedMessageItem;
- (id)_initWithItem:(id)arg0 sender:(id)arg1;
- (id)associatedMessageEmoji;
- (id)associatedMessageGUID;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)emojiSticker;
- (id)message;
- (id)messageSummaryInfo;
- (id)sender;
- (id)tapback;
- (id)time;
- (long long)associatedMessageType;
- (unsigned long long)stickerEffectType;
- (unsigned long long)stickerPositionVersion;
- (void)_setGeometryDescriptor:(IMAssociatedMessageGeometryDescriptor)arg0;
- (void)_setParentMessageIsFromMe:(bool)arg0;
- (void)setEmojiSticker:(id)arg0;
- (void)setIsReaction:(bool)arg0;
- (void)setStickerEffectType:(unsigned long long)arg0;
- (void)setTapback:(id)arg0;

@end
