// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMAssociatedStickerChatItem : IMAssociatedMessageChatItem

@property (readonly, copy, nonatomic) NSString *transferGUID;

- (Class)__ck_chatItemClass;
- (bool)canDelete;
- (bool)supportsCommunicationSafety;
- (id)_initWithItem:(id)arg0 sender:(id)arg1 transferGUID:(id)arg2;
- (id)commSafetyMessageGUID;
- (id)commSafetyTransferGUID;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)description;
- (id)transferGUID;
- (unsigned long long)stickerPositionVersion;
- (void)_refreshGeometryDescriptorFromStickerUserInfo;

@end
