// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMBalloonAppExtension : IMBalloonPlugin

@property (nonatomic) bool canSendDataPayloads;
@property (readonly, nonatomic) NSString *containingBundleIdentifier;
@property (readonly, nonatomic) bool isLaunchProhibited;
@property (readonly, nonatomic) bool shouldBalloonHideAppIcon;
@property (readonly, retain, nonatomic) NSExtension *extension;
@property (readonly, retain, nonatomic) NSNumber *itemID;
@property (readonly, retain, nonatomic) id<PKPlugIn> plugin;
@property (retain) NSUUID *requestIdentifier;
@property (retain, nonatomic) LSPlugInKitProxy *proxy;

- (bool)__ck_preferIconServices;
- (bool)canSendDataPayloads;
- (bool)isBetaPlugin;
- (bool)isLaunchProhibited;
- (bool)shouldBalloonHideAppIcon;
- (bool)shouldBreadcrumbHideAppIcon;
- (id)__ck_breadcrumbImage;
- (id)__ck_browserImageForInterfaceStyle:(long long)arg0;
- (id)__ck_browserImageGenerateSynchronously:(bool)arg0 interfaceStyle:(long long)arg1 allowPlaceholder:(bool)arg2;
- (id)__ck_generateAssetCatalogImageForInterfaceStyle:(long long)arg0;
- (id)__ck_iconServicesBundleIdentifier;
- (id)__ck_statusImage;
- (id)__ck_tapToRadarBalloonPluginImage;
- (id)_generatePlaceholderImageForInterfaceStyle:(long long)arg0;
- (id)_initWithPluginBundle:(id)arg0 extension:(id)arg1 pluginKitProxyClass:(Class)arg2;
- (id)_validProxy;
- (id)adamID;
- (id)containingBundleIdentifier;
- (id)extension;
- (id)initWithPluginBundle:(id)arg0 appBundle:(id)arg1;
- (id)initWithPluginBundle:(id)arg0 extension:(id)arg1;
- (id)initWithPluginBundle:(id)arg0 pluginKitProxy:(id)arg1 extension:(id)arg2;
- (id)itemID;
- (id)plugin;
- (id)proxy;
- (id)requestIdentifier;
- (id)version;
- (void)__ck_generateStatusImage:(id /* block */)arg0;
- (void)setCanSendDataPayloads:(bool)arg0;
- (void)setProxy:(id)arg0;
- (void)setRequestIdentifier:(id)arg0;

@end
