// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMBalloonPluginManager : NSObject

@property (retain, nonatomic) IMBalloonPluginManagerModel *model;

+ (bool)_allowExtensionWithIdentifier:(id)arg0;
+ (bool)_isExtensionBlocklisted:(id)arg0;
+ (bool)_isServerBlocklistedBundleIdentifier:(id)arg0 serverBag:(id)arg1;
+ (bool)_shouldAddFindMyToBlockList;
+ (bool)_shouldAddGenPlaygroundToBlockList;
+ (bool)_shouldAddSafetyMonitorToBlockList;
+ (bool)isRunningPPT;
+ (id)_extensionBlocklist;
+ (id)balloonProviderBundlePathURL;
+ (id)precacheBalloonAppExtensionsForExtensions:(id)arg0;
+ (id)sharedInstance;
+ (id)signpostLogHandle;
+ (void)disableExtensionDiscovery;
+ (void)enableAlternatePathPlugins;
+ (void)setIsRunningPPT:(bool)arg0;

- (Class)dataSourceClassForBundleID:(id)arg0;
- (bool)_shouldSkipUpdatingPluginBundleIdentifier:(id)arg0;
- (id)_appProxyBundleIdentifiersForAppPlugins;
- (id)_currentlyInstalledExtensionsExcludingExtensionPoint:(id)arg0;
- (id)_extensionWithIdentifier:(id)arg0;
- (id)_fallBackMessagesExtensionPluginForBundleID:(id)arg0;
- (id)_identifiersForAppPlugins;
- (id)_infoPlistPathForPluginCreatingFolderIfNeeded:(id)arg0;
- (id)_insertPluginForAppBundle:(id)arg0 balloonProviderBundle:(id)arg1;
- (id)_insertPluginForExtension:(id)arg0 balloonProviderBundle:(id)arg1 precachedBalloonAppExtensions:(id)arg2 timingCollection:(id)arg3;
- (id)_loadAppExtensionDataSourcesForExtensionPoint:(id)arg0;
- (id)_metadataForPluginIdentifier:(id)arg0;
- (id)_pluginPlistPath:(id)arg0;
- (id)_pluginsForWhichWeHaveMetadata;
- (id)_proxyIdentifiersForPlugins;
- (id)allPlugins;
- (id)balloonControllerForIMChatItem:(id)arg0 contextIdentifier:(id)arg1;
- (id)balloonPluginForBundleID:(id)arg0;
- (id)conversationID:(id)arg0 appID:(id)arg1;
- (id)dataSourceForPluginPayload:(id)arg0;
- (id)existingDataSourceForMessageGUID:(id)arg0 bundleID:(id)arg1;
- (id)init;
- (id)localParticipantIdentifierForAppID:(id)arg0 conversationID:(id)arg1;
- (id)model;
- (id)recipientIDForRecipient:(id)arg0 appID:(id)arg1;
- (id)signpostLogHandle;
- (void)_clearPluginMetadataForUninstalledApps;
- (void)_deleteMetaDataForPlugins:(id)arg0;
- (void)_findPluginsInPathInternal:(id)arg0;
- (void)_findPluginsInPaths:(id)arg0;
- (void)_loadAllDataSources;
- (void)_loadAppBundleDataSources;
- (void)_loadAppExtensionDataSources;
- (void)_moveExtensionDataSourcesFromMessagesExtensionPluginToAppExtensions;
- (void)_postDeferredInstalledAppsChangedNotificationIfNecessary;
- (void)_postInstalledAppsChangedNotification;
- (void)_removePluginsForIdentifiers:(id)arg0;
- (void)_removePluginsWithDelay;
- (void)_setPluginsToRemoveAndCallSelectorWithDelay:(id)arg0;
- (void)_storeMetadata:(id)arg0 _forPlugin:(id)arg1;
- (void)_transferUpdated:(id)arg0;
- (void)_updatePluginsForBundles:(id)arg0;
- (void)_updatePluginsForExtensions:(id)arg0 extensionPoint:(id)arg1 precachedBalloonAppExtensions:(id)arg2;
- (void)_updatePluginsForExtensions:(id)arg0 extensionPoint:(id)arg1;
- (void)dealloc;
- (void)insertDataSource:(id)arg0 forGUID:(id)arg1;
- (void)insertPlugin:(id)arg0;
- (void)loadExtensionWithIdentifierIfNeeded:(id)arg0;
- (void)pluginChatItem:(id)arg0 didRelenquishNonResuableController:(id)arg1 contextIdentifier:(id)arg2;
- (void)pluginChatItem:(id)arg0 didRelinquishReusableController:(id)arg1 contextIdentifier:(id)arg2;
- (void)removePluginWithBundleID:(id)arg0;
- (void)setModel:(id)arg0;
- (void)setPluginEnabled:(bool)arg0 identifier:(id)arg1;

@end
