// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMDaemonController : NSObject <IMDaemonControlling_Private, IMDaemonControlling>

@property (nonatomic) bool _blocksConnectionAtResume;
@property (nonatomic) unsigned long long processCapabilities;
@property (readonly) Class superclass;
@property (readonly) unsigned long long hash;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic) IMDaemonListener *listener;
@property (readonly, nonatomic) IMDaemonQueryController *queryController;
@property (readonly, nonatomic) IMDistributingProxy *remoteDaemonProxy;
@property (readonly, nonatomic) NSDictionary *processContext;
@property (readonly, nonatomic) NSMapTable *multiplexedConnections;
@property (readonly, nonatomic) NSMutableDictionary *retainedMultiplexedConnections;
@property (readonly, nonatomic) bool connected;
@property (readonly, nonatomic) bool isConnecting;
@property (readonly, nonatomic) id<IMDaemonConnectionManaging> connection;
@property (readonly, nonatomic) id<IMDaemonProtocol> remoteDaemon;
@property (readonly, nonatomic) id<IMDaemonProtocol> replyingRemoteDaemon;
@property (readonly, nonatomic) id<IMDaemonProtocol> synchronousRemoteDaemon;
@property (readonly, nonatomic) id<IMDaemonProtocol> synchronousReplyingRemoteDaemon;
@property (readonly, nonatomic) os_unfair_lock_s lock;
@property (readonly, nonatomic) unsigned int capabilities;
@property (retain) NSArray *_servicesToAllow;
@property (retain) NSArray *_servicesToDeny;
@property (retain, nonatomic) IMMultiplexedDaemonConnection *anonymousMultiplexedConnection;
@property (retain, nonatomic) NSString *listenerID;
@property (weak, nonatomic) id delegate;

+ (id)sharedController;
+ (id)sharedInstance;
+ (void)_blockUntilSendQueueIsEmpty;

- (bool)_blocksConnectionAtResume;
- (bool)_clientRequiresSynchronousConnectionRescueWithListenerID:(id)arg0;
- (bool)_hasMultiplexedConnectionWithUniqueID:(id)arg0;
- (bool)addListenerID:(id)arg0 capabilities:(unsigned int)arg1;
- (bool)connectToDaemon;
- (bool)connectToDaemonWithLaunch:(bool)arg0 capabilities:(unsigned int)arg1 blockUntilConnected:(bool)arg2;
- (bool)connectToDaemonWithLaunch:(bool)arg0;
- (bool)hasListenerForID:(id)arg0;
- (bool)isConnected;
- (bool)isConnecting;
- (bool)removeListenerID:(id)arg0;
- (bool)setCapabilities:(unsigned int)arg0 forListenerID:(id)arg1;
- (id)_multiplexedConnectionWithUniqueID:(id)arg0 label:(id)arg1 capabilities:(unsigned long long)arg2 context:(id)arg3 retain:(bool)arg4;
- (id)_servicesToAllow;
- (id)_servicesToDeny;
- (id)anonymousMultiplexedConnection;
- (id)connection;
- (id)delegate;
- (id)init;
- (id)listener;
- (id)listenerID;
- (id)multiplexedConnectionWithLabel:(id)arg0 capabilities:(unsigned long long)arg1 context:(id)arg2;
- (id)multiplexedConnections;
- (id)processContext;
- (id)queryController;
- (id)remoteDaemon;
- (id)remoteDaemonProxy;
- (id)replyingRemoteDaemon;
- (id)retainedMultiplexedConnections;
- (id)synchronousRemoteDaemon;
- (id)synchronousReplyingRemoteDaemon;
- (os_unfair_lock_s)lock;
- (unsigned int)capabilities;
- (unsigned int)capabilitiesForListenerID:(id)arg0;
- (unsigned long long)_capabilitiesForMultiplexedConnectionWithUniqueID:(id)arg0;
- (unsigned long long)_clientCapabilitiesForLegacyClientWithListenerID:(id)arg0 requestedCapabilities:(unsigned long long)arg1;
- (unsigned long long)processCapabilities;
- (unsigned long long)requestedCapabilities;
- (void)_blockUntilSendQueueIsEmpty;
- (void)_capabilitiesDidChange;
- (void)_capabilitiesDidChangeWithContextChange:(bool)arg0;
- (void)_connectWithCompletion:(id /* block */)arg0;
- (void)_connectWithContextChange:(bool)arg0;
- (void)_handleDaemonLaunched:(id)arg0;
- (void)_invalidateMultiplexedConnectionWithUniqueID:(id)arg0;
- (void)_noteSetupComplete;
- (void)_reconnectIfNeeded;
- (void)_setBlocksConnectionAtResume:(bool)arg0;
- (void)_setListenerID:(id)arg0;
- (void)_setServicesToAllow:(id)arg0;
- (void)_setServicesToDeny:(id)arg0;
- (void)_updateAnonymousMultiplexedConnectionWithAddedCapabilities:(unsigned long long)arg0;
- (void)blockUntilConnected;
- (void)disconnectFromDaemon;
- (void)killDaemon;
- (void)requestSetup;
- (void)sendQueryWithReply:(bool)arg0 query:(id /* block */)arg1;
- (void)setAnonymousMultiplexedConnection:(id)arg0;
- (void)setDelegate:(id)arg0;
- (void)setProcessCapabilities:(unsigned long long)arg0;

@end
