// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

@protocol IMDaemonListenerProtocol

// required
- (void)pendingACRequestComplete;
- (void)pendingVCRequestComplete;
- (void)vcCapabilitiesChanged:(id)arg0;

@end
