// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMDPersistence.framework/Versions/A/IMDPersistence
@interface IMDPersistentAttachmentController : NSObject

+ (id)sharedInstance;

- (bool)_canDeleteAttachmentPath:(id)arg0;
- (bool)_deleteAttachmentForTransfer:(id)arg0 highQuality:(bool)arg1;
- (bool)_shouldDeleteOriginalPath:(id)arg0 copyWithinAttachmentStore:(bool)arg1 destPath:(id)arg2 storeAtExternalPath:(bool)arg3;
- (bool)cleanseOrphanedFileTransfers;
- (bool)deleteAttachmentsForTransfer:(id)arg0;
- (bool)isSafeToDeleteAttachmentPath:(id)arg0;
- (id)_migrateSiblingAssetsInAttachmentStoreWithOriginalPath:(id)arg0 destinationPath:(id)arg1 withFileManager:(id)arg2;
- (id)_persistentPathForTransfer:(id)arg0 filename:(id)arg1 highQuality:(bool)arg2 chatGUID:(id)arg3 storeAtExternalPath:(bool)arg4;
- (id)_saveAttachmentForTransfer:(id)arg0 highQuality:(bool)arg1 copyWithinAttachmentStore:(bool)arg2 chatGUID:(id)arg3 storeAtExternalPath:(bool)arg4;
- (id)_saveAttachmentForTransfer:(id)arg0 highQuality:(bool)arg1 copyWithinAttachmentStore:(bool)arg2;
- (void)_removeLegacyAttachmentPathsInAttachmentStoreWithOriginalPath:(id)arg0 withFileManager:(id)arg1;
- (void)moveAttachmentsForTransfer:(id)arg0 completion:(id /* block */)arg1;
- (void)saveAttachmentsForTransfer:(id)arg0 chatGUID:(id)arg1 storeAtExternalLocation:(bool)arg2 completion:(id /* block */)arg3;
- (void)saveAttachmentsForTransfer:(id)arg0 completion:(id /* block */)arg1;

@end
