// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMFindMyHandle : NSObject

@property (readonly, nonatomic) FMFHandle *fmfHandle;
@property (readonly, nonatomic) FMLHandle *fmlHandle;
@property (retain, nonatomic) NSString *identifier;

+ (id)handleWithFMFHandle:(id)arg0;
+ (id)handleWithFMLHandle:(id)arg0;
+ (id)handleWithIdentifier:(id)arg0;

- (bool)isEqual:(id)arg0;
- (id)description;
- (id)fmfHandle;
- (id)fmlHandle;
- (id)identifier;
- (id)initWithIdentifier:(id)arg0;
- (unsigned long long)hash;
- (void)setIdentifier:(id)arg0;

@end
