// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMCore.framework/Versions/A/IMCore
@interface IMFindMyDevice : NSObject

@property (readonly, nonatomic) FMFDevice *fmfDevice;
@property (readonly, nonatomic) FMLDevice *fmlDevice;
@property (readonly, nonatomic) NSString *deviceName;
@property (readonly, nonatomic) bool isThisDevice;

+ (id)deviceWithFMFDevice:(id)arg0;
+ (id)deviceWithFMLDevice:(id)arg0;

- (bool)isEqual:(id)arg0;
- (bool)isThisDevice;
- (id)deviceName;
- (id)fmfDevice;
- (id)fmlDevice;
- (id)initWithFMFDevice:(id)arg0 fmlDevice:(id)arg1;
- (unsigned long long)hash;

@end
