// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMSharedUtilities.framework/Versions/A/IMSharedUtilities
@interface IMMutedChatList : NSObject

@property (readonly, nonatomic) NSDictionary *mutedChatList;

+ (id)sharedList;

- (bool)isMutedChat:(id)arg0;
- (bool)isMutedChatForChatIdentifier:(id)arg0 chatStyle:(unsigned char)arg1 groupID:(id)arg2 participantIDs:(id)arg3 lastAddressedHandleID:(id)arg4 originalGroupID:(id)arg5;
- (bool)isMutedChatForMuteIdentifiers:(id)arg0;
- (id)groupHashForParticipantIDs:(id)arg0 lastAddressedHandleID:(id)arg1;
- (id)init;
- (id)muteIdentifiersForChat:(id)arg0;
- (id)muteIdentifiersForChatStyle:(unsigned char)arg0 groupID:(id)arg1 participantIDs:(id)arg2 lastAddressedHandleID:(id)arg3 originalGroupID:(id)arg4 chatIdentifier:(id)arg5;
- (id)mutedChatList;
- (id)unmuteDateForChat:(id)arg0;
- (id)unmuteDateForMuteIdentifier:(id)arg0;
- (id)unmuteDateForMuteIdentifiers:(id)arg0;
- (void)_handleChatGroupIDChangedNotification:(id)arg0;
- (void)_handleMutedChatListChanged;
- (void)_synchronizeMutedChatList:(id)arg0 syncToPairedDevice:(bool)arg1;
- (void)dealloc;
- (void)groupID:(id)arg0 didChangeTo:(id)arg1 forChatIdentifier:(id)arg2;
- (void)muteChat:(id)arg0 untilDate:(id)arg1 syncToPairedDevice:(bool)arg2;
- (void)muteChat:(id)arg0 untilDate:(id)arg1;
- (void)muteChatWithMuteIdentifiers:(id)arg0 untilDate:(id)arg1 syncToPairedDevice:(bool)arg2;
- (void)syncToPairedDeviceIncludingVersion:(bool)arg0;
- (void)unmuteChatWithMuteIdentifiers:(id)arg0 syncToPairedDevice:(bool)arg1;

@end
