// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMSharedUtilities.framework/Versions/A/IMSharedUtilities
@interface IMNicknameAvatarImage : IMNicknameAvatar <NSSecureCoding>

@property (readonly, copy, nonatomic) NSString *imageFilePath;
@property (readonly, copy, nonatomic) NSString *imageName;
@property (readonly, nonatomic) bool contentIsSensitive;
@property (readonly, nonatomic) bool hasImage;
@property (readonly, nonatomic) bool imageExists;

+ (bool)supportsSecureCoding;

- (bool)_writeImageData:(id)arg0 path:(id)arg1 error:(id *)arg2;
- (bool)contentIsSensitive;
- (bool)hasImage;
- (bool)imageExists;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)description;
- (id)dictionaryRepresentation;
- (id)imageData;
- (id)imageFilePath;
- (id)imageName;
- (id)init;
- (id)initWithCoder:(id)arg0;
- (id)initWithDictionaryRepresentation:(id)arg0;
- (id)initWithImageName:(id)arg0 imageData:(id)arg1 imageFilePath:(id)arg2 contentIsSensitive:(bool)arg3 error:(id *)arg4;
- (id)initWithImageName:(id)arg0 imageData:(id)arg1 imageFilePath:(id)arg2 contentIsSensitive:(bool)arg3;
- (id)initWithImageName:(id)arg0 imageFilePath:(id)arg1 contentIsSensitive:(bool)arg2;
- (id)initWithPublicDictionaryMetadataRepresentation:(id)arg0 imageData:(id)arg1 imageFilePath:(id)arg2 contentIsSensitive:(bool)arg3 error:(id *)arg4;
- (id)initWithPublicDictionaryMetadataRepresentation:(id)arg0;
- (id)loadAndReturnImageData;
- (id)publicDictionaryMetadataRepresentation;
- (id)publicDictionaryRepresentation;
- (void)encodeWithCoder:(id)arg0;

@end
