// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/PrivateFrameworks/IMSharedUtilities.framework/Versions/A/IMSharedUtilities
@interface IMTapback : NSObject <NSSecureCoding, NSCopying, IMRemoteObjectCoding>

@property (readonly, nonatomic) IMTapback *counterpart;
@property (readonly, nonatomic) IMTapback *removedTapbackCounterpart;
@property (readonly, nonatomic) IMTapback *visibleTapbackCounterpart;
@property (readonly, nonatomic) bool removed;
@property (readonly, nonatomic) bool sendable;
@property (readonly, nonatomic) long long associatedMessageType;
@property (retain, nonatomic) NSString *languageIdentifier;

+ (bool)isValidAssociatedMessageType:(long long)arg0;
+ (bool)supportsSecureCoding;
+ (id)tapbackWithAssociatedMessageType:(long long)arg0;

- (bool)_isAssociatedMessageContentTypeTextInMessageSummaryInfo:(id)arg0;
- (bool)_isAttachmentOnlyMessageText:(id)arg0 isAdaptiveImageGlyphProvider:(id /* block */)arg1;
- (bool)isEqual:(id)arg0;
- (bool)isRemoved;
- (bool)isSendable;
- (bool)shouldQuoteContentString:(id)arg0;
- (id)_attributedAssociatedMessageSummaryFromMessageSummaryInfo:(id)arg0 isAdaptiveImageGlyphProvider:(id /* block */)arg1 isCommSafetySensitiveProvider:(id /* block */)arg2 adaptiveImageGlyphProvider:(id /* block */)arg3 effectString:(id)arg4;
- (id)_convertDatabaseFormatAssociatedMessageSummaryToDisplayFormat:(id)arg0 isAdaptiveImageGlyphProvider:(id /* block */)arg1 isCommSafetySensitiveProvider:(id /* block */)arg2 adaptiveImageGlyphProvider:(id /* block */)arg3;
- (id)_plainStringAssociatedMessageSummaryFromMessageSummaryInfo:(id)arg0 isAdaptiveImageGlyphProvider:(id /* block */)arg1;
- (id)_plainStringReactionFromAttributedReactionString:(id)arg0;
- (id)actionStringFormatWithAdaptiveImageGlyphAvailable:(bool)arg0;
- (id)adaptiveImageGlyphForPreviewStringWithAdaptiveImageGlyphProvider:(id /* block */)arg0;
- (id)adjustMessageSummaryInfoForSending:(id)arg0;
- (id)backwardCompatibilityStringFormatForMessageSummaryInfo:(id)arg0;
- (id)backwardCompatibilityStringWithMessageSummaryInfo:(id)arg0 isAdaptiveImageGlyphProvider:(id /* block */)arg1 isCommSafetySensitiveProvider:(id /* block */)arg2;
- (id)contentTypeStringForMessageSummaryInfo:(id)arg0;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)counterpart;
- (id)description;
- (id)emojiReactionForPreviewString;
- (id)init;
- (id)initWithAssociatedMessageType:(long long)arg0;
- (id)initWithCoder:(id)arg0;
- (id)initWithIMRemoteObjectSerializedDictionary:(id)arg0;
- (id)languageIdentifier;
- (id)messageForChat:(id)arg0 messageGUID:(id)arg1 messagePartRange:(_NSRange)arg2 messageSummaryInfo:(id)arg3 threadIdentifier:(id)arg4;
- (id)previewAttributedStringWithMessageSummaryInfo:(id)arg0 isAdaptiveImageGlyphProvider:(id /* block */)arg1 isCommSafetySensitiveProvider:(id /* block */)arg2 adaptiveImageGlyphProvider:(id /* block */)arg3 senderDisplayName:(id)arg4 isFromMe:(bool)arg5 effectString:(id)arg6;
- (id)previewStringFormatForMessageSummaryInfo:(id)arg0 adaptiveImageGlyphAvailable:(bool)arg1 isFromMe:(bool)arg2;
- (id)reactionStringWithAdaptiveImageGlyph:(id)arg0 isCommSafetySensitiveProvider:(id /* block */)arg1;
- (id)removedTapbackCounterpart;
- (id)visibleTapbackCounterpart;
- (long long)associatedMessageType;
- (void)encodeWithCoder:(id)arg0;
- (void)encodeWithIMRemoteObjectSerializedDictionary:(id)arg0;
- (void)setLanguageIdentifier:(id)arg0;

@end
