// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/Frameworks/Messages.framework/Versions/A/Messages
@interface MSMessageLayout : NSObject <NSCopying>

- (id)_init;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)init;

@end
