// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/iOSSupport/System/Library/Frameworks/Messages.framework/Versions/A/Messages
@interface MSSession : NSObject <NSSecureCoding>

@property (readonly, nonatomic) NSUUID *identifier;

+ (bool)supportsSecureCoding;

- (bool)isEqual:(id)arg0;
- (id)description;
- (id)identifier;
- (id)init;
- (id)initWithCoder:(id)arg0;
- (id)initWithIdentifier:(id)arg0;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg0;

@end
