// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/SPOwner.framework/Versions/A/SPOwner
@interface SPBeaconLocation : NSObject <NSCopying, NSSecureCoding>

@property (copy, nonatomic) NSDate *timestamp;
@property (copy, nonatomic) NSString *source;
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
@property (readonly, nonatomic) double horizontalAccuracy;

+ (bool)supportsSecureCoding;

- (double)horizontalAccuracy;
- (double)latitude;
- (double)longitude;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)debugDescription;
- (id)initWithCoder:(id)arg0;
- (id)initWithTimestamp:(id)arg0 latitude:(double)arg1 longitude:(double)arg2 horizontalAccuracy:(double)arg3 source:(id)arg4;
- (id)source;
- (id)timestamp;
- (void)encodeWithCoder:(id)arg0;
- (void)setLatitude:(double)arg0;
- (void)setLongitude:(double)arg0;
- (void)setSource:(id)arg0;
- (void)setTimestamp:(id)arg0;

@end
