// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/Stickers.framework/Versions/A/Stickers
@interface STKStickerUsageManager : NSObject

+ (id)sharedManager;

- (id)init;
- (unsigned long long)stickerCountsForBundleIdentifier:(id)arg0;
- (void)logStickerWithStickerIdentifier:(id)arg0 bundleIdentifier:(id)arg1;

@end
