// Generated by swift/Tools/private-api on macOS 15.6.1.
// Read from the Objective-C runtime, not from a binary — see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/Versions/A/TelephonyUtilities
@interface TUAnswerRequest : NSObject <NSSecureCoding, TUCallRequest, TUVideoRequest>

@property (copy, nonatomic) NSString *sourceIdentifier;
@property (copy, nonatomic) NSString *uniqueProxyIdentifier;
@property (nonatomic) CGSize localLandscapeAspectRatio;
@property (nonatomic) CGSize localPortraitAspectRatio;
@property (nonatomic) bool allowBluetoothAnswerWithoutDowngrade;
@property (nonatomic) bool downgradeToAudio;
@property (nonatomic) bool pauseVideoToStart;
@property (nonatomic) bool screeningDueToUserInteraction;
@property (nonatomic) bool sendToScreening;
@property (nonatomic) bool wantsHoldMusic;
@property (nonatomic) long long behavior;
@property (readonly) Class superclass;
@property (readonly) unsigned long long hash;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (retain, nonatomic) IDSDestination *endpointIDSDestination;
@property (retain, nonatomic) NSDate *dateAnswered;
@property (retain, nonatomic) NSString *endpointRapportEffectiveIdentifier;
@property (retain, nonatomic) NSString *endpointRapportMediaSystemIdentifier;

+ (bool)supportsSecureCoding;

- (CGSize)localLandscapeAspectRatio;
- (CGSize)localPortraitAspectRatio;
- (bool)allowBluetoothAnswerWithoutDowngrade;
- (bool)downgradeToAudio;
- (bool)pauseVideoToStart;
- (bool)screeningDueToUserInteraction;
- (bool)sendToScreening;
- (bool)wantsHoldMusic;
- (id)dateAnswered;
- (id)description;
- (id)endpointIDSDestination;
- (id)endpointRapportEffectiveIdentifier;
- (id)endpointRapportMediaSystemIdentifier;
- (id)init;
- (id)initWithCall:(id)arg0;
- (id)initWithCoder:(id)arg0;
- (id)initWithUniqueProxyIdentifier:(id)arg0;
- (id)sourceIdentifier;
- (id)uniqueProxyIdentifier;
- (long long)behavior;
- (void)encodeWithCoder:(id)arg0;
- (void)setAllowBluetoothAnswerWithoutDowngrade:(bool)arg0;
- (void)setBehavior:(long long)arg0;
- (void)setDateAnswered:(id)arg0;
- (void)setDowngradeToAudio:(bool)arg0;
- (void)setEndpointIDSDestination:(id)arg0;
- (void)setEndpointRapportEffectiveIdentifier:(id)arg0;
- (void)setEndpointRapportMediaSystemIdentifier:(id)arg0;
- (void)setLocalLandscapeAspectRatio:(CGSize)arg0;
- (void)setLocalPortraitAspectRatio:(CGSize)arg0;
- (void)setPauseVideoToStart:(bool)arg0;
- (void)setScreeningDueToUserInteraction:(bool)arg0;
- (void)setSendToScreening:(bool)arg0;
- (void)setSourceIdentifier:(id)arg0;
- (void)setUniqueProxyIdentifier:(id)arg0;
- (void)setWantsHoldMusic:(bool)arg0;

@end
