//  Enrollment
//  Issuing a per-device credential, so a leak stops meaning "change it for everyone".
//
//  The problem this solves
//  -----------------------
//  Today every client shares one password. There is no device identity, so there is nothing
//  to revoke: a phone that falls into the wrong hands can only be locked out by changing the
//  password for every device the user owns. `AuthenticatedPrincipal.deviceID` is nil under
//  password auth for exactly that reason.
//
//  **The app ships with no credentials.** Nothing is baked into a client binary — the server
//  MINTS a credential for one specific device at setup, and that device uses it from then on.
//  This is dynamic client registration (RFC 7591 in shape) followed by an ordinary
//  `client_credentials` grant.
//
//  All of it is dormant by default. See AuthenticationChain and `docs/AUTH.md`.

import BBCore
import Crypto
import Foundation
import _CryptoExtras

// MARK: - Enrollment codes

/// A short-lived code shown in the server UI, for users who would rather not type the server
/// password into a client.
///
/// Crockford base32: no I, L, O or U, so a code read off a screen and typed into a phone
/// cannot become a different valid code through a misread character. `U` is excluded
/// separately from the vowel-removal rationale — it is dropped to avoid accidental obscenity.
public struct EnrollmentCode: Sendable, Equatable {

  /// 8 characters of Crockford base32 is 40 bits. Short enough to type, and paired with a
  /// five-minute TTL and single use, far too much to guess.
  public static let length = 8
  public static let alphabet = Array("0123456789ABCDEFGHJKMNPQRSTVWXYZ")
  public static let lifetime: Duration = .seconds(300)

  public let value: String
  public let expiresAt: Date

  public init(value: String, expiresAt: Date) {
    self.value = value
    self.expiresAt = expiresAt
  }

  /// Mints a code from the system CSPRNG.
  public static func generate(now: Date = Date()) -> EnrollmentCode {
    precondition(alphabet.count == 32, "a non-power-of-two alphabet biases the modulo")
    var generator = SystemRandomNumberGenerator()
    let value = String(
      (0..<length).map { _ in
        alphabet[Int(generator.next(upperBound: UInt64(alphabet.count)))]
      })
    return EnrollmentCode(
      value: value,
      expiresAt: now.addingTimeInterval(lifetime.seconds)
    )
  }

  public func isValid(at moment: Date = Date()) -> Bool {
    moment < expiresAt
  }

  /// Normalises what a user typed.
  ///
  /// Crockford's decoding rules, which exist because people transcribe these by hand:
  /// case is irrelevant, `I` and `L` read as `1`, `O` reads as `0`, and hyphens people add
  /// for readability are ignored.
  public static func normalize(_ input: String) -> String {
    input
      .uppercased()
      .replacingOccurrences(of: "-", with: "")
      .replacingOccurrences(of: " ", with: "")
      .map { character -> Character in
        switch character {
        case "I", "L": "1"
        case "O": "0"
        default: character
        }
      }
      .reduce(into: "") { $0.append($1) }
  }

  /// Constant-time comparison against a candidate.
  ///
  /// A code is a credential, and comparing credentials with `==` leaks their prefix through
  /// timing. Forty bits is not much to leak a byte at a time.
  public func matches(_ candidate: String) -> Bool {
    ConstantTime.equals(value, Self.normalize(candidate))
  }
}

// MARK: - Secret hashing

/// How a client secret is stored.
///
/// **scrypt, not the Argon2id the plan named.** swift-crypto ships no Argon2, and adding a
/// dependency to get one would put unaudited crypto in the trust path for no gain: scrypt is
/// memory-hard in the same way and for the same reason, which is the property that actually
/// matters here.
///
/// Worth stating plainly what this is defending against, because it is *not* the usual one.
/// A client secret is 32 bytes from the system CSPRNG — not a human-chosen password — so
/// there is no dictionary and no offline guessing attack to slow down. Against a 256-bit
/// random input a single SHA-256 would be equally unbreakable. The memory-hard KDF is kept
/// anyway because it costs one login's worth of milliseconds and removes the need to reason
/// about that argument again if the secret's provenance ever changes.
///
/// **That reasoning has a precondition, and it is enforced:** secrets are generated by
/// `ClientSecret.generate()` and never accepted from a caller. A user-chosen secret would
/// invalidate the entropy argument entirely.
public struct SecretHash: Sendable, Equatable, Codable {

  /// scrypt parameters. Interactive-login tier: ~16MB and a few tens of milliseconds, which
  /// is imperceptible on a token request and expensive to parallelise.
  public static let rounds = 16_384
  public static let blockSize = 8
  public static let parallelism = 1
  public static let outputBytes = 32

  public let salt: Data
  public let hash: Data

  public init(salt: Data, hash: Data) {
    self.salt = salt
    self.hash = hash
  }

  /// Hashes a secret with a fresh random salt.
  public static func make(_ secret: String) throws -> SecretHash {
    var salt = Data(count: 16)
    salt.withUnsafeMutableBytes { buffer in
      guard let base = buffer.bindMemory(to: UInt8.self).baseAddress else { return }
      for offset in 0..<buffer.count {
        base[offset] = UInt8.random(in: 0...255, using: &SystemRandomNumberGenerator.shared)
      }
    }
    return SecretHash(salt: salt, hash: try derive(secret, salt: salt))
  }

  /// Constant-time verification.
  public func verify(_ candidate: String) -> Bool {
    guard let derived = try? Self.derive(candidate, salt: salt) else { return false }
    return ConstantTime.equals(derived, hash)
  }

  static func derive(_ secret: String, salt: Data) throws -> Data {
    let key = try KDF.Scrypt.deriveKey(
      from: Data(secret.utf8),
      salt: salt,
      outputByteCount: outputBytes,
      rounds: rounds,
      blockSize: blockSize,
      parallelism: parallelism
    )
    return key.withUnsafeBytes { Data($0) }
  }
}

extension SystemRandomNumberGenerator {
  /// A shared instance, so a loop does not construct one per byte.
  nonisolated(unsafe) static var shared = SystemRandomNumberGenerator()
}

// MARK: - Constant time

public enum ConstantTime {

  /// Compares without short-circuiting.
  ///
  /// Length is compared first and is not itself secret — the values here are fixed-length
  /// by construction. What must not leak is *where* two same-length values diverge, which
  /// an early return would reveal one byte at a time.
  public static func equals(_ lhs: Data, _ rhs: Data) -> Bool {
    guard lhs.count == rhs.count else { return false }
    var difference: UInt8 = 0
    for (left, right) in zip(lhs, rhs) { difference |= left ^ right }
    return difference == 0
  }

  public static func equals(_ lhs: String, _ rhs: String) -> Bool {
    equals(Data(lhs.utf8), Data(rhs.utf8))
  }
}

// MARK: - Credentials

/// The pair the server mints. The secret is returned ONCE and never retrievable again.
public struct ClientCredentials: Sendable, Equatable {
  public let clientId: String
  /// Plaintext, and the only time it exists in this form. Stored hashed.
  public let clientSecret: String

  public init(clientId: String, clientSecret: String) {
    self.clientId = clientId
    self.clientSecret = clientSecret
  }
}

public enum ClientSecret {
  /// 32 bytes from the system CSPRNG, base64url without padding.
  ///
  /// Never accepts a caller-supplied value — see the note on SecretHash. The entropy here
  /// is what makes the hashing choice sound.
  public static func generate() -> String {
    var bytes = [UInt8](repeating: 0, count: 32)
    for index in bytes.indices {
      bytes[index] = UInt8.random(in: 0...255, using: &SystemRandomNumberGenerator.shared)
    }
    return Data(bytes).base64EncodedString()
      .replacingOccurrences(of: "+", with: "-")
      .replacingOccurrences(of: "/", with: "_")
      .replacingOccurrences(of: "=", with: "")
  }

  public static func generateIdentifier() -> String {
    "bb_" + UUID().uuidString.lowercased().replacingOccurrences(of: "-", with: "")
  }
}

// MARK: - Devices

public struct EnrolledDevice: Sendable, Equatable, Codable, Identifiable {
  public let id: DeviceID
  public let clientId: String
  public var secret: SecretHash
  public var name: String
  public var platform: String
  public var scopes: Set<Scope>
  /// X25519 public key for sealed-v2, when the device registered one. This is the same key
  /// §4 encrypts to — one handshake covering identity, codecs and encryption.
  public var publicKey: Data?
  public var supportedCodecs: [String]
  public let enrolledAt: Date
  public var lastSeenAt: Date?
  public var isRevoked: Bool

  public init(
    id: DeviceID,
    clientId: String,
    secret: SecretHash,
    name: String,
    platform: String,
    scopes: Set<Scope> = Scope.all,
    publicKey: Data? = nil,
    supportedCodecs: [String] = [],
    enrolledAt: Date = Date(),
    lastSeenAt: Date? = nil,
    isRevoked: Bool = false
  ) {
    self.id = id
    self.clientId = clientId
    self.secret = secret
    self.name = name
    self.platform = platform
    self.scopes = scopes
    self.publicKey = publicKey
    self.supportedCodecs = supportedCodecs
    self.enrolledAt = enrolledAt
    self.lastSeenAt = lastSeenAt
    self.isRevoked = isRevoked
  }
}

public enum EnrollmentError: BBError, Equatable {
  case notEnabled
  case invalidEnrollmentCode
  case enrollmentCodeExpired
  case invalidClientCredentials
  case deviceRevoked
  case unknownDevice
}

extension EnrollmentError {
  public var code: String {
    switch self {
    case .notEnabled: "enrollment.not_enabled"
    case .invalidEnrollmentCode: "enrollment.invalid_code"
    case .enrollmentCodeExpired: "enrollment.code_expired"
    case .invalidClientCredentials: "enrollment.invalid_credentials"
    case .deviceRevoked: "enrollment.device_revoked"
    case .unknownDevice: "enrollment.unknown_device"
    }
  }

  public var domain: String { "Auth" }

  /// Never. Every case here is reachable by anyone who can reach the server, so raising a
  /// notification would hand a stranger a way to fill someone's screen.
  public var isUserFacing: Bool { false }

  public var title: String { "A device could not enrol" }

  public var body: String {
    switch self {
    case .notEnabled: "Token authentication is not enabled on this server."
    case .invalidEnrollmentCode: "That enrolment code is not valid."
    case .enrollmentCodeExpired: "That enrolment code has expired."
    case .invalidClientCredentials: "Those client credentials were not accepted."
    case .deviceRevoked: "That device has been revoked."
    case .unknownDevice: "That device is not enrolled."
    }
  }
}
