//  PacketCodec
//  Engine.IO and Socket.IO framing, written against golden vectors.
//
//  The vectors in Tests/ProtocolTests/ProtocolFixtures were generated by socket.io-parser
//  4.2.7 and engine.io-parser 5.2.3 — the canonical implementations — so "correct" here means
//  byte-identical to what those produce, not "looks right". That matters because a socket
//  frame that is subtly wrong does not fail loudly: the client silently ignores it and
//  messages just stop arriving.
//
//  Details that are easy to get wrong and are pinned by vectors:
//    - A packet for the default namespace `/` emits NO namespace segment. Emitting `/,`
//      breaks every client.
//    - The ack id sits between the type digit and the payload with no separator: `217[...]`
//      is EVENT, ack id 17.
//    - CONNECT with no data is bare `0`, not `0{}`.
//    - Engine.IO payloads join with the record separator U+001E, not a comma or newline.
//    - Engine.IO wraps Socket.IO: `4` (MESSAGE) then the Socket.IO packet, so an event on
//      the wire reads `42[...]`.
//
//  See `docs/EVENTS.md`.

import BBSerialization
import Foundation

// MARK: - Engine.IO

public enum EngineIOPacketType: Int, Sendable, CaseIterable {
  case open = 0
  case close = 1
  case ping = 2
  case pong = 3
  case message = 4
  case upgrade = 5
  case noop = 6
}

public struct EngineIOPacket: Sendable, Equatable {
  public let type: EngineIOPacketType
  public let payload: String

  public init(type: EngineIOPacketType, payload: String = "") {
    self.type = type
    self.payload = payload
  }

  public func encode() -> String { "\(type.rawValue)\(payload)" }

  public static func decode(_ text: String) -> EngineIOPacket? {
    guard let first = text.first,
      let digit = first.wholeNumberValue,
      let type = EngineIOPacketType(rawValue: digit)
    else { return nil }
    return EngineIOPacket(type: type, payload: String(text.dropFirst()))
  }

  /// `2probe` / `3probe`, the transport-upgrade handshake. The upgrade fails silently
  /// without these and the client stays on polling forever — working, but with every
  /// event delayed by a poll cycle.
  public static let pingProbe = EngineIOPacket(type: .ping, payload: "probe")
  public static let pongProbe = EngineIOPacket(type: .pong, payload: "probe")
}

/// The open handshake body.
///
/// The three timeouts are not defaults — they are the current server's explicit values, and
/// a client that has been told `pingTimeout: 120000` will wait two minutes before deciding
/// the connection is dead. Shortening them changes reconnect behavior in the field.
public struct EngineIOHandshake: Sendable {
  public let sid: String
  public let upgrades: [String]
  public let pingInterval: Int
  public let pingTimeout: Int
  public let maxPayload: Int

  public init(
    sid: String,
    upgrades: [String] = ["websocket"],
    pingInterval: Int = 60_000,
    pingTimeout: Int = 120_000,
    maxPayload: Int = 100_000_000
  ) {
    self.sid = sid
    self.upgrades = upgrades
    self.pingInterval = pingInterval
    self.pingTimeout = pingTimeout
    self.maxPayload = maxPayload
  }

  /// Built by hand rather than through JSONSerialization because key ORDER is part of what
  /// the golden vectors compare, and Foundation does not promise one. A real client parses
  /// this as JSON and does not care — but a test that cannot compare strings is a much
  /// weaker test, so the ordering is worth keeping.
  public func encode() throws -> String {
    let upgradeList =
      upgrades
      .map { "\"\($0)\"" }
      .joined(separator: ",")
    return "0{\"sid\":\"\(sid)\",\"upgrades\":[\(upgradeList)],"
      + "\"pingInterval\":\(pingInterval),\"pingTimeout\":\(pingTimeout),"
      + "\"maxPayload\":\(maxPayload)}"
  }
}

public enum EngineIOPayload {

  /// U+001E RECORD SEPARATOR. Not a comma, not a newline.
  public static let separator: Character = "\u{1e}"

  /// Batches packets for the polling transport. WebSocket sends one packet per frame and
  /// never uses this.
  public static func encode(_ packets: [String]) -> String {
    packets.joined(separator: String(separator))
  }

  public static func decode(_ payload: String) -> [String] {
    payload.split(separator: separator, omittingEmptySubsequences: false).map(String.init)
  }
}

// MARK: - Socket.IO

public enum SocketIOPacketType: Int, Sendable, CaseIterable {
  case connect = 0
  case disconnect = 1
  case event = 2
  case ack = 3
  case connectError = 4
  case binaryEvent = 5
  case binaryAck = 6
}

public struct SocketIOPacket: Sendable {
  public let type: SocketIOPacketType
  /// `/` is the default namespace and is NEVER written to the wire.
  public let namespace: String
  /// For EVENT: `[name, payload…]`. For CONNECT and CONNECT_ERROR: an object.
  public let data: JSONValue?
  public let ackID: Int?

  public init(
    type: SocketIOPacketType,
    namespace: String = "/",
    data: JSONValue? = nil,
    ackID: Int? = nil
  ) {
    self.type = type
    self.namespace = namespace
    self.data = data
    self.ackID = ackID
  }

  public func encode() throws -> String {
    var text = String(type.rawValue)

    // Only a non-default namespace is written, and it is comma-terminated.
    if namespace != "/" && !namespace.isEmpty {
      text += namespace + ","
    }
    // Immediately after the type (and namespace), with no separator: `217[...]`.
    if let ackID {
      text += String(ackID)
    }
    if let data {
      guard let encoded = String(data: try data.serialize(), encoding: .utf8) else {
        return text
      }
      text += encoded
    }
    return text
  }

  /// A broadcast event.
  ///
  /// Under legacy-v1 the payload is the RAW object, never envelope-wrapped. Wrapping it —
  /// which would make the socket consistent with the HTTP API — breaks every client, since
  /// they read fields straight off the emitted object.
  public static func event(name: String, payload: JSONValue?, ackID: Int? = nil) -> SocketIOPacket {
    SocketIOPacket(
      type: .event,
      data: .array([.string(name), payload ?? .null]),
      ackID: ackID
    )
  }

  public static func ack(id: Int, payload: JSONValue?) -> SocketIOPacket {
    SocketIOPacket(type: .ack, data: .array([payload ?? .null]), ackID: id)
  }

  public static func connect(sid: String?) -> SocketIOPacket {
    // Bare `0` when there is no sid. `0{}` is a different packet on the wire.
    SocketIOPacket(
      type: .connect,
      data: sid.map { .object(["sid": .string($0)]) }
    )
  }

  public static func connectError(message: String) -> SocketIOPacket {
    SocketIOPacket(type: .connectError, data: .object(["message": .string(message)]))
  }

  // MARK: Decoding

  public static func decode(_ text: String) -> SocketIOPacket? {
    var remainder = Substring(text)

    guard let first = remainder.first,
      let digit = first.wholeNumberValue,
      let type = SocketIOPacketType(rawValue: digit)
    else { return nil }
    remainder = remainder.dropFirst()

    var namespace = "/"
    if remainder.first == "/" {
      if let comma = remainder.firstIndex(of: ",") {
        namespace = String(remainder[remainder.startIndex..<comma])
        remainder = remainder[remainder.index(after: comma)...]
      } else {
        // A namespace with no payload after it, so the whole remainder is the name.
        namespace = String(remainder)
        remainder = remainder[remainder.endIndex...]
      }
    }

    var ackID: Int?
    let digits = remainder.prefix { $0.isNumber }
    if !digits.isEmpty {
      ackID = Int(digits)
      remainder = remainder.dropFirst(digits.count)
    }

    var data: JSONValue?
    if !remainder.isEmpty {
      data = try? JSONValue.parse(Data(remainder.utf8))
    }

    return SocketIOPacket(type: type, namespace: namespace, data: data, ackID: ackID)
  }

  /// The event name and its arguments, for an EVENT packet.
  public var eventContents: (name: String, arguments: [JSONValue])? {
    guard type == .event || type == .binaryEvent,
      case .array(let items) = data,
      case .string(let name)? = items.first
    else { return nil }
    return (name, Array(items.dropFirst()))
  }
}

// MARK: - Combined

/// A Socket.IO packet wrapped for the wire: Engine.IO MESSAGE plus the Socket.IO packet.
public enum WireFrame {

  public static func encode(_ packet: SocketIOPacket) throws -> String {
    try EngineIOPacket(type: .message, payload: packet.encode()).encode()
  }

  public static func decode(_ text: String) -> SocketIOPacket? {
    guard let engine = EngineIOPacket.decode(text), engine.type == .message else { return nil }
    return SocketIOPacket.decode(engine.payload)
  }
}
