// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary; see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/AVConference.framework/Versions/A/AVConference
@interface AVCamera : NSObject

+ (id)UIDforDeviceID:(unsigned int)arg0;
+ (id)cameraList;
+ (unsigned int)deviceIDForUID:(id)arg0;

- (bool)cameraSupportsWidth:(int)arg0 height:(int)arg1;
- (bool)is1080HD;
- (bool)isIrisOpen;
- (bool)isMinimumFrameRateSupportedForStreamID:(unsigned int)arg0 withFormatDescriptor:(opaqueCMFormatDescription *)arg1;
- (bool)isSuspended;
- (bool)isWVGA;
- (bool)isWidescreen;
- (id)GUID;
- (id)description;
- (id)displayName;
- (id)initWithCMIODeviceID:(unsigned int)arg0;
- (unsigned int)cameraType;
- (unsigned int)deviceID;

@end
