// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary; see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/AVConference.framework/Versions/A/AVConference
@interface AVConferencePreview : NSObject

@property (retain, nonatomic) NSObject<AVConferencePreviewClientDelegate> *delegate;

+ (id)AVConferencePreviewSingleton;

- (bool)isCameraZoomAvailable;
- (bool)isPreviewRunning;
- (double)currentZoomFactor;
- (double)maxZoomFactor;
- (id)allocWithZone:(_NSZone *)arg0;
- (id)autorelease;
- (id)copyWithZone:(_NSZone *)arg0;
- (id)delegate;
- (id)init;
- (id)localCameraUID;
- (id)localScreenAttributesForVideoAttributes:(id)arg0;
- (id)localVideoAttributes;
- (id)localVideoLayer:(bool)arg0;
- (id)retain;
- (unsigned int)localCamera;
- (unsigned long long)retainCount;
- (void)addStickerWithURL:(id)arg0 isFaceSticker:(bool)arg1 atPosition:(CGPoint)arg2 identifier:(id)arg3;
- (void)beginPIPToPreviewAnimation;
- (void)beginPreviewToPIPAnimation;
- (void)cameraCFramingAvailabilityDidChange:(bool)arg0;
- (void)cameraDidBecomeAvailableForUniqueID:(id)arg0;
- (void)cameraDidBecomeInterruptedForForUniqueID:(id)arg0 reason:(long long)arg1;
- (void)cameraZoomAvailabilityDidChange:(bool)arg0 currentZoomFactor:(double)arg1 maxZoomFactor:(double)arg2;
- (void)clearAllStickers:(bool)arg0;
- (void)connectLayer:(id)arg0 withSlot:(unsigned int)arg1;
- (void)dealloc;
- (void)didChangeLocalCameraUID:(id)arg0;
- (void)didChangeLocalScreenAttributes:(id)arg0;
- (void)didChangeLocalVideoAttributes:(id)arg0;
- (void)didGetSnapshot:(id)arg0;
- (void)didPausePreview;
- (void)didReceiveCommError;
- (void)didReceiveErrorFromCameraUniqueID:(id)arg0 error:(id)arg1;
- (void)didStartPreview;
- (void)didStopPreview;
- (void)endPIPToPreviewAnimation;
- (void)endPreviewToPIPAnimation;
- (void)getSnapshot;
- (void)pausePreview;
- (void)registerBlocksForDelegateNotifications;
- (void)release;
- (void)resetLocalCameraAfterServerDisconnect;
- (void)setAnimoji:(id)arg0;
- (void)setCameraZoomFactor:(double)arg0 withRate:(double)arg1;
- (void)setCameraZoomFactor:(double)arg0;
- (void)setCinematicFramingEnabled:(bool)arg0;
- (void)setDelegate:(id)arg0;
- (void)setFollowSystemCameraEnabled:(bool)arg0;
- (void)setLocalCamera:(unsigned int)arg0;
- (void)setLocalCameraWithUID:(id)arg0;
- (void)setLocalScreenAttributes:(id)arg0;
- (void)setLocalVideoAttributes:(id)arg0;
- (void)setLocalVideoLayer:(id)arg0 front:(bool)arg1;
- (void)setMemoji:(id)arg0;
- (void)startPreview;
- (void)startPreviewUnpausing:(bool)arg0;
- (void)stopPreview;

@end
