// Generated by swift/Tools/private-api on macOS 14.6.1.
// Read from the Objective-C runtime, not from a binary; see dump-headers.m.
// DO NOT EDIT: regenerate with Tools/private-api/dump-headers.sh.

// Image: /System/Library/PrivateFrameworks/AVConference.framework/Versions/A/AVConference
@interface VCCameraPreview : NSObject

@property (nonatomic) bool started;

- (bool)isStarted;
- (id)description;
- (void)setStarted:(bool)arg0;

@end
